RustCrypto/elliptic-curves

Cargo.toml, elliptic-curve-crate/.gitignore, elliptic-curve-crate/Cargo.toml, elliptic-curve-crate/LICENSE-APACHE, elliptic-curve-crate/LICENSE-MIT, p256/Cargo.toml, p256/LICENSE-APACHE, p256/LICENSE-MIT, p256/README.md, p256/src/lib.rs, p384/Cargo.toml, p384/LICENSE-APACHE, p384/LICENSE-MIT, p384/README.md, p384/src/lib.rs, p521/Cargo.toml, p521/LICENSE-APACHE, p521/LICENSE-MIT, p521/README.md, p521/src/lib.rs
Boilerplate for the `p256`, `p384`, and `p521` crates
=> NIST curve crate boilerplate

k256/CHANGES.md, k256/Cargo.toml
=> k256 v0.1.0

p256/CHANGES.md, p256/Cargo.toml
=> p256 v0.1.0

k256/src/lib.rs, p256/src/lib.rs, p384/src/lib.rs, p521/src/lib.rs
...from all crates for specific curves
=> Re-export the 'elliptic-curve' crate

README.md
Adds a small note to the toplevel README.md
=> README.md: document crates with `arithmetic`

p256/CHANGES.md, p256/Cargo.toml
- Constant time scalar multiplication ([#18])
- Group operation ([#15])
[#18]: https://github.com/RustCrypto/elliptic-curves/pull/18
[#15]: https://github.com/RustCrypto/elliptic-curves/pull/15
=> p256 v0.2.0

k256/CHANGES.md, k256/Cargo.toml
- Field arithmetic, point addition/doubling, and scalar multiplication ([#19])
[#19]: https://github.com/RustCrypto/elliptic-curves/pull/19
=> k256 v0.2.0

README.md, elliptic-curve-crate/README.md, k256/README.md, p256/README.md, p384/README.md, p521/README.md
Update them to use GitHub Actions instead of Travis
=> README.md(s): fix build status badges

.github/workflows/workspace.yml
=> .github: add CodeCov job

.github/workflows/elliptic-curve-crate.yml, .github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/p521.yml, .github/workflows/security-audit.yml, Cargo.lock
Configure environment and working directory globally
=> .github: use global env and working dir

k256/Cargo.toml, k256/README.md, k256/src/lib.rs, p256/Cargo.toml, p256/README.md, p384/Cargo.toml, p384/README.md, p521/Cargo.toml, p521/README.md
- Use consistent headlines starting with "RustCrypto:" and ending with "elliptic curve"
- Add an "About" section to all README.mds
- Add curve aliases to Cargo.toml description and keywords
=> Improve documentation (all crates)

elliptic-curve-crate/README.md, k256/README.md
Previously was something of a dangling participle
=> k256/README.md: tweak wording

k256/src/arithmetic/scalar.rs
Adds a method for determining if a scalar is greater than or equal to the modulus divided by 2 (in constant time).
The ultimate purpose of this method is implementing non-malleable ECDSA signatures as described in [BIP 0062: Dealing with Malleability](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki), namely ensuring signatures are [low-S normalized](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#Low_S_values_in_signatures).
In the event the S-component of an ECDSA signature is "high", it should be normalized (to be low) by subtracting it from the modulus.
=> k256: add `Scalar::is_high`

k256/src/arithmetic/scalar.rs
Implement negation (modulo n) for `Scalar`, for the purposes of implementing low-S normalization of ECDSA signatures (see #60).
=> k256: impl Neg for Scalar

k256/src/ecdsa/recoverable.rs
Moves some of the complexity (some of which is incidental due to subtle#73) in validating the `r` and `s` components of signatures into accessor methods.
This makes the `recover_pubkey` method itself cleaner.
=> k256: refactor pubkey recovery from ECDSA signatures

Cargo.lock, k256/src/arithmetic.rs, p256/src/arithmetic.rs
See: https://github.com/RustCrypto/traits/pull/219
=> k256/p256: add `Arithmetic` trait impls

Cargo.lock, k256/src/arithmetic.rs, k256/src/arithmetic/scalar.rs, k256/src/mul.rs, p256/src/arithmetic.rs, p256/src/arithmetic/scalar.rs
Implements the changes from RustCrypto/traits#239
=> k256/p256: update MulBase

k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/signer.rs
The previous method was failing about 52% of the time, and was probably failing to consider some combination of low-`S` or potentially `r` overflowing the scalar field(?)
This commit a method for computing a `recoverable::Signature` from any ECDSA/secp256k1 signature using trial recovery, and uses it in the `RandomizedSigner<recoverable::Signature>` impl.
This method "brute forces" the recovery ID by trying both 0 or 1 until the correct PublicKey is recovered, and returning an error if both fail.
It seems to have at least corrected the previous signature recovery failures, although could probably be better optimized in the case of the `RandomizedSigner` impl. This is noted in a TODO comment.
=> k256: add ecdsa::recoverable::Signature::from_trial_recovery

k256/src/ecdsa/signer.rs
Adds `debug_assertions` to ensure that the correct public key is recovered from every signature.
=> k256: add debug assertions for ECDSA pubkey recovery

Cargo.lock, k256/src/arithmetic.rs, k256/src/arithmetic/scalar.rs, k256/src/ecdsa/signer.rs, k256/src/ecdsa/verifier.rs, k256/src/lib.rs, p256/src/arithmetic.rs, p256/src/arithmetic/scalar.rs, p256/src/ecdsa.rs, p256/src/lib.rs, p384/src/lib.rs
=> Rename ScalarBytes to ElementBytes

.github/workflows/k256.yml, .github/workflows/p256.yml, Cargo.lock, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, p256/src/ecdsa.rs
Not all feature combos build correctly. This commit tests more of them.
=> k256/p256: test more feature combinations on no_std

Cargo.lock, k256/src/lib.rs, p256/src/lib.rs, p384/src/lib.rs
See: https://github.com/RustCrypto/traits/pull/282
=> Rename Curve::ElementSize => FieldSize

k256/src/ecdsa/recoverable.rs
Support for "trial recovery" computation of an `ecdsa::recoverable::Signature` and the `VerifyKey` that created it using a prehashed message `Digest`.
=> k256: factor out a `from_digest_trial_recovery` method

k256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs
https://github.com/RustCrypto/elliptic-curves/issues/170
=> k256/p256: link to Scalar::sqrt todo issue

Cargo.lock, k256/src/arithmetic/scalar.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, p256/src/arithmetic/scalar.rs
=> Use subtle 2.3's From<CtOption<T>> impl on Option<T>

Cargo.lock, k256/src/arithmetic/affine.rs, k256/src/arithmetic/field.rs, k256/src/arithmetic/field/field_10x26.rs, k256/src/arithmetic/field/field_5x52.rs, k256/src/arithmetic/field/field_impl.rs, k256/src/arithmetic/field/field_montgomery.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/ecdsa/sign.rs, k256/src/lib.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p256/src/lib.rs, p384/src/lib.rs
=> Rename `ElementBytes` => `FieldBytes`

Cargo.lock, k256/bench/bench.rs, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, p256/src/arithmetic/projective.rs, p256/src/arithmetic/scalar.rs, p256/src/ecdsa.rs
=> `FromFieldBytes` updates

k256/src/ecdsa.rs, k256/src/lib.rs, p256/src/ecdsa.rs, p256/src/lib.rs
Expands the rustdoc intro, and provides information about supported features.
=> k256/p256: documentation improvements

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- `SecretValue` impl when `arithmetic` feature is disabled ([#222])
[#222]: https://github.com/RustCrypto/elliptic-curves/pull/222
=> k256 v0.5.7

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/ecdsa/recoverable.rs, k256/src/lib.rs
- Bump `cfg-if` from 0.1.10 to 1.0.0 ([#220])
[#220]: https://github.com/RustCrypto/elliptic-curves/pull/220
=> k256 v0.5.9

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Expand README.md ([#233])
[#233]: https://github.com/RustCrypto/elliptic-curves/pull/233
=> k256 v0.5.10

k256/src/ecdsa.rs
Per #269 it seems this might've been a bit hard to discover, so this note hopefully makes it easier.
=> k256: add Ethereum note to `ecdsa` module rustdoc

Cargo.lock, Cargo.toml, tests/Cargo.toml
Also adds `base64ct` dependency
=> Bump `der`, `elliptic-curve`, and `pkcs8` dependencies

bp256/src/r1/ecdsa.rs, bp256/src/t1/ecdsa.rs, bp384/src/r1/ecdsa.rs, bp384/src/t1/ecdsa.rs, k256/src/ecdsa.rs, p256/src/ecdsa.rs, p384/src/ecdsa.rs
Corresponding change for https://github.com/RustCrypto/signatures/pull/226
=> Rename ECDSA `Asn1Signature` to `DerSignature`

Cargo.lock, bp256/CHANGELOG.md, bp256/Cargo.toml, bp256/src/lib.rs, bp384/CHANGELOG.md, bp384/Cargo.toml, bp384/src/lib.rs
=> bp256 + bp384 v0.0.1

Cargo.lock, k256/Cargo.toml, k256/src/lib.rs
Includes `rand_core` v0.6 upgrade
=> k256 v0.8.0-pre

Cargo.lock, p256/Cargo.toml, p256/src/lib.rs
Includes `rand_core` v0.6 upgrade
=> p256 v0.8.0-pre

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Mixed coordinate addition with the point at infinity ([#337])
[#337]: https://github.com/RustCrypto/elliptic-curves/pull/337
=> k256 v0.8.1

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- Mixed coordinate addition with the point at infinity ([#337])
[#337]: https://github.com/RustCrypto/elliptic-curves/pull/337
=> p256 v0.8.1

k256/src/ecdsa/sign.rs
=> k256: impl `Debug` for `SigningKey`

k256/Cargo.toml, k256/bench/ecdsa.rs, k256/src/ecdsa/verify.rs
Adds basic benchmarks for signing and verification
=> k256: add ECDSA benchmarks

Cargo.lock, k256/src/arithmetic/scalar/scalar_4x64.rs
Changelog: https://github.com/RustCrypto/traits/pull/674
=> Bump `elliptic-curve` dependency to v0.10.3

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Optimize ECDSA using linear combination of points ([#380])
[#380]: https://github.com/RustCrypto/elliptic-curves/pull/380
=> k256 v0.9.5

p256/src/arithmetic/scalar.rs
Replaces the previous `sub_inner` function with a `sub_order` function specialized to subtracting the scalar modulus.
=> p256: use `U256` to impl inner subtraction

p256/src/arithmetic/scalar.rs
Changes the ordering of code within the `scalar` module to place related functions closer together.
=> p256: refactor `scalar` module

Cargo.lock, p256/src/arithmetic/projective.rs
Compatibility updates for RustCrypto/traits#738
=> p256: impl `DefaultIsZeroes` for `ProjectivePoint`

k256/src/arithmetic/scalar.rs
This uses the same approach as the `p256` crate
=> k256: use `UInt` to compute `Scalar::add`; make `const fn`

k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs
This is a step towards unifying the 32-bit and 64-bit implementations
=> k256: use `U512` as the internal type for `WideScalar`

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/LICENSE-MIT, k256/src/lib.rs
- Impl `ff::Field` trait for `FieldElement` ([#498])
- Impl `ReduceNonZero<U256>` for `Scalar` ([#501])
[#498]: https://github.com/RustCrypto/elliptic-curves/pull/498
[#501]: https://github.com/RustCrypto/elliptic-curves/pull/501
=> k256 v0.10.1

p256/src/arithmetic/scalar.rs
IANA cryptographer, I basically copied this from k256.
=> Implement `ReduceNonZero<U256>` for `p256::Scalar`

p256/src/arithmetic/affine.rs, p256/src/arithmetic/projective.rs
Adds inherent constants to `AffinePoint` and `ProjectivePoint` representing the identity and generator points.
This should make it possible to write `const fn`s that produce things like precomputed basepoint tables (see #508).
Deprecates the previous inherent methods on `ProjectivePoint` for returning these constants.
=> p256: `IDENTITY` and `GENERATOR` point constants

k256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs
Reorders the impl blocks containing inherent constants/methods to the top of the module, following suit with how the `affine` and `projective` modules have been reorganized.
=> k256+p256: move `Scalar` impl blocks to top of module

p256/src/arithmetic/field.rs
```text
invert() using pow_vartime: 256 squarings, 128 multiplications
addition chain   : 255 squarings,  12 multiplications
```
```text
sqrt()   using pow_vartime: 256 squarings, 129 multiplications
addition chain   : 253 squarings,   7 multiplications
```
Ported from Zig's standard library.
=> p256 invert(), sqrt(): replace exponentiations with addition chains

p384/src/arithmetic/scalar.rs
...and adds `Scalar::from_*_slice` which returns `Result`.
`<Scalar as PrimeField>::from_repr` now calls `Scalar::from_be_bytes`.
This approach permits constant-time overflow checking for applications which would benefit from it, and is consistent with the `ScalarCore` API in the `elliptic_curve` crate:
https://docs.rs/elliptic-curve/0.12.0/elliptic_curve/struct.ScalarCore.html
=> p384: return `CtOption` from `Scalar::from_*_bytes`

p384/src/arithmetic/projective.rs
=> p384: remove `dbg!` comment

.github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
Ensures that rustdoc builds without warnings for all crates
=> Fix rustdoc build and test in CI

p256/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs
Leverages the generic serde trait impls on `ScalarCore`
=> p384: impl `serde::{Serialize, Deserialize}` for `Scalar`

p256/src/arithmetic/hash2curve.rs
Adds a bit more code in the tests, which I hope is okay.
=> Update P-256 VOPRF test vectors

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs, p256/Cargo.toml, p256/src/arithmetic/scalar.rs, p384/Cargo.toml, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
=> Bump `elliptic-curve` to v0.12.2

p384/src/ecdh.rs
=> p384: re-export low-level `diffie_hellman` function

k256/src/ecdsa/recoverable.rs
Adds a test vector for usage of HMAC-DRBG-SHA-256 for RFC6979 when producing Ethereum-style recoverable ECDSA signatures, using test vectors adapted from this discussion:
https://github.com/RustCrypto/elliptic-curves/pull/552#issuecomment-1185890038
=> k256: add RFC6979 test vector

k256/src/arithmetic/mul.rs
Ported the changes from the initial commit bumping the precision from 272 to 384 bits:
https://github.com/bitcoin-core/secp256k1/commit/76ed922a5f09d63e0622825ca83d9301c1ef3efe
and the commit with the proof for the decompostion bounds:
https://github.com/bitcoin-core/secp256k1/commit/acab934d24ff26289ab9930587c3fc51c30c6a2f
=> k256: bump the precision of precomputed division for the scalar decomposition

k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs
Impls these traits for ECDSA `SigningKey` and `VerifyingKey`.
=> k256: impl `PrehashSigner` and `PrehashVerifier` traits

k256/src/ecdsa/sign.rs
This trait provides a common API for obtaining the `VerifyingKey` for a given signer type.
=> k256: impl `Keypair` for `SigningKey`

k256/src/ecdsa/recoverable.rs
Add a method which can compute an `ecdsa::recoverable::Signature` from a non-recoverable `ecdsa::Signature` using a trial recovery method: testing various recovery IDs until one successfully recovers the public key correctly.
This is primarily useful with external signers that may not natively support computing recoverable signatures like the software implementation does.
=> k256: add `ecdsa::recoverable::Signature::from_digest_bytes_trial_recovery`

Cargo.lock, p256/Cargo.toml, p384/Cargo.toml, primeorder/CHANGELOG.md, primeorder/Cargo.toml
=> primeorder v0.0.1

primeorder/src/projective.rs
=> primeorder: impl `From/ToEncodedPoint` for `ProjectivePoint`

p224/src/arithmetic/field.rs
=> p224: fix `FieldElement::CAPACITY` constant

k256/src/schnorr/signing.rs, k256/src/schnorr/verifying.rs
=> K256 schnorr serde

p224/CHANGELOG.md, p224/Cargo.toml
=> p224 v0.13.0

Cargo.lock, p521/CHANGELOG.md, p521/Cargo.toml
=> p521 v0.13.0

k256/CHANGELOG.md
Fixed small typo in the k256 changelog.
=> Fix typo in date

k256/src/arithmetic/field.rs, k256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs, p521/src/arithmetic/field.rs, p521/src/arithmetic/scalar.rs, primeorder/src/field.rs
=> Correct product definition for empty iterators

.github/workflows/sm2.yml, Cargo.lock, Cargo.toml, sm2/CHANGELOG.md, sm2/Cargo.toml, sm2/LICENSE-APACHE, sm2/LICENSE-MIT, sm2/README.md, sm2/src/lib.rs
Initial crate boilerplate with a `Sm2` type, `Curve` impl, and type aliases for the generic types which can work with that.
=> sm2: initial crate

Cargo.lock, sm2/CHANGELOG.md, sm2/Cargo.toml
=> sm2 v0.13.0

p192/Cargo.toml, p224/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, sm2/Cargo.toml
This option was previously not set in Cargo.toml
=> p192/p224/p384/p521/sm2: add `all-features = true` on docsrs

.github/workflows/bp256.yml, .github/workflows/bp384.yml, README.md, bp256/Cargo.toml, bp256/src/lib.rs, bp256/src/r1.rs, bp256/src/t1.rs, bp384/Cargo.toml, bp384/src/lib.rs, bp384/src/r1.rs, bp384/src/t1.rs
Promotes the `wip-arithmetic-do-not-use` feature to an `arithmetic` feature
=> bp256/bp384: `arithmetic` feature

Cargo.lock, README.md, bp256/CHANGELOG.md, bp256/Cargo.toml, bp256/src/r1/arithmetic.rs, bp256/src/t1/arithmetic.rs
- WIP `arithmetic` implementation ([#870], [#871], [#874], [#876])
[#870]: https://github.com/RustCrypto/elliptic-curves/pull/870
[#871]: https://github.com/RustCrypto/elliptic-curves/pull/871
[#874]: https://github.com/RustCrypto/elliptic-curves/pull/874
[#876]: https://github.com/RustCrypto/elliptic-curves/pull/876
=> bp256 v0.6.1

bp384/CHANGELOG.md, bp384/Cargo.toml, bp384/src/r1/arithmetic.rs, bp384/src/t1/arithmetic.rs
- WIP `arithmetic` implementation ([#869], [#872], [#873], [#875], [#877])
[#869]: https://github.com/RustCrypto/elliptic-curves/pull/869
[#872]: https://github.com/RustCrypto/elliptic-curves/pull/872
[#873]: https://github.com/RustCrypto/elliptic-curves/pull/873
[#875]: https://github.com/RustCrypto/elliptic-curves/pull/875
[#877]: https://github.com/RustCrypto/elliptic-curves/pull/877
=> bp384 v0.6.1

p224/src/arithmetic/scalar.rs
Part of https://github.com/RustCrypto/elliptic-curves/issues/847
I implemented p224 sqrt.
I would appreciate it if you could confirm.
Thank you!
=> p224 Scalar::sqrt

bp384/src/arithmetic/scalar.rs
Close https://github.com/RustCrypto/elliptic-curves/issues/847
I implemented bp384 sqrt.
I would appreciate it if you could confirm.
Thank you!
=> bp384: impl `Scalar::sqrt`

Cargo.lock, p521/Cargo.toml, p521/src/arithmetic/scalar.rs, p521/src/lib.rs
Adds `serde::{Serialize, Deserialize}` impls for `AffinePoint` and `Scalar`.
=> p521: `serde` feature

p521/src/arithmetic/field.rs
Puts it with the other trait impls
=> p521: move `Debug` impl for `FieldElement`

Cargo.lock, sm2/CHANGELOG.md, sm2/Cargo.toml
- Impl `Randomized*Signer` for `sm2::dsa::SigningKey` ([#993])
[#993]: https://github.com/RustCrypto/elliptic-curves/pull/993
=> sm2 v0.13.3

.github/workflows/p256.yml, p256/src/arithmetic/hash2curve.rs
=> p256: fix tests with `hash2curve` feature

Cargo.lock, bign256/CHANGELOG.md, bign256/Cargo.toml
- Digital signature algorithm ([#935])
[#935]: https://github.com/RustCrypto/elliptic-curves/pull/935
=> bign256 v0.13.1

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/LICENSE-MIT
- More inlines for better efficiency ([#999])
[#999]: https://github.com/RustCrypto/elliptic-curves/pull/999
=> k256 v0.13.3

Cargo.lock, k256/Cargo.toml
This reverts commit 53fcfc0515edcb40d886a9e7651750e80d8874f8.
=> Revert "build(deps): bump once_cell from 1.19.0 to 1.20.0 (#1076)"

p384/CHANGELOG.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "compactabtility" to "compactability".
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

sm2/CHANGELOG.md, sm2/src/dsa.rs, sm2/src/dsa/signing.rs, sm2/src/dsa/verifying.rs, sm2/tests/pkcs8.rs
=> sm2: bring signature and key encoding support

p256/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/scalar.rs
This implements `ReduceNonZero` for `p384::Scalar` and `p521::Scalar`.
Previously implemented for P-256 in #507.
=> Implement `ReduceNonZero` for `p384::Scalar` and `p521::Scalar`

k256/Cargo.toml
=> k256: have `serde` feature activate `pkcs8`

bign256/src/arithmetic/field.rs, bign256/src/arithmetic/scalar.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs, primefield/src/lib.rs
Uses a common `Debug` impl for all field element types
=> primefield: have `field_element_type!` impl `Debug`

bign256/src/arithmetic/field.rs, bign256/src/arithmetic/scalar.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs, primefield/src/lib.rs
The trait is sourced from `crypto-bigint`
=> primefield: `field_element_type!` now impls `Invert`

sm2/tests/dsa_extended.rs
Add comprehensive test suite for SM2 DSA implementation.
Added new test file `dsa_extended.rs` with the following test cases:
- Test vectors for different message lengths (empty, 1 byte, 32 bytes, 1KB)
- Signature tampering detection tests
- Special message cases (all zeros, all ones, control characters)
- Property-based tests for signature consistency
All tests pass successfully. The new tests provide better coverage for:
- Edge cases
- Security properties
- Signature consistency
- Error handling
N/A
=> sm2: add comprehensive DSA tests

Cargo.lock, Cargo.toml, bp256/src/r1/ecdsa.rs, bp256/src/t1/ecdsa.rs, bp384/src/r1/ecdsa.rs, bp384/src/t1/ecdsa.rs, k256/src/ecdsa.rs, k256/src/schnorr/signing.rs, k256/src/schnorr/verifying.rs, p224/src/ecdsa.rs, p256/src/ecdsa.rs, p384/src/ecdsa.rs, p521/src/ecdsa.rs
Depends:
- https://github.com/RustCrypto/signatures/pull/955
=> Revert signature 3 changes

Cargo.lock, Cargo.toml, bign256/src/arithmetic/scalar.rs, bp256/src/arithmetic/scalar.rs, bp384/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/field/field32.rs, p256/src/arithmetic/field/field64.rs, p256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar/scalar32.rs, p256/src/arithmetic/scalar/scalar64.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/scalar.rs, primefield/Cargo.toml, sm2/src/arithmetic/scalar.rs
depends:
- https://github.com/RustCrypto/traits/pull/1845
=> chore(deps): bump `crypto-bigint` to `0.7.0-pre.3`

Cargo.lock, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml
Cuts new prereleases of: `k256`, `p256`, `p384`, `p521`
=> Release `pre.3` prereleases

p256/src/ecdsa.rs
=> Add re-export p256::ecdsa::RecoveryId

Cargo.lock, Cargo.toml, bign256/Cargo.toml, bign256/src/ecdsa/signing.rs, bign256/src/ecdsa/verifying.rs, k256/Cargo.toml, k256/src/schnorr/signing.rs, k256/src/schnorr/verifying.rs, sm2/Cargo.toml, sm2/src/dsa/signing.rs, sm2/src/dsa/verifying.rs
Implementation of `MultipartSigner` and `MultipartVerifier` added in https://github.com/RustCrypto/traits/pull/1880.
=> Implement `MultipartSigner/Verifier`

.github/workflows/ed448-goldilocks.yml, ed448-goldilocks/src/sign/verifying_key.rs
=> ed448-goldilocks: use `cargo hack test`

.github/workflows/workspace.yml, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs
Also includes some small fixes for redundant lints
=> CI: bump `clippy` to v1.89

k256/src/arithmetic/projective.rs, primeorder/src/projective.rs
- Creates a logical comment-delimited section of the source for `group` trait impls
- Alphabetizes trait impls by name
- Adds some explanatory comments
=> k256+primeorder: organize `group` trait impls

Cargo.lock, Cargo.toml, bign256/src/ecdsa.rs, bign256/src/lib.rs, bign256/src/secret_key.rs, bp256/src/r1.rs, bp256/src/r1/arithmetic.rs, bp256/src/t1.rs, bp256/src/t1/arithmetic.rs, bp384/src/r1.rs, bp384/src/r1/arithmetic.rs, bp384/src/t1.rs, bp384/src/t1/arithmetic.rs, k256/src/arithmetic/scalar.rs, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/field.rs, p521/src/arithmetic/scalar.rs, sm2/src/arithmetic/scalar.rs, sm2/src/dsa.rs
Companion PR to RustCrypto/traits#2008
=> elliptic-curve: rename `ScalarPrimitive` => `ScalarValue`

ed448-goldilocks/src/sign/signing_key.rs, ed448-goldilocks/src/sign/verifying_key.rs
As discussed in https://github.com/RustCrypto/traits/pull/2004#issuecomment-3288626334, but with no real impact in this case.
=> Replace `Digest + Update` with underlying traits
