elliptic-curve-crate/CHANGES.md, elliptic-curve-crate/Cargo.toml, elliptic-curve-crate/src/lib.rs, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml
- `Scalar` struct type ([#5])
- Repository moved to <https://github.com/RustCrypto/elliptic-curves>
- Curve definitions/arithmetic extracted out into per-curve crates ([#5])
[#5]: https://github.com/RustCrypto/elliptic-curves/pull/5
=> elliptic-curve v0.3.0

k256/README.md
It was previously "seck256k1" instead of secp256k1.
=> k256: fix typo in crate name

k256/CHANGES.md, k256/Cargo.toml
- README.md: fix typo in crate name ([#16])
[#16]: https://github.com/RustCrypto/elliptic-curve/pull/16
=> k256 v0.1.1

k256/Cargo.toml
- Removes "nist" keyword (copypasta from the `p256`/`p384`/`p521` crates)
- Adds `cryptography::cryptocurrencies` category
- Adds `bitcoin` and `ethereum` keywords
=> k256: update categories and keywords

README.md, k256/Cargo.toml, k256/src/arithmetic.rs, k256/src/lib.rs, p256/Cargo.toml, p256/src/arithmetic.rs, p256/src/lib.rs
- Make `Scalar` types a `pub` export
- Adds docs.rs config for `arithmetic` feature gating
- Remove obsolete comments about arithmetic status
- Remove broken deps.rs badge
- Update MSRV to 1.37
=> p256/k256: prep for 2.0 release

p256/CHANGES.md, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml
These crats don't actually link directly to the corresponding version of their own documentation, so these comments are irrelevant.
=> Cargo.toml(s): remove copypasta comment

p256/src/arithmetic/scalar.rs
This is just a small ergonomics issue I ran into when implementing [hpke](https://github.com/rozbb/rust-hpke)
cc @str4d
=> Implemented SecretKey -> Scalar conversion in p256

Cargo.lock, elliptic-curve-crate/Cargo.toml
Matches the other crates in https://github.com/RustCrypto/traits
=> elliptic-curve-crate: bump generic-array dep to v0.14

Cargo.lock, elliptic-curve-crate/CHANGES.md, elliptic-curve-crate/Cargo.toml, elliptic-curve-crate/src/lib.rs, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml
- Bump `generic-array` dependency from v0.12 to v0.14 ([#38])
[#38]: https://github.com/RustCrypto/elliptic-curves/pull/38
=> elliptic-curve v0.4.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- Bump `elliptic-curve` crate dependency to v0.4 ([#39])
[#39]: https://github.com/RustCrypto/elliptic-curves/pull/39
=> k256 v0.3.0

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml
- Bump `elliptic-curve` crate dependency to v0.4 ([#39])
[#39]: https://github.com/RustCrypto/elliptic-curves/pull/39
=> p256 v0.3.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml
- Bump `elliptic-curve` crate dependency to v0.4 ([#39])
[#39]: https://github.com/RustCrypto/elliptic-curves/pull/39
=> p384 v0.2.0

README.md
Unfortunately there don't seem to be good pure-curve resources (even with anchors!) for the NIST curves as they're largely documented in standards documents published as PDFs.
This links to http://oid-info.com (which sadly doesn't support https://) which contains some information about each curve, including the curve's OIDs and where it's standardized (e.g. ANSI, IEEE, SECG, RFC).
Lacking other options, it might make sense to eventually make some pages on https://github.com/RustCrypto/elliptic-curves/wiki which contain the same information, but served over https://
=> README.md: add links to individual curves

k256/src/arithmetic.rs, k256/src/lib.rs, p256/src/arithmetic.rs, p256/src/lib.rs, p384/src/lib.rs
Adds `CompressedCurvePoint` and `UncompressedCurvePoint` type aliases to each crate, which helps simplify the type signatures.
=> k256/p256/p384: add curve point type aliases

elliptic-curve-crate/src/weierstrass.rs, elliptic-curve-crate/src/weierstrass/point.rs, elliptic-curve-crate/src/weierstrass/public_key.rs, k256/src/arithmetic.rs, k256/src/lib.rs, p256/src/arithmetic.rs, p256/src/lib.rs, p384/src/lib.rs
Rationale:
- `CompressedCurvePoint` and `UncompressedCurvePoint` are annoyingly long to type
- It's an elliptic curve library: we already know it's a curve point by definition
- More consistency with types like `AffinePoint` and `ProjectivePoint`
- Matches the `CompressedPointSize` and `UncompressedPointSize` names
=> Drop `*Curve*` from CompressedPoint/UncompressedPoint

elliptic-curve-crate/src/weierstrass/point.rs, k256/src/arithmetic.rs, p256/src/arithmetic.rs
Adds a `from_affine_coords` method to `CompressedPoint` and `UncompressedPoint` which accepts a `ScalarBytes` for the x and y-coordinates.
This is then used in the `k256` and `p256` crates to consolidate the duplicated SEC-1 serialization logic.
=> Factor SEC-1 serialization into `elliptic-curve` crate

Cargo.lock, elliptic-curve-crate/Cargo.toml, elliptic-curve-crate/src/error.rs, elliptic-curve-crate/src/lib.rs, elliptic-curve-crate/src/secret_key.rs, elliptic-curve-crate/src/weierstrass.rs, elliptic-curve-crate/src/weierstrass/curve.rs, k256/Cargo.toml, k256/src/arithmetic.rs, p256/Cargo.toml, p256/src/arithmetic.rs
Adds a `SecretKey` generation trait for Weierstrass curves supporting curve-specific logic.
The trait is implemented for the `k256` and `p256` crates using a trial generation method ("generate-and-pray") which attempts to decode a randomly generated bytestring as a `Scalar` and loops until it succeeds.
This approach is suboptimal as it's non-constant-time, however this should not pose a practical security concern as the timing sidechannel shouldn't reveal any useful information (so long as RNG outputs do not reveal information about subsequent or prior RNG outputs, which is a property required for any secure CSPRNG).
It would be good to replace this with a truly constant-time approach (e.g. using a modular reduction to ensure the scalar is in range, rather than brute force)
=> Add `weierstrass::GenerateSecretKey` trait

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic.rs, k256/src/arithmetic/field.rs, p256/Cargo.toml, p256/src/arithmetic.rs, p256/src/arithmetic/field.rs
...to implement `FieldElement::generate()`. The previous implementation was based on a legacy (and previously removed) `getrandom` feature.
The `rand_core` crate has the advantage of being able to work (ergonomically) in embedded environments.
=> k256/p256: remove `getrandom`; use `rand` feature

k256/src/arithmetic/scalar.rs
Adds an impl of `subtle::ConstantTimeEq` on `Scalar`.
Uses that impl to define `Scalar::is_zero`, and then uses `is_zero` within the `Neg` impl.
=> k256: impl ConstantTimeEq for Scalar; is_zero()

.github/workflows/workspace.yml
Presently this action fails on any PR from a fork.
Codecov fixed things upstream to where public repos no longer require a token when uploading from GitHub actions:
https://github.com/codecov/codecov-action/issues/29
Upgrading should fix builds from forks
=> .github: bump codecov-action to v1.0.10; remove token

k256/Cargo.toml, k256/bench/bench.rs, k256/src/arithmetic.rs, k256/src/lib.rs
- adds benchmarks for `Scalar` and `FieldElement` operations
- adds a benchmark for point-scalar multiplication
- exposes `FieldElement` when `arithmetic` feature is on
=> Add criterion-based benchmarks for k256

k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs
This PR is an alternative to #76 
This method is intended for use when implementing ECDSA, namely for computing a `Scalar` from the hash of the message:
https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Signature_generation_algorithm
1. Calculate 𝑒 = HASH(𝑚)
2. Let 𝐳 be the 𝐋𝑛 leftmost bits of 𝑒, where 𝐋𝑛 is the bit length of the group order 𝑛
=> k256: add Scalar::from_digest

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic.rs, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/lib.rs
Conditionally implements public key recovery for `recoverable::Signature` when the `arithmetic` and `sha256` Cargo features are enabled.
Recovery is only implemented for "recovery IDs" 0 and 1, as these are the only ones that occur in practice.
=> k256: Add recoverable::Signature::recover_pubkey

k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs
If the unreduced result ended up in range [modulus, 2^256), it was not reduced.
=> Fix a bug in scalar addition

Cargo.lock, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/ecdsa.rs
Implements the low-level ECDSA signing and verification interfaces.
=> k256: impl ecdsa::hazmat::{SignPrimitive, VerifyPrimitive}

k256/Cargo.toml, k256/src/arithmetic.rs, k256/src/arithmetic/field.rs, k256/src/arithmetic/field/field_10x26.rs, k256/src/arithmetic/field/field_5x52.rs, k256/src/arithmetic/field/field_impl.rs, k256/src/arithmetic/field/field_montgomery.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/lib.rs, k256/src/mul.rs
May fix issue #24, or at least come close to fixing it. On my machine, the multiplication speed without endomorphism is 104us, and with endomorphism 75us.
Current version uses a simple windowed multiplication. `libsecp256k1` has the following improvements on top of that:
1. a use of the endomorphism
This is implemented, and enabled by `endomorphism-mul`. I have some doubts about the validity of the approximation used in `libsecp256k1`, see my comment in `mul.rs` ("@fjarri"). 
2. a more advanced windowing algorithm, requiring precomputation of only odd multiples of the point
I checked it out, and it performs the same as the one from Ristretto, with the latter being considerably simpler. So I used the Ristretto one. (It does have a hardcoded window size, but generalizing to other window …
=> Improved k256 point-scalar multiplication

p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs
This PR cherry picks @nickray's original #56 onto the latest code.
I also removed the `expose-arithmetic` feature/gating as I think it should no longer be necessary.
With this I think it should be possible to implement `ecdsa::hazmat::SignPrimitive` ala the implementation in #79 for secp256k1.
=> p256: Implement scalar arithmetic via Barrett reduction

.github/workflows/workspace.yml, Cargo.lock, k256/Cargo.toml, k256/src/arithmetic.rs, k256/src/ecdsa.rs
Converts ECDSA tests to use the `new_signing_test!` and `new_verification_test!` macros added to the new `dev` feature of the `ecdsa` crate in RustCrypto/signatures#103.
The macros use a few new APIs which were also added in this PR, namely `AffinePoint::{from_compressed_point, from_uncompressed_point}` which provide a more direct conversion path from SEC-1 encodings to `AffinePoint` which skip the `PublicKey` interface (which is more of a high-level, user-facing API).
=> k256: use `ecdsa/dev` test macros + API support

.github/workflows/workspace.yml, k256/src/arithmetic.rs, k256/src/ecdsa/recoverable.rs
Uses a `compress: bool` argument to enable point compression.
=> k256: unify `AffinePoint::to_pubkey` method

Cargo.lock, k256/src/arithmetic.rs, k256/src/ecdsa.rs, p256/Cargo.toml, p256/src/arithmetic.rs, p256/src/arithmetic/scalar.rs, p256/src/ecdsa.rs
This PR combines parts of #57 and #79 to implement the low-level ECDSA signing interface for P-256.
=> ecdsa::hazmat::{SignPrimitive, VerifyPrimitive}

Cargo.lock, k256/src/arithmetic.rs, k256/src/arithmetic/scalar.rs, p256/src/arithmetic.rs, p256/src/arithmetic/scalar.rs
Impls the new trait for random generation added in RustCrypto/traits#220.
This can potentially be used to completely replace the `GenerateSecretKey` trait, since that can now be made a conditionally impl'd inherent method on `SecretKey` with where bounds on `Scalar: Generate`.
=> k256/p256: impl Generate for Scalar types

Cargo.lock, k256/src/arithmetic.rs, k256/src/lib.rs, p256/src/arithmetic.rs, p256/src/lib.rs, p384/src/lib.rs
Updates usages of the elliptic-curve crate API to incorporate the changes from RustCrypto/traits#223.
=> Implement RustCrypto/traits#223 updates

Cargo.lock, k256/src/arithmetic.rs, p256/src/arithmetic.rs
This trait was removed in https://github.com/RustCrypto/traits/pull/224
The `Generate` trait is now conditionally defined for `SecretKey` when an `Arithmetic` impl is available and its `Scalar` type impls `Generate`.
=> k256/p256: remove GenerateSecretKey impls; use Generate

Cargo.lock, k256/src/arithmetic.rs, p256/src/arithmetic.rs
Implements the changes from RustCrypto/traits#227
=> k256/p256: FixedBaseScalarMul simplification

Cargo.lock, k256/src/ecdsa.rs, p256/src/ecdsa.rs
Incorporates changes from RustCrypto/signatures#106
The `ecdsa::hazmat::SignPrimitive` now bounds the elliptic curve generic parameter on `Arithmetic`, from which it sources an associated `Scalar` type.
=> k256/p256: use Arithmetic trait-based ECDSA SignPrimitive

k256/src/arithmetic/field/field_10x26.rs
=> Fix an overly strict debug check in FieldElement10x26::normalize_weak()

p256/Cargo.toml
Set default-features = false for sha2 in Cargo.toml such that the crate builds in no_std environment.
=> Deactivate default features of sha2 in Cargo.toml

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/ecdsa.rs, p256/Cargo.toml, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar/blinding.rs, p256/src/ecdsa.rs, p256/src/lib.rs
Updates both crates with the `SignPrimitive` changes from RustCrypto/signatures#107.
These changes removed the `masking_scalar` argument from the trait, and replaced it with trait bounds that make it possible to substitute a blinded scalar.
In the `p256` crate (which is the only one that presently implements a variable-time inversion) the `masking_scalar` is replaced with a `BlindedScalar` type that implements the previous blinded inversion.
The implementation it uses (including `Scalar::invert_vartime`) could potentially be made generic and extracted into the `elliptic-curve` crate, allowing it to be used with any curve which implements the arithmetic primitives used in the blinded inversion implementation.
However, for now, this PR leaves it in `p256`, and therefore at least has feature …
=> k256/p256: use new `SignPrimitive` API; add `BlindedScalar`

Cargo.lock, k256/src/arithmetic.rs, k256/src/arithmetic/scalar.rs, p256/src/arithmetic.rs, p256/src/arithmetic/scalar.rs
...and remove the now legacy `FixedBaseScalarMul` trait.
This commit impls the changes from RustCrypto/traits#229 and RustCrypto/traits#230:
- Adds a `FromSecretKey` impl on `Scalar`
- Adds a `FromPublicKey` impl on `AffinePoint`
- Adds `MulBase` impl on `Scalar`
=> k256/p256: impl FromPublicKey/FromSecretKey and ops::MulBase

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/lib.rs, k256/src/test_vectors/ecdsa.rs, p256/Cargo.toml, p256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar/blinding.rs, p256/src/ecdsa.rs, p256/src/lib.rs, p256/src/test_vectors/ecdsa.rs
Adds a type alias for `ecdsa::signer::Signer`, which provides a high-level ECDSA signing interface.
=> k256/p256: wire up ecdsa::Signer

k256/src/ecdsa.rs
Adds an initial description of the crate's ECDSA-related cargo features (`ecdsa-core` and `ecdsa`) along with a basic signing/verification usage example.
=> k256: ECDSA usage with initial end-to-end doctest

k256/src/ecdsa.rs
Per BIP0062: https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki
=> k256: ensure ECDSA signatures are low-S normalized

Cargo.lock, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/signer.rs
Replaces the previous precomputed recovery ID with a stored PublicKey.
This is generally useful and makes it possible to retrieve a PublicKey from a Signer instance.
=> k256: have ecdsa::Signer cache public key

Cargo.lock, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/signer.rs
Impls the `RecoverableSignPrimitive` trait introduced in RustCrypto/signatures#111 which returns the necessary information
(even-or-odd) about the ECDSA signature's `R` y-coordinate to be able to compute the recovery ID without using brute force trial recovery.
This implementation leaks some details the existing `ecdsa` crate APIs are trying to abstract over, but hopefully can feed into the requirements for what those APIs should actually look like.
=> k256: impl ecdsa::hazmat::RecoverableSignPrimitive

Cargo.lock, k256/Cargo.toml, k256/src/lib.rs, p256/Cargo.toml, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
Uses types from the `const-oid` crate to define OIDs (optionally, gated on the `oid` cargo feature)
=> Use `const_oid` crate

Cargo.lock, k256/src/arithmetic.rs, k256/src/arithmetic/field.rs, k256/src/arithmetic/field/field_10x26.rs, k256/src/arithmetic/field/field_5x52.rs, k256/src/arithmetic/field/field_impl.rs, k256/src/arithmetic/field/field_montgomery.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/signer.rs, k256/src/ecdsa/verifier.rs, p256/src/arithmetic.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p256/src/ecdsa.rs
Impls the new `FromBytes` traits introduced in RustCrypto/traits#247, and changes `to_bytes()` to return `ElementBytes`.
=> k256/p256: use new `elliptic_curve::encoding` module

k256/src/ecdsa/signer.rs
To catch bugs like this we need to run tests with all features on but *without* `field-montgomery`, which skips normalization checks.
Another variant would be to auto-normalize in `is_odd()`. I'm kind of on the fence about it. Explicit normalization seems to be the general convention in `k256` now (except for `to_bytes()`), so I went with it. Otherwise one could as well auto-normalize in `is_zero()`.
=> k256: normalize() before is_odd()

Cargo.lock, k256/src/ecdsa/normalize.rs, k256/src/ecdsa/signer.rs
Implements the changes made in RustCrypto/signatures#120.
These changes have the `k256` always compute a `recoverable::Signature` via `RecoverableSignPrimitive` and use the blanket impl of `SignPrimitive` for `RecoverableSignPrimitive` to convert it to a regular `k256::ecdsa::Signature` in `ecdsa::signer::Signer<Secp256k1>`.
Ideally the `k256::ecdsa::Signer` newtype could go away and this could all be handled by `ecdsa::signer::Signer` via blanket and conditional impls, however I'm not sure how to prevent the impls of `RandomizedSigner` from overlapping in a generic context.
=> k256: impl new RecoverableSignPrimitive API

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic.rs, k256/src/arithmetic/field.rs, k256/src/arithmetic/field/field_10x26.rs, k256/src/arithmetic/field/field_5x52.rs, k256/src/arithmetic/field/field_impl.rs, k256/src/arithmetic/field/field_montgomery.rs, k256/src/ecdsa.rs, p256/Cargo.toml, p256/src/arithmetic.rs, p256/src/arithmetic/field.rs, p256/src/ecdsa.rs
This is used by the generic `ecdh` implementation to zero out the transient shared secret value after it's been serialized to bytes.
=> k256/p256: impl Zeroize for AffinePoint and FieldElement types

k256/Cargo.toml, k256/src/ecdh.rs, p256/Cargo.toml, p256/src/ecdh.rs
Provides a usage example for Elliptic Curve Diffie-Hellman.
This also tests that the generic implementation is wired up correctly in both crates.
=> k256/p256: ECDH rustdoc

Cargo.lock, Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml
Release notes:
- `elliptic-curve` v0.5.0: https://github.com/RustCrypto/traits/pull/254
- `ecdsa` v0.7.0: https://github.com/RustCrypto/signatures/pull/125
=> Bump `elliptic-curve` to v0.5; `ecdsa` to v0.7

k256/README.md, k256/src/lib.rs, p256/README.md, p256/src/lib.rs
These crates now contain full-fledged cryptographic algorithm implementations, so note that they are bleeding edge, unaudited, use-at-your-own-risk, etc.
Also add additional documentation about supported features and other notable information about elliptic curves.
=> k256/p256: add security warnings and other documentation

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- ECDSA support ([#73], [#101], [#104], [#105])
- ECDSA public key recovery support ([#110])
- OID support ([#103], [#113])
- Elliptic Curve Diffie-Hellman ([#120])
- `Zeroize` impl for `AffinePoint` and `FieldElement` types ([#124])
- Optimized field arithmetic with 32-bit and 64-bit backends ([#59], [#82])
- Bump `elliptic-curve` crate dependency to v0.5 ([#126])
[#59]: https://github.com/RustCrypto/elliptic-curves/pull/59
[#73]: https://github.com/RustCrypto/elliptic-curves/pull/73
[#82]: https://github.com/RustCrypto/elliptic-curves/pull/82
[#101]: https://github.com/RustCrypto/elliptic-curves/pull/101
[#104]: https://github.com/RustCrypto/elliptic-curves/pull/104
[#103]: https://github.com/RustCrypto/elliptic-curves/pull/103
[#105]: …
=> k256 v0.4.0

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- ECDSA support ([#73], [#101], [#104], [#105])
- ECDSA public key recovery support ([#110])
- OID support ([#103], [#113])
- Elliptic Curve Diffie-Hellman ([#120])
- Bump `elliptic-curve` crate dependency to v0.5 ([#126])
[#73]: https://github.com/RustCrypto/elliptic-curves/pull/73
[#101]: https://github.com/RustCrypto/elliptic-curves/pull/101
[#104]: https://github.com/RustCrypto/elliptic-curves/pull/104
[#103]: https://github.com/RustCrypto/elliptic-curves/pull/103
[#105]: https://github.com/RustCrypto/elliptic-curves/pull/105
[#110]: https://github.com/RustCrypto/elliptic-curves/pull/110
[#113]: https://github.com/RustCrypto/elliptic-curves/pull/113
[#120]: https://github.com/RustCrypto/elliptic-curves/pull/120
[#126]: https://github.com/RustCrypto/elliptic-curves/pull/126
=> p256 v0.4.0

Cargo.lock, k256/CHANGELOG.md, p256/CHANGELOG.md, p384/CHANGELOG.md, p384/Cargo.toml, p384/src/lib.rs
- ECDSA types ([#73])
- OID support ([#103], [#113])
- Bump `elliptic-curve` crate dependency to v0.5 ([#126])
[#73]: https://github.com/RustCrypto/elliptic-curves/pull/73
[#103]: https://github.com/RustCrypto/elliptic-curves/pull/103
[#113]: https://github.com/RustCrypto/elliptic-curves/pull/113
[#126]: https://github.com/RustCrypto/elliptic-curves/pull/126
=> p384 v0.3.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- secp256k1 rustdoc link ([#131])
[#131]: https://github.com/RustCrypto/elliptic-curves/pull/131
=> k256 v0.4.1

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Builds with either `ecdsa-core` or `sha256` in isolation ([#133])
[#133]: https://github.com/RustCrypto/elliptic-curves/pull/133
=> k256 v0.4.2

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- Builds with either `ecdsa-core` or `sha256` in isolation ([#133])
[#133]: https://github.com/RustCrypto/elliptic-curves/pull/133
=> p256 v0.4.1

Cargo.lock, Cargo.toml, k256/src/arithmetic.rs, k256/src/arithmetic/field.rs, k256/src/arithmetic/field/field_10x26.rs, k256/src/arithmetic/field/field_5x52.rs, k256/src/arithmetic/field/field_montgomery.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/ecdh.rs, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/signer.rs, k256/src/ecdsa/verifier.rs, k256/src/lib.rs, p256/src/arithmetic.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p256/src/ecdh.rs, p256/src/ecdsa.rs, p256/src/lib.rs, p384/src/lib.rs
Replaces the previous `PublicKey` type with `sec1::EncodedPoint`, as introduced in RustCrypto/traits#264.
This clears the way for a higher-level PublicKey type.
=> Implement `EncodedPoint` changes

Cargo.lock, k256/Cargo.toml, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/signer.rs
Ethereum-style signatures (`k256::ecdsa::recoverable::Signature`) use Keccak256.
This commit adds a `keccak256` feature which can be used to compute these signatures using Keccak256 automatically.
=> k256: add `keccak256` feature

k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/signer.rs
...when the `ecdsa` feature of the crate is enabled.
This provides infallible access to the ECDSA `r()` and `s()` scalars.
=> k256: eagerly verify ECDSA scalars are in range

Cargo.lock, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/verifier.rs
Simplifies checks that `r` and `s` are non-zero by using the `NonZeroScalar` type.
=> k256: use NonZeroScalar for ECDSA signature components

Cargo.lock, p256/src/ecdsa.rs
Adds a test vector to ensure RFC6979 is implemented correctly.
Ideally some form of this can be implemented in the ECDSA crate as well, but for now this is an initial test that it's working correctly.
=> p256: add RFC6979 test vector

Cargo.lock, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs, p256/src/ecdsa.rs
These methods simplify ECDSA usages.
=> k256/p256: update code and examples to use new ECDSA key APIs

Cargo.lock, k256/src/ecdsa/sign.rs
Removes the RecoverableSignPrimitive trait per RustCrypto/signatures#146
=> k256: impl SignPrimitive

Cargo.lock, k256/src/arithmetic.rs, p256/src/arithmetic.rs
Removes fallibility around obtaining the y-coordinate
=> k256/p256: use sec1::Coordinates enum

Cargo.lock, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/verify.rs, k256/src/lib.rs
Uses the point decompression trait rather than duplicating the point decompression logic.
=> k256: use Decompress to impl ECDSA pubkey recovery

Cargo.lock, k256/src/ecdsa.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs, p256/src/ecdsa.rs, p384/src/ecdsa.rs
Corresponding `ecdsa` crate PR is RustCrypto/signatures#151.
This implements the changes which eagerly validate that ECDSA signature `r` and `s` components are in-range `NonZeroScalar` values.
This eliminates the need to do these checks as part of each ECDSA verification implementation.
=> Impl ecdsa::CheckSignatureBytes-related changes

k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs
Noticed while checking performance in PR #164 that scalar `mul()` became slower. Seems to be caused by the compiler ceasing to inline `mul_wide()` and `reduce()` starting from commit 058669385045de6eaeb6da7446d4904c08cd5dca on. 
Adding this makes `Scalar4x64::mul()` 10% faster, but has no effect on `Scalar8x32` performance on my machine; nevertheless, I inlined these functions there as well for the sake of uniformity (may be important for a 32-bit embedded device). These functions are only used once (in `mul()`), so it won't degrade compilation. 
I usually prefer not to add explicit inlining, but 10% is a pretty solid speed-up...
=> Force inline mul_wide() and reduce() to get rid of performance regression

k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/projective.rs, p256/src/ecdsa.rs
This is a corresponding change ala #165, but for the `p256` crate.
=> p256: implement `AffinePoint::identity()` and `::is_identity()`

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic/affine.rs, k256/src/arithmetic/mul.rs, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs
- Impls `ff::{Field, PrimeField}` on `Scalar`
- Impls `group::{Group, Curve}` on `ProjectivePoint`
=> k256: impl `ff` and `group` traits

Cargo.lock, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, p256/Cargo.toml, p256/src/arithmetic/projective.rs, p256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar/blinding.rs, p256/src/ecdsa.rs
Corresponding change to #164, but for the `p256` crate.
- Impls `ff::{Field, PrimeField}` on `Scalar`
- Impls `group::{Group, Curve}` on `ProjectivePoint`
=> p256: impl `ff` and `group` traits

Cargo.lock, k256/src/arithmetic/affine.rs, p256/src/arithmetic/affine.rs
Replaces previous usage of XNOR on Choice to provide `ConstantTimeEq` with a newly released upstream impl of the same behavior:
https://github.com/dalek-cryptography/subtle/pull/76
=> Use subtle 2.3's ConstantTimeEq impl on Choice

.github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/workspace.yml, Cargo.lock, Cargo.toml, README.md, k256/Cargo.toml, k256/README.md, k256/src/arithmetic.rs, k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/lib.rs, p256/Cargo.toml, p256/README.md, p256/src/arithmetic.rs, p256/src/arithmetic/projective.rs, p256/src/arithmetic/scalar.rs, p256/src/lib.rs, p384/README.md, p384/src/lib.rs, tests/Cargo.toml
Previously the `elliptic-curve` crate was depending on pre-releases of `ff` and `group` sourced via git. It was upgraded to use the final releases in RustCrypto/traits#292.
Because these crates depend on `bitvec` and its transitive dependencies, an `arithmetic` feature was added to `elliptic-curve` in RustCrypto/traits#293.
This commit upgrades the `k256` and `p256` crates to use the final releases of `ff` and `group`. This ended up actually being a relatively straightforward upgrade because we were already running off the latest versions sourced from git.
The major notable change is `PrimeField::ReprBits` and the `to_le_bits` and `char_le_bits` methods for obtaining `bitvec`-friendly types for representing field elements.
=> k256/p256: bump `ff` and `group` deps to v0.8; MSRV 1.44+

Cargo.lock, k256/src/arithmetic.rs, k256/src/arithmetic/scalar.rs, k256/src/ecdh.rs, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, p256/src/arithmetic.rs, p256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar/blinding.rs, p256/src/ecdh.rs, p256/src/ecdsa.rs
It's been replaced by methods like `Field::random` and `Group::random`.
See: RustCrypto/traits#295
=> k256/p256: remove `Generate` trait

Cargo.lock, k256/src/arithmetic.rs, k256/src/ecdsa/sign.rs, k256/src/lib.rs, p256/src/arithmetic.rs, p256/src/arithmetic/scalar.rs, p256/src/lib.rs, p384/src/lib.rs
=> Support generic inner type for elliptic_curve::SecretKey<C>

Cargo.lock, Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, tests/Cargo.toml
Release notes:
- `elliptic-curve` v0.6.0: https://github.com/RustCrypto/traits/pull/302
- `ecdsa` v0.8.0: https://github.com/RustCrypto/signatures/pull/166
=> Bump `elliptic-curve` crate to v0.6; `ecdsa` to v0.8

Cargo.lock, k256/Cargo.toml, k256/src/lib.rs, p256/Cargo.toml, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
(for `p384` it's actually v0.4.0-rc)
=> Cut v0.5.0-rc prereleases

Cargo.lock, k256/Cargo.toml
This was mistakenly released as v0.5.0-pre before.
=> k256 v0.5.0-rc

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- `ecdsa::Asn1Signature` type aliases ([#186])
- `ff` and `group` crate dependencies; MSRV 1.44+ ([#164], [#174])
- `AffinePoint::identity()` and `::is_identity()` ([#165])
- `expose-field` feature ([#161])
- `keccak256` feature ([#142])
- Bump `elliptic-curve` crate to v0.6; `ecdsa` to v0.8 ([#180])
- Refactor ProjectiveArithmetic trait ([#179])
- Support generic inner type for `elliptic_curve::SecretKey<C>` ([#177])
- Rename `ElementBytes` => `FieldBytes` ([#176])
- Factor out a `from_digest_trial_recovery` method ([#168])
- Rename `ecdsa::{Signer, Verifier}` => `::{SigningKey, VerifyKey}` ([#153])
- Rename Curve::ElementSize => FieldSize ([#150])
- Implement RFC6979 deterministic ECDSA ([#146])
- Use `NonZeroScalar` for ECDSA signature components ([#144])
- Eagerly verify ECDSA scalars …
=> k256 v0.5.0

Cargo.lock, k256/CHANGELOG.md, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- `ecdsa::Asn1Signature` type alias ([#186])
- `ff` and `group` crate dependencies; MSRV 1.44+ ([#169], [#174])
- `AffinePoint::identity()` and `::is_identity()` ([#167])
- Bump `elliptic-curve` crate to v0.6; `ecdsa` to v0.8 ([#180])
- Refactor ProjectiveArithmetic trait ([#179])
- Support generic inner type for `elliptic_curve::SecretKey<C>` ([#177])
- Rename `ElementBytes` => `FieldBytes` ([#176])
- Rename `ecdsa::{Signer, Verifier}` => `::{SigningKey, VerifyKey}` ([#153])
- Rename `Curve::ElementSize` => `FieldSize` ([#150])
- Implement RFC6979 deterministic ECDSA ([#146], [#147])
- Rename `PublicKey` to `EncodedPoint` ([#141])
- `rand` feature ([#162])
[#186]: https://github.com/RustCrypto/elliptic-curves/pull/186
[#180]: https://github.com/RustCrypto/elliptic-curves/pull/180
[#179]: …
=> p256 v0.5.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml, p384/src/lib.rs
- `ecdsa::Asn1Signature` type alias ([#186])
- Rename `ElementBytes` => `FieldBytes` ([#176])
- Rename `Curve::ElementSize` => `FieldSize` ([#150])
[#186]: https://github.com/RustCrypto/elliptic-curves/pull/186
[#176]: https://github.com/RustCrypto/elliptic-curves/pull/176
[#150]: https://github.com/RustCrypto/elliptic-curves/pull/150
=> p384 v0.4.0

k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs
They don't work otherwise.
This isn't a SemVer breaking change, because they still didn't work without the feature enabled. This change provides a slightly better error message.
=> k256: gate ecdsa::{Signer, Verifier} impls on `sha256` feature

k256/src/ecdsa/sign.rs
Gated on the `sha256` feature.
=> k256: impl `RandomizedSigner` on `SigningKey`

Cargo.lock, Cargo.toml, k256/src/arithmetic/affine.rs, p256/src/arithmetic/affine.rs
Add tests that the upstream `sec1::EncodedPoint::decompress` method works given the trait impls in the respective crates.
The generic upstream implementation was previously broken:
https://github.com/RustCrypto/traits/pull/309
The plan is to release `elliptic-curve` v0.6.1 with the above fix, then yank the broken v0.6.1 release.
=> k256/p256: add sec1::EncodedPoint::decompress test

Cargo.lock, Cargo.toml
See: https://github.com/RustCrypto/traits/pull/310
=> Bump `elliptic-curve` dependency to v0.6.1

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Documentation for `sha256` feature ([#197])
- `sec1::EncodedPoint::decompress` test ([#194])
- Impl `RandomizedSigner` on `SigningKey` ([#193])
- Gate ecdsa::{Signer, Verifier} impls on `sha256` feature ([#192])
[#197]: https://github.com/RustCrypto/elliptic-curves/pull/197
[#194]: https://github.com/RustCrypto/elliptic-curves/pull/194
[#193]: https://github.com/RustCrypto/elliptic-curves/pull/193
[#192]: https://github.com/RustCrypto/elliptic-curves/pull/192
=> k256 v0.5.1

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Corrected imports when using `ecdsa` + `keccak256` features ([#199])
[#199]: https://github.com/RustCrypto/elliptic-curves/pull/199
=> k256 v0.5.2

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Derive `Copy` on `VerifyKey` ([#202])
[#202]: https://github.com/RustCrypto/elliptic-curves/pull/202
=> k256 v0.5.3

k256/src/ecdsa/recoverable.rs
Adds a `recover_verify_key_from_digest_bytes` method which operates on a byte array that's allegedy the digest of the message used to produce a given signature.
Where `*Verifier` methods carry the risk of a signature forgery if they operate on something that's not a message digest (since this violates ROM under which ECDSA derives its security), there isn't a similar risk for public key recovery: the best an attacker can do is force recovery of a bogus key, and all recovered public keys are inherently untrusted until they can be validated against a key fingerprint. So this method doesn't have similar misuse concerns as signature verification.
=> k256: recoverable::Signature::recover_verify_key_from_digest_bytes

Cargo.lock, k256/Cargo.toml, k256/src/ecdsa/sign.rs
Impls the `RecoverableSignPrimitive` trait revived in RustCrypto/signatures#175.
This provides low-level support for computing recoverable signatures.
=> k256: impl RecoverableSignPrimtive

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Impl `RecoverableSignPrimtive` on `Scalar` ([#206])
- `recoverable::Signature::recover_verify_key_from_digest_bytes` ([#205])
[#206]: https://github.com/RustCrypto/elliptic-curves/pull/206
[#205]: https://github.com/RustCrypto/elliptic-curves/pull/205
=> k256 v0.5.4

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Impl `FromEncodedPoint` for `ProjectivePoint` ([#210])
- Impl `ToEncodedPoint` for `ecdsa::VerifyKey` ([#209])
[#210]: https://github.com/RustCrypto/elliptic-curves/pull/210
[#209]: https://github.com/RustCrypto/elliptic-curves/pull/209
=> k256 v0.5.5

k256/Cargo.toml
The reason this wasn't enabled-by-default before was due to a lingering US patent. However, as noted on #211, that patent just expired 🎉
The `bitcoin-core/secp256k1` library is also pursuing a full switch to endomorphisms: https://github.com/bitcoin-core/secp256k1/pull/826
For now this commit just switches on the feature by default, but in the future we can eventually rip out the non-endomorphism code and remove the feature entirely.
=> k256: enable endomorphisms by default

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Enable `endomorphism-mul` optimizations by default ([#213])
[#213]: https://github.com/RustCrypto/elliptic-curves/pull/213
=> k256 v0.5.6

k256/Cargo.toml, k256/src/arithmetic/mul.rs, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs
This code was previously gated under the `endomorphism-mul` feature due to lingering concerns about the "GLV" patents, namely US7110538.
According to @pwuille, a patent attorney he works with has verified that the patent is expired:
https://twitter.com/pwuille/status/1310639051393830912
Likewise non-endomorphism code is being removed from `bitcoin-core/secp256k1`:
https://github.com/bitcoin-core/secp256k1/pull/826
This commit does the same for `k256`: it removes all the non-endomorphism code and feature gating from the endomorphism code, making the `endomorphism-mul` feature a no-op.
We can remove the feature in the next SemVer-breaking release (v0.6.x).
=> k256: remove non-endomorphism code

Cargo.lock, k256/src/lib.rs, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
This allows all crates (`k256`, `p256`, `p384`) to provide a `SecretKey` type with the `zeroize` feature alone (i.e. with `arithmetic` disabled).
=> Add `SecretValue` impls when `arithmetic` is disabled

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- `SecretValue` impl when `arithmetic` feature is disabled ([#222])
[#222]: https://github.com/RustCrypto/elliptic-curves/pull/222
=> p256 v0.5.1

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml, p384/src/lib.rs
- `SecretValue` impl when `arithmetic` feature is disabled ([#222])
[#222]: https://github.com/RustCrypto/elliptic-curves/pull/222
=> p384 v0.4.1

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Regenerate `rustdoc` on https://docs.rs after nightly breakage
=> k256 v0.5.8

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- Regenerate `rustdoc` on https://docs.rs after nightly breakage
=> p256 v0.5.2

.github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/security-audit.yml, .github/workflows/workspace.yml, Cargo.lock, Cargo.toml, README.md, k256/Cargo.toml, k256/README.md, k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, k256/src/ecdh.rs, k256/src/lib.rs, p256/Cargo.toml, p256/README.md, p256/src/arithmetic/affine.rs, p256/src/ecdh.rs, p256/src/lib.rs, p384/README.md, p384/src/lib.rs, tests/Cargo.toml
Bumps all crates to use the new prereleases of these crates, as sourced from git.
=> Bump `elliptic-curve` to v0.7.0-pre; `ecdsa` to v0.9.0-pre

Cargo.lock, k256/src/ecdh.rs, k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs, p256/src/ecdh.rs, p256/src/ecdsa.rs
Use the latest versions from git, which include some minor name changes
=> Bump `elliptic-curve` and `ecdsa` dependencies

k256/src/ecdsa/sign.rs
The `SecretKey` type wraps up a lot of the concerns of secret key management, including encoding/decoding, computing public keys, and zeroization.
=> k256: make SigningKey a newtype of SecretKey

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs, p256/src/lib.rs, p384/src/lib.rs
- PKCS#8 support ([#243], [#244], [#251])
- `PublicKey` type ([#239])
- Bump `elliptic-curve` crate dependency to v0.7; MSRV 1.46+ ([#247])
- Bump `ecdsa` crate dependency to v0.9 ([#247])
- Make `SigningKey` a newtype of `elliptic_curve::SecretKey` ([#242])
[#251]: https://github.com/RustCrypto/elliptic-curves/pull/251
[#247]: https://github.com/RustCrypto/elliptic-curves/pull/247
[#244]: https://github.com/RustCrypto/elliptic-curves/pull/244
[#243]: https://github.com/RustCrypto/elliptic-curves/pull/243
[#242]: https://github.com/RustCrypto/elliptic-curves/pull/242
[#239]: https://github.com/RustCrypto/elliptic-curves/pull/239
=> k256 v0.6.0

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml
- PKCS#8 support ([#243], [#244], [#245])
- `PublicKey` type ([#239])
- Bump `elliptic-curve` crate dependency to v0.7; MSRV 1.46+ ([#247])
- Bump `ecdsa` crate dependency to v0.9 ([#247])
[#247]: https://github.com/RustCrypto/elliptic-curves/pull/247
[#245]: https://github.com/RustCrypto/elliptic-curves/pull/245
[#244]: https://github.com/RustCrypto/elliptic-curves/pull/244
[#243]: https://github.com/RustCrypto/elliptic-curves/pull/243
[#239]: https://github.com/RustCrypto/elliptic-curves/pull/239
=> p256 v0.6.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml, p384/src/lib.rs
- PKCS#8 support ([#243], [#244])
- Bump `elliptic-curve` crate dependency to v0.7; MSRV 1.46+ ([#247])
- Bump `ecdsa` crate dependency to v0.9 ([#247])
[#247]: https://github.com/RustCrypto/elliptic-curves/pull/247
[#244]: https://github.com/RustCrypto/elliptic-curves/pull/244
[#243]: https://github.com/RustCrypto/elliptic-curves/pull/243
=> p384 v0.5.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Bump `elliptic-curve` dependency to v0.8 ([#260])
- `ecdsa` to v0.10 ([#260])
[#260]: https://github.com/RustCrypto/elliptic-curves/pull/260
=> k256 v0.7.0

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- Bump `elliptic-curve` dependency to v0.8 ([#260])
- `ecdsa` to v0.10 ([#260])
[#260]: https://github.com/RustCrypto/elliptic-curves/pull/260
=> p256 v0.7.0

Cargo.lock, k256/CHANGELOG.md, p256/CHANGELOG.md, p384/CHANGELOG.md, p384/Cargo.toml, p384/src/lib.rs
- Bump `elliptic-curve` dependency to v0.8 ([#260])
- Bump `ecdsa` to v0.10 ([#260])
[#260]: https://github.com/RustCrypto/elliptic-curves/pull/260
=> p384 v0.6.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs, p384/CHANGELOG.md, p384/Cargo.toml, p384/src/lib.rs
This is a (re-)release of the following crates solely for the purpose of triggering a rebuild on docs.rs:
- `k256` v0.7.1
- `p256` v0.7.1
- `p384` v0.6.1
The previous builds failed due to a `nightly` regression in the upstream elliptic-curve` crate:
https://github.com/RustCrypto/traits/pull/412
Crates are otherwise unchanged from the previous releases.
=> Point releases to trigger docs.rs rebuild

.github/workflows/k256.yml, Cargo.lock, p256/tests/pkcs8.rs
Adds tests which exercise the generic impls of the `pkcs8` key serialization traits for the `PublicKey` and `SecretKey` types.
=> p256: private/public key serialization tests

k256/Cargo.toml, k256/src/ecdsa.rs, p256/Cargo.toml, p256/src/ecdsa.rs
Closes #271
This is needed to define a `std::error::Error` impl on errors arising from the `ecdsa` crate.
Unfortunately without weak activation this means the `ecdsa` crate gets pulled in by default, but we can circle back on that later.
=> k256/p256: have `std` activate `ecdsa-core/std`

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Have `std` feature activate `ecdsa-core/std` ([#273])
[#273]: https://github.com/RustCrypto/elliptic-curves/pull/273
=> k256 v0.7.2

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- Have `std` feature activate `ecdsa-core/std` ([#273])
[#273]: https://github.com/RustCrypto/elliptic-curves/pull/273
=> p256 v0.7.2

.github/workflows/k256.yml, Cargo.lock, Cargo.toml, k256/Cargo.toml, k256/src/ecdh.rs, k256/src/ecdsa.rs, p256/Cargo.toml, p256/src/ecdh.rs, p256/src/ecdsa.rs, p384/Cargo.toml, p384/src/ecdsa.rs, tests/Cargo.toml
...as sourced via git from the RustCrypto/traits repo.
Also bumps `ecdsa` to v0.11.0-pre (via git from RustCrypto/signatures)
=> Bump `elliptic-curve` dependency to v0.9.0-pre

Cargo.lock, k256/Cargo.toml, k256/README.md, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, k256/src/lib.rs, p256/Cargo.toml, p256/src/arithmetic/projective.rs, p256/src/arithmetic/scalar.rs, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
See: https://github.com/RustCrypto/traits/pull/487
=> Cargo.toml: bump dependencies to flattened `elliptic-curve` crate

Cargo.lock, Cargo.toml
Also bumps related dependencies in Cargo.lock
=> Bump `pkcs8` dependency to v0.4.0

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, p256/Cargo.toml, p256/src/arithmetic/scalar.rs
The `FromDigest` trait was moved to the `ecdsa` crate. See:
- https://github.com/RustCrypto/traits/pull/532
- https://github.com/RustCrypto/signatures/pull/238
=> Migrate to `FromDigest` trait from `ecdsa` crate

Cargo.lock, Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, tests/Cargo.toml
Release notes: https://github.com/RustCrypto/traits/pull/535
=> Bump `elliptic-curve` dependency to v0.9

.github/workflows/k256.yml, Cargo.lock, Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml
Uses a prerelease on crates.io rather than sourcing the dependency from `git`, which will allow us to publish prereleases of the crates in this repo for users eager to update to `rand_core` v0.6.
=> Bump `ecdsa` dependency to v0.11.0-pre.1

bp384/Cargo.toml
Typo/copypasta: `brainpoolP256t1` => `brainpoolP384t1`
=> bp384: fix Cargo.toml description

Cargo.lock
Includes the `elliptic-curve` v0.9.3 with a workaround for:
https://github.com/bitvecto-rs/bitvec/issues/105
=> Cargo.lock: bump deps

Cargo.lock, bp256/src/r1.rs, bp256/src/t1.rs, bp384/src/r1.rs, bp384/src/t1.rs, k256/src/lib.rs, p256/src/lib.rs, p384/src/lib.rs
Uses the new const-friendly OID string parser added in:
https://github.com/RustCrypto/utils/pull/312
=> Use string-based OID constants

.github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/workspace.yml, Cargo.lock, README.md, bp256/Cargo.toml, bp256/README.md, bp256/src/lib.rs, bp384/Cargo.toml, bp384/README.md, bp384/src/lib.rs, k256/Cargo.toml, k256/README.md, k256/src/lib.rs, p256/Cargo.toml, p256/README.md, p256/src/lib.rs, p384/Cargo.toml, p384/README.md, p384/src/lib.rs
This commit upgrades the following dependencies:
- `base64` v1.0
- `ecdsa` v0.11.0-pre.2
- `elliptic-curve` v0.9.5
- `pkcs8` v0.5.5
=> Bump base64ct, ecdsa, elliptic-curve, and pkcs8; MSRV 1.47+

Cargo.lock, bp256/CHANGELOG.md, bp256/Cargo.toml, bp384/CHANGELOG.md, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml
Cuts the following new pre-release versions
- `bp256` v0.0.2
- `bp384` v0.0.2
- `k256` v0.8.0-pre.1
- `p256` v0.8.0-pre.1
- `p384` v0.7.0-pre.1
=> New pre-releases

k256/Cargo.toml, k256/src/ecdsa.rs, p256/Cargo.toml
We've gotten enough questions/complaints from people who had trouble figuring out feature activations for `ecdsa` it's probably easier to just turn it on by default and let people who don't want it figure out how to shut it off if they so desire.
=> k256+p256: make `ecdsa` a default feature

k256/CHANGELOG.md, p256/CHANGELOG.md
I backported the changes from #325 to the v0.7.x releases.
This should address #326.
=> k256+p256: add CHANGELOG.md entries for v0.7.3 release

Cargo.lock, bp256/Cargo.toml, bp256/src/r1.rs, bp256/src/t1.rs, bp384/Cargo.toml, bp384/src/r1.rs, bp384/src/t1.rs, k256/Cargo.toml, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/lib.rs, p256/Cargo.toml, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
Allows checking that a scalar field element is in range generically without a curve arithmetic implementation.
=> Add `Order` constants to all curve implementations

Cargo.lock, bp256/Cargo.toml, bp256/src/r1/ecdsa.rs, bp256/src/t1/ecdsa.rs, bp384/Cargo.toml, bp384/src/r1/ecdsa.rs, bp384/src/t1/ecdsa.rs, k256/Cargo.toml, k256/src/ecdsa.rs, p256/Cargo.toml, p256/src/ecdsa.rs, p384/Cargo.toml, p384/src/ecdsa.rs
Eliminates the `CheckSignatureBytes` trait, replacing it with `elliptic_curve::Order`:
https://github.com/RustCrypto/signatures/pull/281
=> Bump `ecdsa` dependency to v0.11.0-pre.6

Cargo.lock, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml
Release notes: https://github.com/RustCrypto/signatures/pull/288
=> Bump `ecdsa` crate dependency to v0.11

Cargo.lock, bp256/CHANGELOG.md, bp256/Cargo.toml, bp256/src/lib.rs, bp384/CHANGELOG.md, bp384/Cargo.toml, bp384/src/lib.rs
- `Order` constant ([#328])
- Bump `ecdsa` crate dependency to v0.11 ([#330])
[#328]: https://github.com/RustCrypto/elliptic-curves/pull/328
[#330]: https://github.com/RustCrypto/elliptic-curves/pull/330
=> bp256 + bp384 v0.1.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- `jwk` feature ([#295])
- `Order` constant ([#328])
- Rename `ecdsa::Asn1Signature` to `::DerSignature` ([#288])
- Migrate to `FromDigest` trait from `ecdsa` crate ([#292])
- Bump `elliptic-curve` to v0.9.2 ([#296])
- Bump `pkcs8` to v0.6 ([#319])
- Bump `ecdsa` crate dependency to v0.11 ([#330])
- `DigestPrimitive` feature gating ([#324])
[#288]: https://github.com/RustCrypto/elliptic-curves/pull/288
[#292]: https://github.com/RustCrypto/elliptic-curves/pull/292
[#295]: https://github.com/RustCrypto/elliptic-curves/pull/295
[#296]: https://github.com/RustCrypto/elliptic-curves/pull/296
[#319]: https://github.com/RustCrypto/elliptic-curves/pull/319
[#324]: https://github.com/RustCrypto/elliptic-curves/pull/324
[#328]: https://github.com/RustCrypto/elliptic-curves/pull/328
[#330]: …
=> k256 v0.8.0

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- `jwk` feature ([#279])
- Wycheproof ECDSA P-256 test vectors ([#313])
- `Order` constant ([#328])
- Rename `ecdsa::Asn1Signature` to `::DerSignature` ([#288])
- Migrate to `FromDigest` trait from `ecdsa` crate ([#292])
- Bump `elliptic-curve` to v0.9.2 ([#296])
- Bump `pkcs8` to v0.6 ([#319])
- Bump `ecdsa` crate dependency to v0.11 ([#330])
- `DigestPrimitive` feature gating ([#324])
[#279]: https://github.com/RustCrypto/elliptic-curves/pull/279
[#288]: https://github.com/RustCrypto/elliptic-curves/pull/288
[#292]: https://github.com/RustCrypto/elliptic-curves/pull/292
[#296]: https://github.com/RustCrypto/elliptic-curves/pull/296
[#313]: https://github.com/RustCrypto/elliptic-curves/pull/313
[#319]: https://github.com/RustCrypto/elliptic-curves/pull/319
[#324]: …
=> p256 v0.8.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml, p384/src/lib.rs
- `jwk` feature ([#279])
- `Order` constant ([#328])
- Rename `ecdsa::Asn1Signature` to `::DerSignature` ([#288])
- Bump `elliptic-curve` crate dependency to v0.9 ([#293])
- Bump `pkcs8` crate dependency to v0.6 ([#319])
- Bump `ecdsa` crate dependency to v0.11 ([#330])
[#279]: https://github.com/RustCrypto/elliptic-curves/pull/279
[#288]: https://github.com/RustCrypto/elliptic-curves/pull/288
[#293]: https://github.com/RustCrypto/elliptic-curves/pull/293
[#319]: https://github.com/RustCrypto/elliptic-curves/pull/319
[#328]: https://github.com/RustCrypto/elliptic-curves/pull/328
[#330]: https://github.com/RustCrypto/elliptic-curves/pull/330
=> p384 v0.7.0

k256/src/arithmetic/projective.rs, p256/src/arithmetic/projective.rs
The mixed point additions are not complete; they assume that the point in affine coordinates is not the point at infinity.
Handle that case, if only for consistency with non-mixed addition.
Fixes #336
=> p256/k256: fix mixed coordinate addition with the point at infinity

Cargo.lock, k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/projective.rs
Implements a newly added trait in the `elliptic-curve` crate which uses an associated type to encode a baseline set of trait bounds on curve points with affine coordinates:
https://github.com/RustCrypto/traits/pull/658
=> k256+p256: implement `AffineArithmetic` trait

Cargo.lock, k256/src/arithmetic/affine.rs, p256/src/arithmetic/affine.rs
Adds stubs which make these crates code-compatible with these changes:
https://github.com/RustCrypto/traits/pull/659
No actual support is provided though. Points with 0x05 "SEC1" tags simply fail to decode. However, this opens the door to eventually implementing support.
=> k256+p256: stub out point compaction support

.github/workflows/k256.yml, .github/workflows/p256.yml, Cargo.lock, Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, tests/Cargo.toml
Changelogs:
- `elliptic-curve`: https://github.com/RustCrypto/traits/pull/663
- `ecdsa`: https://github.com/RustCrypto/signatures/pull/316
=> Bump `elliptic-curve` to v0.10; `ecdsa` to v0.12

k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, k256/src/ecdsa/verify.rs, k256/src/lib.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/projective.rs, p256/src/lib.rs
Implements traits from the `group` crate for prime order curves:
- AffinePoint
- GroupEncoding
- PrimeCurveAffine
- ProjectivePoint
- GroupEncoding
- PrimeGroup
- PrimeCurve
=> k256+p256: impl PrimeCurve traits

Cargo.lock, bp256/CHANGELOG.md, bp256/Cargo.toml, bp256/README.md, bp256/src/lib.rs, bp384/CHANGELOG.md, bp384/Cargo.toml, bp384/README.md, bp384/src/lib.rs
- Bump `elliptic-curve` to v0.10; MSRV 1.51+ ([#349])
- Bump `ecdsa` to v0.12 ([#349])
[#349]: https://github.com/RustCrypto/elliptic-curves/pull/349
=> bp256+bp384 v0.2.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/README.md, k256/src/lib.rs
- Derive `Ord` on `ecdsa::VerifyingKey` ([#343])
- `AffineArithmetic` trait impl ([#347])
- `PrimeCurve` trait impls ([#350])
- Bump `elliptic-curve` to v0.10; MSRV 1.51+ ([#349])
- Bump `ecdsa` to v0.12 ([#349])
[#343]: https://github.com/RustCrypto/elliptic-curves/pull/343
[#347]: https://github.com/RustCrypto/elliptic-curves/pull/347
[#349]: https://github.com/RustCrypto/elliptic-curves/pull/349
[#350]: https://github.com/RustCrypto/elliptic-curves/pull/350
=> k256 v0.9.0

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- `AffineArithmetic` trait impl ([#347])
- `PrimeCurve` trait impls ([#350])
- Bump `elliptic-curve` to v0.10; MSRV 1.51+ ([#349])
- Bump `ecdsa` to v0.12 ([#349])
[#347]: https://github.com/RustCrypto/elliptic-curves/pull/347
[#349]: https://github.com/RustCrypto/elliptic-curves/pull/349
[#350]: https://github.com/RustCrypto/elliptic-curves/pull/350
=> p256 v0.9.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml, p384/README.md, p384/src/lib.rs
- Bump `elliptic-curve` to v0.10; MSRV 1.51+ ([#349])
- Bump `ecdsa` to v0.12 ([#349])
[#349]: https://github.com/RustCrypto/elliptic-curves/pull/349
=> p384 v0.8.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- `Copy` impl for `ecdsa::VerifyingKey` ([#355])
[#355]: https://github.com/RustCrypto/elliptic-curves/pull/355
=> k256 v0.9.1

Cargo.lock, k256/Cargo.toml, k256/src/ecdsa/sign.rs
The `Eq`/`PartialEq` impls use `ConstantTimeEq` internally.
This is useful for writing tests that need to compare keys.
=> k256: impl `Eq`/`PartialEq`/`ConstantTimeEq` for `SigningKey`

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- `Debug` impl for `ecdsa::SigningKey` ([#358])
- `ConstantTimeEq`/`Eq`/`PartialEq` impls for `ecdsa::SigningKey` ([#359])
[#358]: https://github.com/RustCrypto/elliptic-curves/pull/358
[#359]: https://github.com/RustCrypto/elliptic-curves/pull/359
=> k256 v0.9.2

p256/src/arithmetic/scalar.rs
- Place `Scalar::invert` and `Scalar::invert_vartime` next to each other
- Consolidate the `shr1` free function into `Scalar::shr1` (the free function was *only* used by latter otherwise)
=> p256: minor cleanups

k256/src/ecdsa/sign.rs
The previous name is retained as a deprecated alias.
This better patches the `VerifyingKey` type name.
=> k256: rename `SigningKey::verify_key()` -> `::verifying_key()`

README.md, p256/README.md, p256/src/lib.rs
The MSRV is 1.51+, but bumping it was missed in a few places
=> Fix MSRV documentation

k256/Cargo.toml, k256/bench/bench.rs
Enables them via conditional compilation when the `expose-field` crate feature is enabled.
=> k256: make field benchmarks optional

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Bump `elliptic-curve` dependency to v0.10.3 ([#371])
[#371]: https://github.com/RustCrypto/elliptic-curves/pull/371
=> k256 v0.9.3

k256/CHANGELOG.md
It was mistakenly left out of the v0.9.3 release notes
=> k256: add CHANGELOG.md entry for #363

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/arithmetic/mul.rs, k256/src/lib.rs
- Derive `Clone` for `ecdsa::SigningKey` ([#374])
[#374]: https://github.com/RustCrypto/elliptic-curves/pull/374
=> k256 v0.9.4

k256/bench/scalar.rs, k256/src/arithmetic.rs, k256/src/arithmetic/mul.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/verify.rs, k256/src/lib.rs
The goal of this PR is to optimize a commonly used operation `(x * k + y * l)` where `x` and `y` are curve points, and `k` and `l` are scalars. It is currently used in `verify.rs` and `recoverable.rs`. 
On my machine it speeds up ECDSA verification from 176us to 145us (and the newly added benchmark shows speed-up from 157us to 124us for linear combination alone).
Currently there PR contains a `lincomb_generic()` that takes arrays, and it has two aliases: `mul()` (internal, used in operator traits) and `lincomb()` (public, for two-point linear combinations).
=> Optimized linear combination of points

k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/ecdsa/normalize.rs, k256/src/ecdsa/verify.rs
Per BIP62, the valid range for "low" scalars is:
https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#Low_S_values_in_signatures
> The value S in signatures must be between 0x1 and 0x7FFFFFFF FFFFFFFF
> FFFFFFFF FFFFFFFF 5D576E73 57A4501D DFE92F46 681B20A0 (inclusive).
...where the large hex constant is the scalar modulus / 2.
However, the previous implementation was exclusive. There were tests for this particular case, but the tests confirmed it was exclusive instead of inclusive.
This commit fixes both the tests and the implementation to confirm that the scalar modulus / 2 is *NOT* considered high by `Scalar::is_high`, however scalar modulus / 2 + 1 is high.
=> k256: fix edge case in `Scalar::is_high`

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Wycheproof test vectors ([#384])
- Edge case in `Scalar::is_high` ([#385])
- Bug in overflow check during 32-bit multiplication ([#388])
[#384]: https://github.com/RustCrypto/elliptic-curves/pull/384
[#385]: https://github.com/RustCrypto/elliptic-curves/pull/385
[#388]: https://github.com/RustCrypto/elliptic-curves/pull/388
=> k256 v0.9.6

p256/src/arithmetic/affine.rs, p256/src/arithmetic/field.rs, p256/src/lib.rs
This may not quite be what you had in mind, especially with the modifications to field math to expose the borrow, but it was the shortest way to show what we'd done so far using the new elliptic curve traits
=> implement compact support for p256

p256/src/arithmetic/scalar.rs
Implements Tonelli-Shank's algorithm for q mod 16 = 1 as synthesized using the `ff_derive` crate, then modified to use `Self::pow_vartime` (with a fixed exponent, where it is only variable time with respect to the exponent)
As part of implementing this, it was discovered that `root_of_unity()` was incorrect. I (re)calculated it using sage:
```sage
sage: n = 115792089210356248762697446949407573529996955224135760342422259061068512044369
sage: GF(n).primitive_element()
7
sage: s = 4
sage: t = (n - 1) >> s
sage: power_mod(7,t,n)
115695789336771192084080718687965001507772259361175921799893286721837170845186
```
Closes #170
=> p256: implement `Scalar::sqrt`

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/lib.rs
This commit begins the process of starting to retrofit representing the scalar modulus as a `crypto_bigint::UInt`.
It isn't a perfect fit in the current form as the `force-32-bit` cargo feature complicates things. It would probably make sense to get rid of it in the next breaking release, especially as it isn't additive. Instead it should be easy to do 32-bit testing with `cross`.
All that said, it's now possible to calculate constants like `FRAC_MODULUS_2` at compile time using `const fn` which is pretty neat.
=> k256: use `crypto-bigint` for `scalar::MODULUS`

.github/workflows/workspace.yml, k256/src/arithmetic/field.rs, k256/src/arithmetic/field/field_10x26.rs, k256/src/arithmetic/field/field_5x52.rs, k256/src/arithmetic/field/field_impl.rs, k256/src/arithmetic/mul.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/scalar_4x64.rs, k256/src/arithmetic/scalar/scalar_8x32.rs, k256/src/ecdsa/verify.rs
Ensures `k256` passes clippy under Rust 1.54
=> k256: clippy fixes

k256/src/arithmetic/scalar.rs
Implements Tonelli-Shank's algorithm for q mod 16 = 1 as synthesized using the `ff_derive` crate, similar to #392 which implements it for the `p256`.
Like in `p256`, as part of implementing this it was discovered that `root_of_unity()` was incorrect. Here it is (re)calculated with sage:
```sage
sage: n = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
sage: GF(n).primitive_element()
7
sage: s = 6
sage: t = (n - 1) >> s
sage: power_mod(7,t,n)
5480320495727936603795231718619559942670027629901634955707709633242980176626
```
Note that the value was computed correctly originally, but the hex digits were shifted such that the resulting value was left shifted by 4-bits. This has now been corrected.
=> k256: implement `Scalar::sqrt`

.github/workflows/k256.yml, .github/workflows/p256.yml, Cargo.lock, Cargo.toml, bp256/Cargo.toml, bp256/src/lib.rs, bp384/Cargo.toml, bp384/src/lib.rs, k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/ecdsa.rs, k256/src/ecdsa/normalize.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs, k256/src/lib.rs, p256/Cargo.toml, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p256/src/ecdsa.rs, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
Sourced from git.
This includes transitive updates to ff and group v0.11. A major notable change of these updates is switching several APIs to use `subtle::Choice` and `subtle::CtOption` instead of `bool`/`Option`.
Fortunately, the crates in this repo are already written with constant-time implementations internally, so this was an easy change.
=> Bump `elliptic-curve` to v0.11.0-pre

Cargo.lock, k256/src/ecdsa.rs, k256/src/ecdsa/normalize.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs
Corresponding changes for RustCrypto/signatures#355
=> k256: make `ecdsa::Signature::normalize_s` non-mutating

Cargo.lock, Cargo.toml, p256/src/arithmetic/projective.rs, p256/src/arithmetic/scalar.rs
This is a minimally invasive change to use `crypto_bigint::U256` as the internal representation of `p256::Scalar`.
There are several places that various functions are still using a `U64x4` type which could be made to work over 8 x 32-bit limbs instead on 32-bit platforms, which is what `U256` uses internally.
This commit doesn't attempt to implement those changes, but rather just switch out the type used for the internal representation. This should hopefully avoid any regressions in this particular change.
=> p256: use `U256` as the internal representation of `Scalar`

p256/src/arithmetic/projective.rs, p256/src/arithmetic/scalar.rs, p256/src/lib.rs
- Iterate directly over limbs in `mul` implementation
- Promote `Scalar::ZERO` and `Scalar::ONE` to inherent constants
- Replace some hardcoded constants with `const fn` calculations
=> p256: better utilize `UInt` in `Scalar` impls

Cargo.lock, bp256/src/r1.rs, bp256/src/t1.rs, bp384/src/r1.rs, bp384/src/t1.rs, k256/src/arithmetic/affine.rs, k256/src/ecdsa/recoverable.rs, k256/src/lib.rs, p256/src/arithmetic/affine.rs, p256/src/lib.rs, p384/src/lib.rs
Switches from `weierstrass::Curve` to the `PrimeCurve` trait added in RustCrypto/traits#737.
=> Use `PrimeCurve` trait

.github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/workspace.yml, Cargo.lock, README.md, bp256/README.md, bp256/src/lib.rs, bp384/README.md, bp384/src/lib.rs, k256/LICENSE-MIT, k256/README.md, k256/src/arithmetic/projective.rs, k256/src/lib.rs, p256/LICENSE-MIT, p256/README.md, p256/src/arithmetic/projective.rs, p256/src/lib.rs, p384/LICENSE-MIT, p384/src/lib.rs
Implements the `PrimeCurveArithmetic` trait introduced in RustCrypto/traits#739
=> k256+p256: impl `PrimeCurveArithmetic`; MSRV 1.52

Cargo.lock, k256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs
Adds the scalar conversion bounds from RustCrypto/traits#740
=> k256+p256: scalar conversion bounds

Cargo.lock, Cargo.toml, k256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs
`crypto-bigint` v0.2.7 fixed a bug in `UInt::add_mod` in https://github.com/RustCrypto/utils/pull/619, and the `elliptic-curve` crate has been updated to depend on this version at a minimum.
This means we can now use it to implement scalar addition.
=> k256+p256: use `UInt::add_mod` for scalar addition

k256/src/arithmetic/mul.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs
This, combined with a small fixup to `conditional_add_bit`, ensures that all of the `Scalar`-related word size-specific gating is relegated to the `wide32.rs` vs `wide64.rs` modules.
Ideally these could be replaced with a common `U512`-based implementation which further reduces this gating, but that's left for a followup step.
=> k256: factor `mul_shift_var(time)` into `wide` module

k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs
This is no longer needed as the function needing access has been moved to the `WideScalar` type.
=> k256: remove `pub(super)` from `WideScalar`'s `.0` field

k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs
The case it's actually being used for in practice is much simpler and can be easily expressed using the current functionality.
=> k256: remove `Scalar::conditional_add_bit`

Cargo.lock, Cargo.toml
Updates `elliptic-curve` to a new version which uses the (unreleased) `sec1 crate.
See RustCrypto/traits#765
=> Bump `elliptic-curve` crate; add `sec1` crate patches

Cargo.lock, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, k256/src/arithmetic/affine.rs, k256/src/ecdsa.rs, p256/Cargo.toml, p256/src/arithmetic/affine.rs, p384/Cargo.toml
These code changes are necessary to support a migration to the `sec1` crate, which extracted types like `EncodedPoint` into a separate reusable crate.
Relevant `elliptic-curve` PR:
https://github.com/RustCrypto/traits/pull/771
=> Updates for `sec1` crate

k256/src/arithmetic/scalar.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs, p256/src/arithmetic/scalar.rs, p256/src/ecdsa.rs
Adds trait impls to `k256::Scalar` and `p256::Scalar` for the newly introduced `Reduce` trait, replacing the previous inherent methods:
https://github.com/RustCrypto/traits/pull/768
=> k256+p256: impl `Reduce` trait on `Scalar` types

Cargo.lock, Cargo.toml
Bumps `elliptic-curve` and `ecdsa` git hashes and removes patch dependencies for `der` and `sec1`.
=> Use the `sec1` v0.1 crate release

Cargo.lock, k256/src/arithmetic/scalar.rs, k256/src/ecdsa/sign.rs, p256/src/arithmetic/scalar.rs
The `FromDigest` trait has been removed from the `ecdsa` crate, in favor of using the `Reduce` trait:
https://github.com/RustCrypto/signatures/pull/372
This is the corresponding set of changes to the above upstream PR to the `ecdsa` crate which implements this change.
=> k256+p256: replace `ecdsa::hazmat::FromDigest` with `Reduce`

p256/src/arithmetic/projective.rs
This could maybe alternatively be fixed "upstream" in `EncodedPoint::len()`?
Fixes #442.
=> Fix `to_bytes()` for `ProjectivePoint::identity()`

Cargo.lock, k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/projective.rs
Corresponding changes for:
https://github.com/RustCrypto/traits/pull/782
Internally these were already returning `CtOption` anyway. It should also simplify the implementation of `GroupEncoding`.
=> k256+p256: make `FromEncodedPoint` return a `CtOption`

k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/projective.rs
`GroupEncoding` uses a fixed-width `Repr` whereas SEC1 is variable-width with respect to compressed points versus the identity.
This change allows 33-bytes of zeroes to be used as the identity. Technically that's not a valid SEC1 encoding: the SEC1 encoding for the identity is 1-byte: 0x00. However, this is the best we can do with a fixed-width encoding.
See also: #443 and #444
=> k256+p256: handle identity point in `GroupEncoding`

k256/src/ecdsa/sign.rs
Adds a `Drop` handler which calls `zeroize()` on the `NonZeroScalar` which the `SigningKey` newtype wraps.
=> k256: impl `Drop` for `ecdsa::SigningKey`

Cargo.lock, Cargo.toml
Pull in the prerelease format parsers so we can properly integration test them for the elliptic curve use case.
=> Use prerelease format parsers

Cargo.lock, k256/src/arithmetic/scalar.rs, k256/src/ecdsa/verify.rs, p256/src/arithmetic/projective.rs, p256/src/arithmetic/scalar.rs
Updates to the latest `elliptic-curve` and RustCrypto/formats crates
=> Bump dependencies

Cargo.lock, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs
Updates to the latest git version of the `pkcs8` crate, which uses `TryFrom` to handle the final step of decoding keys
=> Update `pkcs8` crate

Cargo.lock, Cargo.toml
Removes the git-based dependencies
=> Use released RustCrypto/formats crates

k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs
It has been renamed to `SigningKey::verifying_key` instead.
=> k256: remove deprecated `SigningKey::verify_key` method

Cargo.lock, k256/bench/ecdsa.rs, k256/src/arithmetic/affine.rs, k256/src/arithmetic/mul.rs, k256/src/arithmetic/scalar.rs, k256/src/ecdsa/normalize.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/scalar.rs, p256/src/ecdsa.rs
This updates the crates in this repo to leverage the following generic implementations recently added to the `ecdsa` crate:
- Sign: RustCrypto/signatures#396
- Verify: RustCrypto/signatures#397
The `p256` crate is able to directly utilize the generic implementation from the `ecdsa` crate.
The `k256` crate retains its previous custom implementation, which provides a secp256k1-specific take on public key recovery, but can also directly leverage optimizations for computing linear combinations, which there are not presently traits in `elliptic-curve` or `group` to express.
=> Update `ecdsa` crate and leverage generic ECDSA implementations

.github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, Cargo.lock, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml
Adds a `serde` feature to all crates which activates the corresponding `serde` feature in the `ecdsa`, `elliptic-curve`, and `sec1` crates.
=> Add `serde` feature

Cargo.lock, Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml
Release notes: https://github.com/RustCrypto/traits/pull/821
=> Bump `elliptic-curve` crate dependency to v0.11

Cargo.lock, p256/Cargo.toml, p256/src/lib.rs
This pre-release includes upgrades to the following:
- `ecdsa` v0.13
- `elliptic-curve` v0.11
- `ff` v0.11
- `group` v0.11
=> p256 v0.10.0-pre.1

.cargo/audit.toml
Ignores `RUSTSEC-2021-0127`: `serde_cbor` is unmaintained
This is a transitive dependency of `criterion`
=> .cargo/audit.toml: initial config with RUSTSEC-2021-0127

k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs
Adds a second impl of the `Reduce` trait for `Scalar` (where the first was `U256`).
This provides a simple thunk to `WideScalar::reduce`.
=> k256: impl `Reduce<U512>` for `Scalar`

Cargo.lock, k256/src/ecdsa/sign.rs
The extraction of the RFC6979 implementation in the `ecdsa` crate into the `rfc6979` crate resulted in a suboptimal API for general use.
This commit uses a helper function added in `ecdsa` v0.13.1 which simplifies the API.
=> k256: use `ecdsa::hazmat::rfc6979_generate_k`

Cargo.lock, k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs
Provides an impl of the `ReduceNonZero` trait added in [RustCrypto/elliptic-curves#827](https://github.com/RustCrypto/traits/pull/827), which provides a reduction from a 512-bit (64-byte) input, i.e. a "wide" reduction from an integer twice the size of the curve's order, to a `Scalar` which is guaranteed to be non-zero.
Based on @fjarri's work in #432
=> k256: impl `ReduceNonZero<U512>` for `Scalar`

bp256/src/lib.rs, bp384/src/lib.rs, k256/README.md, k256/src/arithmetic/affine.rs, k256/src/arithmetic/scalar.rs, k256/src/ecdsa/verify.rs, k256/src/lib.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/scalar.rs, p256/src/lib.rs, p384/src/lib.rs
- Use `doc = include_str!` attribute to include README.md
- Add documentation for `serde` features
=> Documentation improvements

Cargo.lock, k256/Cargo.toml, k256/bench/scalar.rs, k256/src/arithmetic.rs, k256/src/arithmetic/mul.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/verify.rs, k256/src/lib.rs, p256/src/arithmetic.rs
Adds impls of traits for linear combinations added in RustCrypto/traits#833:
- `k256` uses an optimized implementation.
- `p256` uses the default unoptimized implementation.
=> k256+p256: impl `LinearCombination` trait

Cargo.lock, k256/Cargo.toml, k256/bench/scalar.rs, k256/src/arithmetic/mul.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/verify.rs, p256/Cargo.toml, p256/src/arithmetic.rs, p256/src/arithmetic/projective.rs
=> k256+p256: use revised `LinearCombination` trait

Cargo.lock, bp256/CHANGELOG.md, bp256/Cargo.toml, bp256/src/lib.rs
- `serde` feature ([#463])
[#453]: https://github.com/RustCrypto/elliptic-curves/pull/453
[#463]: https://github.com/RustCrypto/elliptic-curves/pull/463
[#466]: https://github.com/RustCrypto/elliptic-curves/pull/466
[#467]: https://github.com/RustCrypto/elliptic-curves/pull/467
=> bp256 v0.3.0

Cargo.lock, bp384/CHANGELOG.md, bp384/Cargo.toml, bp384/src/lib.rs
- `serde` feature ([#463])
[#453]: https://github.com/RustCrypto/elliptic-curves/pull/453
[#463]: https://github.com/RustCrypto/elliptic-curves/pull/463
[#466]: https://github.com/RustCrypto/elliptic-curves/pull/466
[#467]: https://github.com/RustCrypto/elliptic-curves/pull/467
=> bp384 v0.3.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- Implement `Scalar::sqrt` ([#400])
- Impl `PrimeCurveArithmetic` ([#415])
- Impl `Reduce<U256>` for `Scalar` ([#436])
- Impl `Drop` for `ecdsa::SigningKey` ([#449])
- `serde` feature ([#463], [#464])
- Impl `Reduce<U512>` for `Scalar` ([#472])
- Impl `ReduceNonZero<U512>` for `Scalar` ([#474])
- Impl `LinearCombination` trait ([#476])
- Make `ecdsa::Signature::normalize_s` non-mutating ([#405])
- Use `PrimeCurve` trait ([#413])
- Use `sec1` crate for `EncodedPoint` type ([#435])
- Replace `ecdsa::hazmat::FromDigest` with `Reduce` ([#438])
- Make `FromEncodedPoint` return a `CtOption` ([#445])
- `force-32-bit` feature ([#399])
- …
=> k256 v0.10.0

Cargo.lock, k256/CHANGELOG.md, p256/CHANGELOG.md, p256/Cargo.toml, p256/src/lib.rs
- Implement point compaction support ([#357])
- Implement `Scalar::sqrt` ([#392])
- Impl `DefaultIsZeroes` for `ProjectivePoint` ([#414])
- Impl `PrimeCurveArithmetic` ([#415])
- Impl `Reduce<U256>` for `Scalar` ([#436])
- `serde` feature ([#463], [#465])
- Impl `LinearCombination` trait ([#476])
- Use `PrimeCurve` trait ([#413])
- Use `sec1` crate for `EncodedPoint` type ([#435])
- Replace `ecdsa::hazmat::FromDigest` with `Reduce` ([#438])
- Make `FromEncodedPoint` return a `CtOption` ([#445])
- Leverage generic ECDSA implementation from `ecdsa` crate ([#462])
- Handle identity point in `GroupEncoding` ([#446])
[#357]: …
=> p256 v0.10.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml, p384/src/lib.rs
- `serde` feature ([#463])
- Use `sec1` crate for `EncodedPoint` type ([#435])
[#435]: https://github.com/RustCrypto/elliptic-curves/pull/435
[#453]: https://github.com/RustCrypto/elliptic-curves/pull/453
[#463]: https://github.com/RustCrypto/elliptic-curves/pull/463
[#466]: https://github.com/RustCrypto/elliptic-curves/pull/466
[#467]: https://github.com/RustCrypto/elliptic-curves/pull/467
=> p384 v0.9.0

Cargo.lock, p384/Cargo.toml, p384/src/arithmetic.rs, p384/src/arithmetic/affine.rs, p384/src/arithmetic/field.rs, p384/src/lib.rs
Partial implementation of `AffinePoint`, with coordinates internally represented using `FieldElement` type which wraps fiat-crypto's base field arithmetic.
With this in place, `FieldElement` can be removed from the public API without any warnings about dead code.
Note: the implementation is not yet fully correct and some of the tests have been flagged with `#[ignore]`.
=> p384: add `AffinePoint`

p256/src/arithmetic/affine.rs, p256/src/arithmetic/field.rs, p384/src/arithmetic.rs, p384/src/arithmetic/field.rs
Adds wrappers for fiat-crypto's `fiat_p384_from_montgomery` and `fiat_p384_to_montgomery`, using them to translate field elements into and out of the Montgomery domain when decoding or encoding them from big endian-serialized canonical form.
Also ensures field element constants are already in Montgomery form.
=> p384: add `FieldElement::{to_canonical, to_montgomery}`

p384/src/arithmetic/scalar.rs
An inherent method is easier to constify, although that isn't possible until `Scalar::montgomery_reduce` is `const fn`, which requires a `const fn` implementation of conditionally subtracting the modulus.
=> p384: factor `Scalar::mul` into an inherent method

k256/src/arithmetic/affine.rs, k256/src/arithmetic/field.rs, k256/src/arithmetic/projective.rs, p256/src/arithmetic.rs, p256/src/arithmetic/affine.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/projective.rs
Allows for writing code which is generic over field elements, such as the optimized SWU implementation added in RustCrypto/traits#854
=> k256+p256: impl `ff::Field` trait for `FieldElement` types

k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs
- add impl of `ReduceNonZero<U256>` for `Scalar`
- fix a bug in `WideScalar::reduce_nonzero()` (a zero value returned when reducing `MODULUS-1`)
Very embarrassing for me, but at least chances of someone hitting it were astronomically small, and if they did, it most probably resulted in a panic during inversion or something of the sort.
=> k256: add impl of `ReduceNonZero<U256>` for `Scalar`

p256/src/arithmetic/affine.rs
This is a stepping stone towards solving #508 for `p256`.
Replaces the implementation of `AffinePoint::generator` with one that uses Rust literal syntax to construct the field elements which represent the base point's affine coordinates.
Coordinates are specified in canonical form for easy auditability, then converted to Montgomery form. With `const fn`, this conversion could happen completely at compile time.
This can't yet be made fully `const` though, as there isn't a `const fn` constructor for `subtle::Choice`, which is used to represent the point at infinity.
=> p256: make `AffinePoint::generator` closer to const-friendly

k256/bench/scalar.rs, k256/src/arithmetic/affine.rs, k256/src/arithmetic/mul.rs, k256/src/arithmetic/projective.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs
Adds inherent constants to `AffinePoint` and `ProjectivePoint` representing the identity and generator points.
This should make it possible to write `const fn`s that produce things like precomputed basepoint tables (see #508).
Deprecates the previous inherent methods on `ProjectivePoint` for returning these constants.
=> k256: `IDENTITY` and `GENERATOR` point constants

k256/src/arithmetic/projective.rs, p256/src/arithmetic/projective.rs
Moves the inherent method definitions to the same impl block as the one that defines the `IDENTITY` and `GENERATOR` constants.
=> p256: consolidate `ProjectivePoint` impl blocks

.github/workflows/p256.yml, .github/workflows/p384.yml, Cargo.lock, p256/Cargo.toml, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
See RustCrypto/traits#878.
Reference: https://www.ietf.org/archive/id/draft-irtf-cfrg-voprf-08.html#section-4.
=> Implement `VoprfParameters` for `NistP256` and `NistP384`

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/lib.rs
- hash2curve support: impl `GroupDigest` for `Secp256k1` ([#503])
- `IDENTITY` and `GENERATOR` point constants ([#511])
[#503]: https://github.com/RustCrypto/elliptic-curves/pull/503
[#511]: https://github.com/RustCrypto/elliptic-curves/pull/511
=> k256 v0.10.3

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml, p256/LICENSE-MIT, p256/src/lib.rs
- Impl `ff::Field` trait for `FieldElement` ([#498])
- hash2curve support: impl `GroupDigest` trait for `NistP256` ([#503])
- Impl `VoprfParameters` trait for `NistP256` ([#506])
- Impl `ReduceNonZero<U256>` trait for `Scalar` ([#507])
- `IDENTITY` and `GENERATOR` point constants ([#509], [#511])
[#498]: https://github.com/RustCrypto/elliptic-curves/pull/498
[#503]: https://github.com/RustCrypto/elliptic-curves/pull/503
[#506]: https://github.com/RustCrypto/elliptic-curves/pull/506
[#507]: https://github.com/RustCrypto/elliptic-curves/pull/507
[#509]: https://github.com/RustCrypto/elliptic-curves/pull/509
[#511]: https://github.com/RustCrypto/elliptic-curves/pull/511
=> p256 v0.10.1

.github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/workspace.yml, Cargo.lock, Cargo.toml, README.md, bp256/Cargo.toml, bp256/README.md, bp384/Cargo.toml, bp384/README.md, k256/Cargo.toml, k256/README.md, k256/src/arithmetic/hash2curve.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/ecdsa/verify.rs, p256/Cargo.toml, p256/README.md, p256/src/arithmetic/affine.rs, p256/src/arithmetic/hash2curve.rs, p256/src/arithmetic/scalar/blinded.rs, p384/Cargo.toml, p384/README.md
This builds on RustCrypto/traits#883 and RustCrypto/signatures#433.
=> Update elliptic-curve, digest and ecdsa

Cargo.lock, bp256/Cargo.toml, bp256/src/lib.rs, bp384/Cargo.toml, bp384/src/lib.rs, k256/Cargo.toml, k256/src/lib.rs, p256/Cargo.toml, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
Now that #515 which upgrades to prereleases of the `elliptic-curve` and `ecdsa` crates has been merged, bump the version numbers of all crates to prereleases to indicate breaking changes have been made.
=> Bump versions to prereleases

k256/CHANGELOG.md
This release backports #530.
Since `master` is already v0.11 prereleases, this commit just contains the release notes.
The released code can be found via the `k256/v0.10.3` tag:
https://github.com/RustCrypto/elliptic-curves/tree/k256/v0.10.3
=> k256: add v0.10.3 release notes

k256/src/arithmetic/hash2curve.rs
An `is_odd()` call I forgot to address in #530
While this fixes the problem at hand, there are a couple of considerations:
- To prevent future problems like this, we do need either #531, or just auto-normalizing in `FieldElement::is_odd()` (but not in `FieldElementImpl`!). Originally I didn't do that because I wanted to leave a possibility for a slightly more efficient code (where the caller would know whether the value has been previously normalized or not), but perhaps it is not worth it, and it's better to prevent errors instead.
- This was not caught in tests in #530 because in CI we run tests with `--release`, and apparently this bug does not affect `hash2curve` test, which is the only one touching `sgn0()`. @tarcieri , why was that decision made originally?
=> k256: normalize before calling is_odd() in sng0()

k256/CHANGELOG.md
This release backports #533.
Since `master` is already v0.11 prereleases, this commit just contains the release notes.
The released code can be found via the `k256/v0.10.4` tag:
https://github.com/RustCrypto/elliptic-curves/tree/k256/v0.10.4
=> k256: add v0.10.4 release notes

Cargo.lock, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/verify.rs, p256/Cargo.toml, p256/src/arithmetic/affine.rs, p256/src/arithmetic/projective.rs, p384/Cargo.toml
The inner type of `VerifyingKey` is a `PublicKey`, which is itself a wrapper for an inner curve-specific `AffinePoint` which ensures that the inner point is *NOT* the additive identity / point at infinity.
Therefore, any conversion from an `AffinePoint` is potentially fallible, so the existing `From` conversions need to be changed to `TryFrom`.
This commit also adds some additional type conversions between `AffinePoint`/`ProjectivePoint` and `PublicKey`/`VerifyingKey`, and also includes them in `p256` for consistency.
=> k256: fallible `AffinePoint` to `VerifyingKey` conversion

k256/src/ecdsa.rs, k256/src/ecdsa/recoverable.rs, p256/src/ecdsa.rs
The type was renamed from `VerifyKey` to `VerifyingKey` quite awhile
ago, however there are still a handful of method names defined on
`k256::ecdsa::recoverable::VerifyingKey` that didn't get updated
accordingly:
- `recover_verify_key` => `recover_verifying_key`
- `recover_verify_key_from_digest` => `recover_verifying_key_from_digest`
=> k256: remove remaining usages of `*_verify_key_*`

Cargo.lock, bp256/CHANGELOG.md, bp256/Cargo.toml
[#544]: https://github.com/RustCrypto/elliptic-curves/pull/544
=> bp256 v0.4.0

Cargo.lock, bp384/CHANGELOG.md, bp384/Cargo.toml
[#544]: https://github.com/RustCrypto/elliptic-curves/pull/544
=> bp384 v0.4.0

bp256/Cargo.toml, bp256/src/lib.rs, bp384/Cargo.toml, bp384/src/lib.rs, k256/Cargo.toml, k256/src/lib.rs, p256/Cargo.toml, p256/src/lib.rs, p384/Cargo.toml, p384/src/lib.rs
It's no longer recommended. See rust-lang/api-guidelines#229
=> Remove `html_root_url` from lib.rs files

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs
- Bump `digest` to v0.10 ([#515])
- Make `AffinePoint` to `VerifyingKey` conversion fallible ([#535])
- Rename `recover_verify_key` => `recover_verifying_key` ([#537])
- Rename `recover_verify_key_from_digest` => `recover_verifying_key_from_digest` ([#537])
- `hash2curve` crate feature ([#519])
[#515]: https://github.com/RustCrypto/elliptic-curves/pull/515
[#519]: https://github.com/RustCrypto/elliptic-curves/pull/519
[#535]: https://github.com/RustCrypto/elliptic-curves/pull/535
[#537]: https://github.com/RustCrypto/elliptic-curves/pull/537
[#544]: …
=> k256 v0.11.0

Cargo.lock, k256/CHANGELOG.md, p256/CHANGELOG.md, p256/Cargo.toml
- Bump `digest` to v0.10 ([#515])
[#515]: https://github.com/RustCrypto/elliptic-curves/pull/515
[#544]: https://github.com/RustCrypto/elliptic-curves/pull/544
=> p256 v0.11.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml
- Bump `digest` to v0.10 ([#515])
[#515]: https://github.com/RustCrypto/elliptic-curves/pull/515
[#544]: https://github.com/RustCrypto/elliptic-curves/pull/544
=> p384 v0.10.0

k256/Cargo.toml, k256/src/ecdsa/sign.rs
For whatever reason when the Ethereum developers decided to use Keccak256 as the digest function for ECDSA itself, they still used SHA-256 as the digest function for RFC6979, possibly because they didn't realize they needed to change the digest function in two places.
Previously the implementation in `k256` would use the same digest function for both (typically Keccak256) but we've had various complaints that doing so doesn't match the test vectors produced by various other libraries (though the signatures will still verify).
This commit uses HMAC-DRBG instantiated with SHA-256 for computing RFC6979 for `ecdsa::recoverable::Signature`, regardless of what digest function is used to hash the message. In theory this should match the Ethereum test vectors.
=> k256: use SHA-256 for computing RFC6979 for `recoverable::Signature`

k256/src/ecdh.rs, p256/src/ecdh.rs
Exports `diffie_hellman` within the `ecdh` module.
This is a low-level Diffie-Hellman function which can be used for static D-H where necessary.
Closes #555.
=> k256+p256: re-export low-level `diffie_hellman` function

k256/src/schnorr.rs, k256/src/schnorr/sign.rs, k256/src/schnorr/verify.rs
Adds general information about the scheme as well as a rustdoc example of how to use it
=> k256: document `schnorr` module

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- Taproot Schnorr as defined in BIP 340 ([#554], [#557], [#558])
- Re-export low-level `diffie_hellman` function ([#556])
- Use SHA-256 for computing RFC6979 for `recoverable::Signature` ([#552])
[#552]: https://github.com/RustCrypto/elliptic-curves/pull/552
[#554]: https://github.com/RustCrypto/elliptic-curves/pull/554
[#556]: https://github.com/RustCrypto/elliptic-curves/pull/556
[#557]: https://github.com/RustCrypto/elliptic-curves/pull/557
[#558]: https://github.com/RustCrypto/elliptic-curves/pull/558
=> k256 v0.11.1

k256/Cargo.toml
And also enable it on docs.rs when generating rustdoc
It has no additional dependencies beyond what is required by default, so there's little reason to leave it off-by-default.
=> k256: enable `schnorr` feature by default

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- Enable `schnorr` feature by default ([#561])
[#561]: https://github.com/RustCrypto/elliptic-curves/pull/561
=> k256 v0.11.2

p256/src/arithmetic/projective.rs, p256/src/arithmetic/scalar.rs
Immediately improves performance even on a variable base:
- 35% faster on x86_64
- 37% faster on M1
- 37% faster on WebAssembly (Wasmtime)
- 39% faster on WebAssembly (Wasmedge)
=> p256: use a 4-bit window for scalar multiplication

p384/src/arithmetic/field.rs, p384/src/arithmetic/projective.rs, p384/src/arithmetic/scalar.rs
Fix for broken test https://github.com/RustCrypto/elliptic-curves/pull/567#discussion_r883209549
Edit: The same check has been changed in `Scalar::invert()` but there was no existing test to detect this.
=> p384: `FieldElement::invert()` should check if self was non-zero

Cargo.toml, p384/src/arithmetic/affine.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
Fixes transcription errors in precomputed Montgomery form constants, and adds tests that the precomputed constants are correct.
32-bit inversions are still unimplemented so it's not yet possible to add CI for these tests yet.
=> p384: 32-bit fixups

.github/workflows/p384.yml, p384/src/arithmetic.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
Fixes the inversion implementation to work with both the 32-bit and 64-bit backends.
Since this was the last blocker for full 32-bit support, this commit also adds 32-bit CI configuration, including `cross`-based tests.
=> p384: fix 32-bit inversions and adds CI

p384/src/arithmetic.rs, p384/src/arithmetic/affine.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
- Make `FieldElement::MODULUS` an inherent constant
- Replace some bespoke logic with U384
=> p384: field cleanups

Cargo.lock, p384/src/arithmetic/field.rs
Leverages the new `AsRef` and `AsMut` impls on `crypto_bigint::UInt` to simplify passing the limbs array to fiat-crypto functions.
Uses a macro to write the arithmetic ops impls.
=> p384: `FieldElement` cleanups

p384/src/arithmetic/affine.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
- Ensure `FieldElement` is always in Montgomery form, changing `to_canonical` to return a `U384`.
- Remove duplicated `sqrt` implementation.
- Remove `DecompactPoint` impl on `AffinePoint`. We don't currently have test vectors so there's no way of knowing it's correct.
=> p384: additional field fixups

Cargo.lock, p384/src/arithmetic/macros.rs
Now that #589 is landed, it's possible to add `const fn` implementations of all core field operations, including conersions to/from Montgomery form as well as arithmetic operations: add, double, sub, mul, neg, square
=> p384: make core field ops `const fn`

p384/src/arithmetic.rs, p384/src/arithmetic/affine.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/macros.rs, p384/src/arithmetic/scalar.rs
Now that conversions to/from the Montgomery domain are `const fn` (#590) it's possible to define constants in their canonical form, rather than converting them into the Montgomery domain first.
This makes the code clearer and easier to audit.
=> p384: use canonical form constants

p256/src/ecdsa.rs, p384/src/ecdsa.rs
One additional test for `p256` and added matching to `p384`.
=> Add RFC 6979 test vectors to `p256` and `p384` ECDSA

p256/src/arithmetic/field.rs
In preparation for a `fiat-crypto` refactor, and for consistency with the other field implementations.
=> p256: move `FieldElement` inherent impl block to top of file

p256/Cargo.toml, p256/src/arithmetic/projective.rs, p384/src/arithmetic/projective.rs
Uses the generic implementation of Renes-Costello-Batina 2015 added to the `elliptic-curve` crate:
https://github.com/RustCrypto/traits/pull/1022
This is effectively the same changes as #601 made to `p384`, but for the `p256` crate.
=> p256: use generic prime order formulas

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml
- Re-export low-level `diffie_hellman` function ([#556])
- Additional RFC6979 test vectors ([#591])
- Use a 4-bit window for scalar multiplication ([#563])
- `invert()`, `sqrt()`: replace exponentiations with addition chains ([#564])
- Use generic prime order formulas ([#602])
[#556]: https://github.com/RustCrypto/elliptic-curves/pull/556
[#563]: https://github.com/RustCrypto/elliptic-curves/pull/563
[#564]: https://github.com/RustCrypto/elliptic-curves/pull/564
[#591]: https://github.com/RustCrypto/elliptic-curves/pull/591
[#602]: https://github.com/RustCrypto/elliptic-curves/pull/602
=> p256 v0.11.1

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml
- RFC6979 test vectors ([#591])
- Impl `serde::{Serialize, Deserialize}` for `Scalar` ([#604])
- Use generic prime order formulas ([#601])
[#591]: https://github.com/RustCrypto/elliptic-curves/pull/591
[#601]: https://github.com/RustCrypto/elliptic-curves/pull/601
[#604]: https://github.com/RustCrypto/elliptic-curves/pull/604
=> p384 v0.11.1

.github/workflows/p521.yml, .gitignore, Cargo.lock, Cargo.toml, README.md, p521/Cargo.toml, p521/LICENSE-APACHE, p521/LICENSE-MIT, p521/README.md, p521/src/lib.rs
This reverts commit 9c4a886a854a68f1965e51d2b81f0c5fe05e9b27.
Revives the skeleton of a `p521` crate which was previously removed in PR #115, with the goal of turning it into a full-fledged P-521 implementation.
=> Revert "p521: remove vaporware crate"

Cargo.lock, p521/CHANGELOG.md, p521/Cargo.toml, p521/LICENSE-MIT, p521/README.md, p521/src/lib.rs
Adds an initial type which impls the `elliptic_curve::Curve` trait and defines the order, JWK identifier, and PKCS#8 OID for secp521r1.
=> p521: initial `NistP521` type definitions

k256/src/ecdsa/sign.rs
Relax `DigestSigner` bounds as discussed in #612 .
=> k256: relax `DigestSigner` trait bounds

p256/src/arithmetic/projective.rs
Since `to_affine` doesn't return an `Option`, the mention of `None` in the documentation doesn't seem to make sense anymore.
=> Remove mention of `None` in `to_affine` docs

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- Relax `DigestSigner` trait bounds ([#613])
- Bump `elliptic-curve` to v0.12.2 ([#616])
[#613]: https://github.com/RustCrypto/elliptic-curves/pull/613
[#616]: https://github.com/RustCrypto/elliptic-curves/pull/616
=> k256 v0.11.3

k256/src/ecdsa/sign.rs, k256/src/schnorr/sign.rs
- `ecdsa::SigningKey` already has a `Drop` implemented, so just added the `ZeroizeOnDrop` marker
- For `schnor::SigningKey` implemented a zeroizing `Drop`, and added the `ZeroizeOnDrop` marker
`k256` 0.11 depends on `elliptic-curve` 0.12, which depends on `zeroize` 1.5, so this trait should be safe to use.
=> k256: implement `ZeroizeOnDrop` for `ecdsa::SigningKey` and `schnor::SigningKey`

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml
- Re-export low-level `diffie_hellman` function ([#627])
[#627]: https://github.com/RustCrypto/elliptic-curves/pull/627
=> p384 v0.11.2

p256/benches/field.rs, p256/src/arithmetic.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/hash2curve.rs, p256/src/arithmetic/scalar.rs
Incremental work towards making the `FieldElement` types between `p256` and `p384` more consistent, as well as laying the groundwork for a proper 32-bit backend.
=> p256: use `U256` as the inner type for `FieldElement`

p256/src/arithmetic.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/field/p256_32.rs, p256/src/arithmetic/field/p256_64.rs
Uses the same macro as `p384` to define the `FieldElement` type.
Isolates core arithmetic functionality in a `p256_64.rs` module, with the goal of eventually producing a 32-bit implementation as well.
Also adds a `p256_32.rs` module which provides a skeleton of a 32-bit implementation, although most of the functionality is currently implemented in terms of 64-bit integers, with the goal of facilitating an incremental conversion to a 32-bit backend.
=> p256: use `impl_field_element!` macro

p256/src/arithmetic.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/field/field32.rs, p256/src/arithmetic/field/field64.rs, p256/src/arithmetic/hash2curve.rs, p256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar/scalar32.rs, p256/src/arithmetic/scalar/scalar64.rs
This applies a similar treatment from #635 to the scalar backend, clearing the way to implement a proper 32-bit backend for both the base and scalar fields.
=> p256: initial 32-bit scalar backend

k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs
- Get rid of eager computation in `mul_shift_vartime()` in places where it is shift-dependent. It is expected to be vartime on the value of `shift`, and calculating some of the paths eagerly when they are not required leads to panics. Fixes #624
- Fix a typo in `mul_shift_vartime()` (incorrect constant, it was `448` instead of `384` in the expression for `r1`). Fortunately, since it was only ever used with `shift == 272`, it never mattered.
=> k256: get rid of eager computation in `mul_shift_vartime()`

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- Impl `ZeroizeOnDrop` for `ecdsa::SigningKey` and `schnorr::SigningKey` ([#630])
- Get rid of eager computation in `mul_shift_vartime()` ([#638])
- Bump the precision of precomputed division for the scalar decomposition ([#639])
[#630]: https://github.com/RustCrypto/elliptic-curves/pull/630
[#638]: https://github.com/RustCrypto/elliptic-curves/pull/638
[#639]: https://github.com/RustCrypto/elliptic-curves/pull/639
=> k256 v0.11.4

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- Impl `PrehashSigner` and `PrehashVerifier` traits for ECDSA keys ([#653])
- Impl `Keypair` for `SigningKey` ([#654])
[#653]: https://github.com/RustCrypto/elliptic-curves/pull/653
[#654]: https://github.com/RustCrypto/elliptic-curves/pull/654
=> k256 v0.11.5

k256/src/arithmetic/projective.rs
1. `ProjectivePoint::is_identity` was slow because it did an equality check with identity rather than just checking z coordinate == 0
2. Equality check was much slower than necessary because it converted to affine coords first. This algorithm does the check avoiding a modular inversion at the cost of a few multiplications. Around ~70 times faster.
I believe these changes are correct but please review carefully.
=> [k256] Make Proj point equality and is_identity faster

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- `ecdsa::recoverable::Signature::from_digest_bytes_trial_recovery` ([#660])
- Make `ProjectivePoint` equality and `is_identity` faster ([#650])
[#650]: https://github.com/RustCrypto/elliptic-curves/pull/650
[#660]: https://github.com/RustCrypto/elliptic-curves/pull/660
=> k256 v0.11.6

.github/dependabot.yml
Add Dependabot configuration to automatically open PRs for outdated actions.
Inspired by https://github.com/RustCrypto/hashes/pull/410#issuecomment-1252658128.
=> add Dependabot configuration to keep GitHub Actions up to date

p256/src/ecdsa.rs, p384/src/ecdsa.rs
Add integration tests to verify the following scenarios:
- P-256 ECDSA signing/verification with SHA-384 (longer than field size)
- P-384 ECDSA signing/verification with SHA-256 (smaller than field size)
Verification scenarios use a test vector adopted from FIPS 186-4.
Signing scenarios use a key from RFC6979 test vector but the test signature is pre-calculated using ecdsa crate (with the following fix applied) and cross-verified using OpenSSL. Unfortunately there are no suitable test vector to test `DigestPrimitive::prehash_to_field_bytes` through `PrehashSigner`.
The tests added in p384 currently fails and a fix has been submitted separately at https://github.com/RustCrypto/signatures/pull/547
@tarcieri PTAL cc/ @aumetra
=> p256,p384: test larger and smaller prehash operation

.github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/k256.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/p521.yml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml
Adds an `alloc` feature to all crates which enables `elliptic-curve/alloc`.
When weak feature activation is MSRV-compatible, we can use it to enable the alloc feature of all dependencies.
=> Add `alloc` feature

Cargo.lock, Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, k256/src/arithmetic/scalar.rs, k256/src/ecdsa/normalize.rs, k256/src/ecdsa/recoverable.rs, k256/src/ecdsa/sign.rs, k256/src/schnorr.rs, k256/src/schnorr/sign.rs, k256/src/schnorr/verify.rs, p256/Cargo.toml, p256/src/arithmetic/scalar/blinded.rs, p256/src/ecdsa.rs, p384/Cargo.toml, p384/src/ecdsa.rs
This (unpublished) prerelease of the `ecdsa` crate impl's the prospective `signature` v2 API from: RustCrypto/traits#1141
=> Bump `ecdsa` crate to v0.15.0-pre

k256/src/arithmetic/hash2curve.rs, k256/src/arithmetic/scalar.rs
[FROST uses hash2field in the Scalar field](https://www.ietf.org/archive/id/draft-irtf-cfrg-frost-11.html#section-6.4-2.2.1). When [adding support for the secp256k1 curve](https://github.com/ZcashFoundation/frost/issues/19), I noticed that k256 does not support the required FromOkm to make that happen, while p256 does support it.
I did the obvious thing and copied the p256 implementation. Let me know if you'd like another approach.
=> k256: implement `FromOkm` for `Scalar`

p256/src/arithmetic.rs, p256/src/lib.rs, p384/src/arithmetic.rs, p384/src/lib.rs
Add a rustdoc note that the `arithmetic` feature must be enabled for types like `AffinePoint`, `NonZeroScalar`, and `ProjectivePoint`.
=> p256+p384: add `arithmetic` doc cfg

Cargo.lock, k256/Cargo.toml, k256/src/schnorr.rs, k256/src/schnorr/sign.rs, k256/src/schnorr/verify.rs
Adds the following trait impls:
- `(Randomized)PrehashSigner` for `schnorr::SigningKey`
- `KeypairRef` for `schnorr::SigningKey`
- `PrehashVerifier` for `schnorr::VerifyingKey`
=> k256: impl `Prehash*` and `KeypairRef` for Schnorr keys

k256/src/schnorr/sign.rs
Adds an accessor for the inner `NonZeroScalar` value that represents a Schnorr secret key.
=> k256: add `schnorr::SigningKey::as_nonzero_scalar`

p256/src/arithmetic.rs, p384/src/arithmetic.rs, primeorder/src/affine.rs, primeorder/src/lib.rs, primeorder/src/projective.rs
There's already a `PrimeCurve` marker trait defined by the `elliptic-curve` crate, so the name `PrimeOrderCurve` is confusing.
The trait defines the curve parameters, such as the coefficients of the curve equation and generator point, so `PrimeCurveParams` makes sense.
=> primeorder: rename `PrimeOrderCurve` => `PrimeCurveParams`

p256/src/arithmetic/hash2curve.rs
This updates the test vectors used in the hash2curve implementation of P-256 to the newest version of VOPRF: https://datatracker.ietf.org/doc/draft-irtf-cfrg-voprf/16/.
See https://github.com/RustCrypto/elliptic-curves/pull/599.
=> Update P-256 VOPRF test vectors

.github/workflows/workspace.yml, bp256/src/lib.rs, bp384/src/lib.rs, k256/src/arithmetic/hash2curve.rs, k256/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar/wide64.rs, k256/src/lib.rs, k256/src/schnorr.rs, k256/src/schnorr/signing.rs, k256/src/schnorr/verifying.rs, p256/src/arithmetic/scalar.rs, p256/src/lib.rs, p521/src/lib.rs, primeorder/src/projective.rs
Adopts the following lints across all crates:
#![warn(
clippy::mod_module_files,
clippy::unwrap_used,
missing_docs,
rust_2018_idioms,
unused_lifetimes,
unused_qualifications
)]
Also bumps the rustc version used for clippy to 1.66 and fixes all clippy errors under the new configuration.
=> Lint improvements

k256/src/schnorr/signing.rs, k256/src/schnorr/verifying.rs
Leverage various infallible conversions to eliminate the use of `unwrap()` and allow infallible conversions from `NonZeroScalar` to `SigningKey`.
=> k256: impl `From<NonZeroScalar>` for `schnorr::SigningKey`

k256/src/schnorr/signing.rs
Leverage infallible conversions to enable direct conversion from `k256::SecretKey` to `k256::schnorr::SigningKey`.
=> k256: impl `From<SecretKey>` for `schnorr::SigningKey`

Cargo.lock, k256/Cargo.toml, k256/benches/scalar.rs, k256/src/arithmetic.rs, k256/src/arithmetic/mul.rs, k256/src/ecdsa.rs, k256/src/lib.rs
This PR introduces a way to multiply a scalar by the generator by keeping precomputed lookup tables. It is exported as `mul_by_generator()` (and used in the signing code). It takes 40us compared to 86us for regular multiplication; signing takes 70us compared to 116us.
The precomputed table contains values for every second radix and takes ~30kb; if we calculated it for every radix it would take 60kb with the performance improvement of only ~3%, so I don't think it is worth it (the same choice was taken by https://github.com/dalek-cryptography/curve25519-dalek).
I am not sure how to speed up the verification, which relies on calculating `k1 * G + k2 * x`. Pre-calculating lookup tables for `G` in `lincomb` only speeds it up from 129us to 122us on my machine. Calculating `k1 * G` via …
=> Scalar multiplication by the generator

.github/workflows/k256.yml, k256/Cargo.toml, k256/src/arithmetic/mul.rs
This allows developers concerned with the resident size of the program to avoid the large `GEN_LOOKUP_TABLE` static.
=> k256: add `basepoint-tables` feature

k256/benches/scalar.rs, k256/src/arithmetic.rs, k256/src/arithmetic/mul.rs, k256/src/ecdsa.rs, k256/src/lib.rs
Makes `ProjectivePoint::mul_by_generator` an inherent static method instead of a free function.
This avoids the need to import it separately from `ProjectivePoint`.
=> k256: factor `mul_by_generator` into `ProjectivePoint`

k256/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
These are helpful when using the scalars in Shamir secret sharing with random (128 bit) participants.
I didn't touch the field.rs files, as then automatic method selection in the `multiplicative_generator` implementations fails - so there is potentially a danger of backwards incompat in p256+p384 which don't have `From<u32>`.
Personally, I'm only interested in `From<u128>` for `k256`.
=> Constructors for scalars from u128

.github/workflows/k256.yml, k256/Cargo.toml, k256/src/arithmetic/mul.rs
Instead this uses weak feature activation to enable `once_cell/std` when the `std` feature is enabled, which it is by default.
The `critical-section` feature can be used in cases where `std` is unavailable but `precomputed-tables` are desired.
=> k256: don't eagerly enable `once_cell`'s `critical-section` feature

bp256/src/lib.rs, bp256/src/r1.rs, bp256/src/r1/ecdsa.rs, bp256/src/t1.rs, bp256/src/t1/ecdsa.rs, bp384/src/lib.rs, bp384/src/r1.rs, bp384/src/r1/ecdsa.rs, bp384/src/t1.rs, bp384/src/t1/ecdsa.rs, k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, k256/src/ecdsa.rs, k256/src/lib.rs, p256/src/arithmetic.rs, p256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar/blinded.rs, p256/src/ecdsa.rs, p256/src/lib.rs, p384/src/arithmetic.rs, p384/src/arithmetic/scalar.rs, p384/src/ecdsa.rs, p384/src/lib.rs, p521/src/lib.rs, primeorder/src/affine.rs, primeorder/src/lib.rs
Replaces manual `cfg(doc(...))` annotations by automatically generating them instead using `doc_auto_cfg`.
=> Use `doc_auto_cfg`

Cargo.lock, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml
Release notes: https://github.com/RustCrypto/signatures/pull/620
=> Bump `ecdsa` dependency to v0.15

Cargo.lock, bp256/CHANGELOG.md, bp256/Cargo.toml
[#701]: https://github.com/RustCrypto/elliptic-curves/pull/701
[#713]: https://github.com/RustCrypto/elliptic-curves/pull/713
=> bp256 v0.5.0

Cargo.lock, bp384/CHANGELOG.md, bp384/Cargo.toml
[#701]: https://github.com/RustCrypto/elliptic-curves/pull/701
[#713]: https://github.com/RustCrypto/elliptic-curves/pull/713
=> bp384 v0.5.0

Cargo.lock, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, primeorder/CHANGELOG.md, primeorder/Cargo.toml
Initial stable release.
NOTE: other versions skipped to synchronize version numbers with `elliptic-curve`, `k256`, `p256`, and `p384`.
=> primeorder v0.12.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- Impl `FromOkm` for `Scalar` ([#673])
- Impl `Prehash*` and `KeypairRef` for Schnorr keys ([#689])
- `schnorr::SigningKey::as_nonzero_scalar` ([#690])
- Impl `From<NonZeroScalar>` for `schnorr::SigningKey` ([#703])
- Impl `From<SecretKey>` for `schnorr::SigningKey` ([#704])
- `precomputed-tables` feature ([#697], [#705], [#707])
- Constructors for scalars from `u128` ([#709])
- `ecdsa::recoverable` module; see documentation for replacements ([#675])
[#673]: https://github.com/RustCrypto/elliptic-curves/pull/673
[#675]: https://github.com/RustCrypto/elliptic-curves/pull/675
[#689]: …
=> k256 v0.12.0

Cargo.lock, bp256/LICENSE-MIT, bp384/LICENSE-MIT, k256/CHANGELOG.md, p256/CHANGELOG.md, p256/Cargo.toml, p256/LICENSE-MIT, primeorder/LICENSE-MIT
- 32-bit scalar backend ([#636])
- Constructors for `Scalar` from `u128` ([#709])
- Use generic curve arithmetic implementation from `primeorder` crate ([#631], [#716])
- Use `U256` as the inner type for `FieldElement` ([#634])
- Update P-256 VOPRF test vectors ([#693])
[#631]: https://github.com/RustCrypto/elliptic-curves/pull/631
[#634]: https://github.com/RustCrypto/elliptic-curves/pull/634
[#636]: https://github.com/RustCrypto/elliptic-curves/pull/636
[#693]: https://github.com/RustCrypto/elliptic-curves/pull/693
[#701]: https://github.com/RustCrypto/elliptic-curves/pull/701
[#709]: …
=> p256 v0.12.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml
- Constructors for `Scalar` from `u128` ([#709])
- Use generic curve arithmetic implementation from `primeorder` crate ([#631], [#716])
[#631]: https://github.com/RustCrypto/elliptic-curves/pull/631
[#701]: https://github.com/RustCrypto/elliptic-curves/pull/701
[#709]: https://github.com/RustCrypto/elliptic-curves/pull/709
[#713]: https://github.com/RustCrypto/elliptic-curves/pull/713
[#716]: https://github.com/RustCrypto/elliptic-curves/pull/716
=> p384 v0.12.0

Cargo.lock, primeorder/CHANGELOG.md, primeorder/Cargo.toml
- Impl `From/ToEncodedPoint` for `ProjectivePoint` ([#722])
[#722]: https://github.com/RustCrypto/elliptic-curves/pull/722
=> primeorder v0.12.1

p256/src/arithmetic.rs, p256/tests/projective.rs, p384/src/arithmetic.rs, p384/tests/projective.rs, primeorder/src/affine.rs, primeorder/src/equation_a.rs, primeorder/src/lib.rs, primeorder/src/projective.rs
Extracts a `Double` trait (which should probably go in `elliptic_curve::ops`) which allows for multiple overlapping impls based on specific properties of the curve's a-coefficient.
The previous inherent `double()` method is now gated on `equation_a::IsMinus3`.
=> primeorder: algorithm specialization using `equation_a::Is*` ZSTs

.github/workflows/p384.yml, p384/src/arithmetic.rs, p384/src/arithmetic/hash2curve.rs
Depends on https://github.com/RustCrypto/traits/pull/1024.
=> Implement `HashToScalar` for P-384

p384/src/arithmetic/hash2curve.rs
Unfortunately #600 will break master in just a moment, I'm assuming #732 or #730 broke it.
This fixes it.
=> Fix P-384 hash2curve implementation

Cargo.lock, Cargo.toml, k256/src/arithmetic/affine.rs, primeorder/src/affine.rs
Switches to the newly consolidated `AffineCoordinates` trait.
See RustCrypto/traits#1237
=> Use `AffineCoordinates` trait

Cargo.lock, k256/src/arithmetic/hash2curve.rs, p256/src/arithmetic/hash2curve.rs, p384/src/arithmetic/hash2curve.rs
Follow up to https://github.com/RustCrypto/traits/pull/1238.
Cc @tarcieri.
=> Update hash2curve implementations to new API

p256/src/arithmetic/field.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/macros.rs, p384/src/arithmetic/scalar.rs, primeorder/src/field.rs
This adds an internal `invert_unchecked` method to all field element types, which is `const fn`.
It's used to impl the `PrimeField` constants which are inversions of other constant values.
=> p256+p384: add `const fn` inversions for all field elements

k256/src/arithmetic/field.rs, k256/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
Adds tests for the `TWO_INV`, `ROOT_OF_UNITY`, and `ROOT_OF_UNITY_INV` constants, based on the tests generated via `ff_derive`.
Some of them are currently failing and have been annotated with `#[ignore]` and a TODO comment.
=> k256+p256+p384: add `PrimeField` constant tests

k256/src/arithmetic/field.rs, k256/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
=> Test MULTIPLICATIVE_GENERATOR^{t} mod m == ROOT_OF_UNITY

p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs, primeorder/src/dev.rs, primeorder/src/field.rs
Extracts the tests duplicated between the `FieldElement` and `Scalar` types of the `p256` and `p384` crates into a macro which writes them.
It currently adds tests for the associated constants but could be further expanded in the future.
=> primeorder: extract `impl_primefield_tests!` macro

Cargo.lock, Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml
Also bumps `ecdsa` to v0.16.0-pre.1
=> Bump `elliptic-curve` to v0.13.0-pre.5

bp256/README.md, bp384/README.md, p224/Cargo.toml, p224/README.md, p256/Cargo.toml, p256/README.md, p256/src/arithmetic.rs, p256/src/lib.rs, p384/Cargo.toml, p384/README.md, p384/src/arithmetic.rs, p384/src/lib.rs, p521/Cargo.toml, p521/README.md, primeorder/README.md
Previously the NIST curves were specified in FIPS 186-4: Digital Signature Standard.
NIST has just released a new document, SP 800-186, which splits the curve definitions out separate from the signature algorithm definitions:
https://csrc.nist.gov/publications/detail/sp/800-186/final
This updates previous references to FIPS 186-4 (that is, ones which don't relate to ECDSA) to use SP 800-186 instead.
=> Update references to NIST SP 800-186

k256/src/arithmetic/scalar.rs
Adapts the implementation originally contributed to the `p256` crate by @nickray to the `k256` crate.
Implementation is checked against the constant-time `Scalar::invert` using proptests (where `Scalar::invert` is in turn proptested against `num-bigint`).
It results in a ~9% ECDSA verification performance improvement according to our criterion benchmarks:
```
ecdsa/verify_prehashed  time:   [67.681 µs 67.734 µs 67.796 µs]
change: [-9.4013% -9.2055% -9.0011%] (p = 0.00 < 0.05)
Performance has improved.
```
=> k256: fast `invert_vartime` using Stein's algorithm

p224/src/arithmetic/field.rs
Previously `S` was miscomputed.
This updates it to 96, and recomputes `MULTIPLICATIVE_GENERATOR` and `DELTA` accordingly (using sage).
=> p224: update `PrimeField` constants for `FieldElement`

k256/src/ecdsa.rs
Uses the `SigningKey::sign_digest_recoverable` method
=> k256: simply ECDSA signature recovery example

k256/src/ecdsa.rs
Adds a test which signs a message using Keccak256 as the digest function, testing that the resulting signature matches the one produced by web3.js, as used in the ethers-rs test vectors.
After the signature has been produced, it recovers the `VerifyingKey` from the message digest and signature, testing that it's the correct `VerifyingKey`, and also testing that it successfully verifies the signature.
=> k256: add complete end-to-end Ethereum signature recovery test

p224/src/arithmetic/field.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/field.rs, primeorder/src/field.rs
- Renames `primeorder::impl_field_element` to `impl_mont_field_element` to reflect it supports a Montgomery internal representation.
- Removes an unused parameter on `impl_field_op` macro.
- Removes some unused code in `p521`'s field element module.
=> Field element macro cleanups

p224/src/arithmetic.rs, p224/src/lib.rs
Constants have been sourced from [NIST SP 800-186](https://csrc.nist.gov/publications/detail/sp/800-186/final) § 3.2.1.2: P-224.
=> p224: `CurveArithmetic` + `PrimeCurveParams`

Cargo.lock, p224/src/lib.rs, p521/Cargo.toml, p521/src/arithmetic.rs, p521/src/arithmetic/field.rs, p521/src/arithmetic/scalar.rs, p521/src/arithmetic/util.rs
Constants have been sourced from [NIST SP 800-186](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-186.pdf) § 3.2.1.5: P-521.
=> p521: `CurveArithmetic` + `PrimeCurveParams`

p224/src/arithmetic/field.rs, primeorder/src/field.rs
Adds an inversion implementation adapted from the addition chain generated by addchain:
https://github.com/mmcloughlin/addchain
It uses a sequence of 11 multiplications and 223 squarings.
=> p224: field inversion support

.github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/k256.yml, .github/workflows/p224.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/p521.yml, .github/workflows/primeorder.yml, Cargo.lock, Cargo.toml, README.md, bp256/Cargo.toml, bp256/README.md, bp384/Cargo.toml, bp384/README.md, k256/Cargo.toml, k256/README.md, p224/Cargo.toml, p224/README.md, p256/Cargo.toml, p256/README.md, p384/Cargo.toml, p384/README.md, p521/Cargo.toml, p521/README.md, primeorder/Cargo.toml, primeorder/README.md
Also bumps `ecdsa` to v0.16.0-rc.0
=> Bump `elliptic-curve` to v0.13.0-rc.0; MSRV 1.65

Cargo.lock, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml
=> Bump `elliptic-curve` dependency to v0.13

p256/tests/affine.rs, primeorder/src/affine.rs
The function `to_compact_encoded_point` should return a CtOption where is_some set to 0 if the AffinePoint is non-compactable.
The current implementation checks if the EncodedPoint from bytes decodes properly to determine compactability. However, the EncodedPoint will always decode just fine, even when a non-compactable point has been compacted. 
Instead, what needs to be checked is if the compacted point and the original affine points Y coordinates match.
=> fix compactabtility check

Cargo.lock, bp256/CHANGELOG.md, bp256/Cargo.toml
- Bump `ecdsa` to v0.16 ([#770])
[#770]: https://github.com/RustCrypto/elliptic-curves/pull/770
=> bp256 v0.6.0

Cargo.lock, bp256/CHANGELOG.md, bp384/CHANGELOG.md, bp384/Cargo.toml
- `FieldBytesEncoding` trait impls ([#732])
- Bump `ecdsa` to v0.16 ([#770])
[#732]: https://github.com/RustCrypto/elliptic-curves/pull/732
[#770]: https://github.com/RustCrypto/elliptic-curves/pull/770
=> bp384 v0.6.0

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- `FieldBytesEncoding` trait impls ([#732])
- Fast `invert_vartime` using Stein's algorithm ([#743])
- `serde` support for `schnorr` types ([#748])
- `AffineCoordinates` trait ([#734])
- Bump `ecdsa` to v0.16 ([#770])
[#732]: https://github.com/RustCrypto/elliptic-curves/pull/732
[#734]: https://github.com/RustCrypto/elliptic-curves/pull/734
[#743]: https://github.com/RustCrypto/elliptic-curves/pull/743
[#748]: https://github.com/RustCrypto/elliptic-curves/pull/748
[#770]: https://github.com/RustCrypto/elliptic-curves/pull/770
=> k256 v0.13.0

Cargo.lock, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/CHANGELOG.md, primeorder/Cargo.toml
- Support curves with any `a`-coefficient ([#728], [#729])
- `impl_primefield_tests!` macro ([#739])
- Use `AffineCoordinates` trait ([#734])
- Rename `impl_field_element!` to `impl_mont_field_element!` ([#762])
- Bump `ecdsa` to v0.16 ([#770])
[#728]: https://github.com/RustCrypto/elliptic-curves/pull/728
[#729]: https://github.com/RustCrypto/elliptic-curves/pull/729
[#734]: https://github.com/RustCrypto/elliptic-curves/pull/734
[#739]: https://github.com/RustCrypto/elliptic-curves/pull/739
[#762]: https://github.com/RustCrypto/elliptic-curves/pull/762
[#770]: https://github.com/RustCrypto/elliptic-curves/pull/770
=> primeorder v0.13.0

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml
- `PrimeField` constants/tests ([#730], [#737], [#738])
- `const fn` inversions for all field elements ([#736])
- `FieldBytesEncoding` trait impls ([#732])
- Update `hash2curve` implementations to new API ([#735])
- Impl `Invert` trait for `Scalar` types ([#741])
- Bump `ecdsa` dependency to v0.16 ([#770])
- Bump `primeorder` dependency to v0.13 ([#777])
- Point compactabtility check ([#772])
[#730]: https://github.com/RustCrypto/elliptic-curves/pull/730
[#732]: https://github.com/RustCrypto/elliptic-curves/pull/732
[#735]: https://github.com/RustCrypto/elliptic-curves/pull/735
[#736]: https://github.com/RustCrypto/elliptic-curves/pull/736
[#737]: https://github.com/RustCrypto/elliptic-curves/pull/737
[#738]: …
=> p256 v0.13.0

Cargo.lock, p384/CHANGELOG.md, p384/Cargo.toml
- `PrimeField` constants/tests ([#730], [#737], [#738])
- `const fn` inversions for all field elements ([#736])
- `FieldBytesEncoding` trait impls ([#732])
- Update `hash2curve` implementations to new API ([#735])
- Impl `Invert` trait for `Scalar` types ([#741])
- Bump `ecdsa` dependency to v0.16 ([#770])
- Bump `primeorder` dependency to v0.13 ([#777])
- Point compactabtility check ([#772])
[#730]: https://github.com/RustCrypto/elliptic-curves/pull/730
[#732]: https://github.com/RustCrypto/elliptic-curves/pull/732
[#735]: https://github.com/RustCrypto/elliptic-curves/pull/735
[#736]: https://github.com/RustCrypto/elliptic-curves/pull/736
[#737]: https://github.com/RustCrypto/elliptic-curves/pull/737
[#738]: …
=> p384 v0.13.0

p224/src/arithmetic/field.rs, p384/src/arithmetic/field.rs, primeorder/src/field.rs
Uses an implementation generated by `ff_derive` using the following parameters:
```rust
#[derive(PrimeField)]
#[PrimeFieldModulus = "26959946667150639794667015087019630673557916260026308143510066298881"]
#[PrimeFieldGenerator = "22"]
```
=> p224: impl `FieldElement::sqrt`

.github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/k256.yml, .github/workflows/p224.yml, .github/workflows/p256.yml, .github/workflows/p384.yml, .github/workflows/p521.yml, .github/workflows/primeorder.yml, .github/workflows/security-audit.yml, .github/workflows/workspace.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/elliptic-curves/actions/runs/4409300910:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct …
=> Replace unmaintained actions-rs/* actions in CI workflows

p224/src/arithmetic/field.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs
Updates the `Debug` impls on `FieldElement` and `Scalar` to print the inner bigint value as hex.
=> p224/p256/p384: better `Debug` for field elements

p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml
It's not needed when the `arithmetic` feature is disabled
=> p224/p256/p384: make `primeorder` dependency optional

p256/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs, primeorder/src/field.rs
Changes the test to only check that sqrt round trips back when squared.
Closes #789
=> primeorder: simplified `impl_field_sqrt_tests!`

primeorder/src/point_arithmetic.rs
Reorders the impls so they match the ordering in the paper, which makes it easier to compare the paper to the Rust code.
=> primeorder: reorder `PointArithmetic` impls

Cargo.lock, p256/tests/ecdsa.rs
Also bumps `ecdsa` to v0.16.4, which contains a bugfix: RustCrypto/signatures#702
This test confirms it's fixed.
=> p256: ECDSA verifying key recovery test

Cargo.lock, p224/Cargo.toml, p224/src/ecdh.rs, p224/src/lib.rs, p256/src/ecdh.rs
Adds a feature for performing elliptic curve Diffie-Hellman similar to the same feature in the `p256` and `p384` crates.
=> p224: add `ecdh` feature

.github/workflows/p224.yml, p224/Cargo.toml, p224/src/lib.rs, p224/tests/projective.rs
Now that #813 has landed it seems prudent to add a real `arithmetic` feature.
This adds a feature similar to the `p256` and `p384` crates which exposes the following types which provide a curve arithmetic implementation:
- `AffinePoint`
- `ProjectivePoint`
- `Scalar`
The `wip-arithmetic-do-not-use` feature is now removed as well. While technically SemVer breaking, it wasn't supposed to be used in the first place!
=> p224: `arithmetic` feature

Cargo.lock, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/CHANGELOG.md, primeorder/Cargo.toml
- `impl_bernstein_yang_invert!` macro ([#786])
- `impl_field_invert_tests!` macro ([#786])
- `impl_field_identity_tests!` macro ([#790])
- `impl_field_sqrt_tests!` macro ([#790], [#800])
- Correct product definition for empty iterators ([#802])
[#786]: https://github.com/RustCrypto/elliptic-curves/pull/786
[#790]: https://github.com/RustCrypto/elliptic-curves/pull/790
[#800]: https://github.com/RustCrypto/elliptic-curves/pull/800
[#802]: https://github.com/RustCrypto/elliptic-curves/pull/802
=> primeorder v0.13.1

Cargo.lock, p224/CHANGELOG.md, p224/Cargo.toml, primeorder/README.md, primeorder/src/dev.rs, primeorder/src/lib.rs
- Projective arithmetic tests ([#813])
- `ecdh` feature ([#814])
- `arithmetic` feature ([#815])
- `ecdsa` feature ([#816])
- FIPS 186-4 ECDSA test vectors ([#817])
- Wycheproof test vectors ([#818])
- Bump `primeorder` to v0.13.1 ([#819])
- Better `Debug` for field elements ([#798])
- Make `primeorder` dependency optional ([#799])
[#798]: https://github.com/RustCrypto/elliptic-curves/pull/798
[#799]: https://github.com/RustCrypto/elliptic-curves/pull/799
[#813]: https://github.com/RustCrypto/elliptic-curves/pull/813
[#814]: https://github.com/RustCrypto/elliptic-curves/pull/814
[#815]: https://github.com/RustCrypto/elliptic-curves/pull/815
[#816]: https://github.com/RustCrypto/elliptic-curves/pull/816
[#817]: https://github.com/RustCrypto/elliptic-curves/pull/817
[#818]: …
=> p224 v0.13.1

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- Correct product definition for empty iterators ([#802])
[#802]: https://github.com/RustCrypto/elliptic-curves/pull/802
=> k256 v0.13.1

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml
- Bump `primeorder` to v0.13.1 ([#819])
- Correct product definition for empty iterators ([#802])
[#802]: https://github.com/RustCrypto/elliptic-curves/pull/802
[#819]: https://github.com/RustCrypto/elliptic-curves/pull/819
=> p256 v0.13.1

p192/src/arithmetic/field.rs
```sage
sage: p = 0xfffffffffffffffffffffffffffffffeffffffffffffffff
11
'111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111101111111111111111111111111111111111111111111111111111111111111110'
sage: s
1
sage: hex(t)
'0x7fffffffffffffffffffffffffffffff7fffffffffffffff'
sage: hex(root_of_unity) …
```
=> p192: define `PrimeField` constants for `FieldElement`

p192/src/arithmetic/scalar.rs
```sage
sage: p = 0xffffffffffffffffffffffff99def836146bc9b1b4d22831
3
'111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111100110011101111011111000001101100001010001101011110010011011000110110100110100100010100000110000'
sage: s
4
sage: hex(t)
'0xffffffffffffffffffffffff99def836146bc9b1b4d2283'
sage: hex(root_of_unity) …
```
=> p192: define `PrimeField` constants for `Scalar`

p256/Cargo.toml
=> p256: enable `pem` feature by default

sm2/src/arithmetic.rs, sm2/src/arithmetic/scalar.rs, sm2/src/lib.rs
Constants have been sourced from draft-shen-sm2-ecdsa Appendix D.
=> sm2: `CurveArithmetic` + `PrimeCurveParams`

.github/workflows/p192.yml, p192/Cargo.toml, p192/src/arithmetic.rs, p192/src/lib.rs, p192/tests/projective.rs
Now that #837 has landed it seems prudent to add a real `arithmetic` feature.
This adds a feature similar to the `p224`/`p256`/`p384` crates which exposes the following types which provide a curve arithmetic implementation:
- `AffinePoint`
- `ProjectivePoint`
- `Scalar`
=> p192: `arithmetic` feature

.github/workflows/sm2.yml, sm2/Cargo.toml, sm2/src/lib.rs, sm2/tests/pkcs8.rs
This adds a feature similar to the `p224`/`p256`/`p384` crates which exposes the following types which provide a curve arithmetic implementation:
- `AffinePoint`
- `ProjectivePoint`
- `Scalar`
=> sm2: `arithmetic` feature

Cargo.lock, p192/Cargo.toml, p192/src/ecdsa.rs, p192/src/lib.rs, p192/src/test_vectors.rs, p192/src/test_vectors/ecdsa.rs
Add ECDSA support for P-192, tests not implemented yet due to lacking signer support in P-192 and also requirement to use `PrehashSigner::sign_prehash()` since `ecdsa` crate currently only supports sha2 hashing algorithms for signing
=> p192: add `ecdsa` feature

p192/README.md, p192/src/ecdsa.rs
Add documentation referring to NIST Special Publication 800-131A Revision 2: Transitioning the Use of Cryptographic Algorithms and Key Lengths, which notes that the `p192` crate follows its recommendations to only implement public key operations as opposed to secret key ops.
=> p192: public key-only documentation

Cargo.lock, sm2/Cargo.toml, sm2/README.md, sm2/src/arithmetic/field.rs, sm2/src/arithmetic/scalar.rs, sm2/src/dsa.rs, sm2/src/dsa/signing.rs, sm2/src/dsa/verifying.rs, sm2/src/lib.rs, sm2/tests/sm2dsa.rs
Implements SM2DSA, a digital signature algorithm specified in GBT.32918.2-2016 as well as draft-shen-sm2-ecdsa.
The implementation draws a lot of inspiration from the `ecdsa` crate, including the use of RFC6979 for deriving the ephemeral scalar `k`.
Tested against a signature test vector created using OpenSSL 3.0.8 using the PKCS#8 example keys which were added in #848.
=> sm2: add `dsa` feature

Cargo.lock, p224/CHANGELOG.md, p224/Cargo.toml, p224/src/arithmetic/scalar.rs
- Enable `arithmetic` and `ecdsa` by default ([#833])
- Have `serde` feature enable `primeorder/serde` ([#851])
[#833]: https://github.com/RustCrypto/elliptic-curves/pull/833
[#851]: https://github.com/RustCrypto/elliptic-curves/pull/851
=> p224 v0.13.2

sm2/Cargo.toml
It's currently the main use case for this crate
=> sm2: enable `dsa` feature by default

Cargo.lock, p256/CHANGELOG.md, p256/Cargo.toml
- Enable `pem` feature by default ([#832])
- Have `serde` feature enable `primeorder/serde` ([#851])
[#832]: https://github.com/RustCrypto/elliptic-curves/pull/832
[#851]: https://github.com/RustCrypto/elliptic-curves/pull/851
=> p256 v0.13.2

Cargo.lock, sm2/CHANGELOG.md, sm2/Cargo.toml
- Enable `dsa` feature by default ([#862])
[#862]: https://github.com/RustCrypto/elliptic-curves/pull/862
=> sm2 v0.13.1

sm2/src/distid.rs, sm2/src/dsa.rs, sm2/src/dsa/signing.rs, sm2/src/dsa/verifying.rs, sm2/src/lib.rs
This code is reusable across all of the SM2 algorithms.
This commit decouples it from the SM2DSA implementation.
=> sm2: factor out `distid` module

Cargo.lock, sm2/CHANGELOG.md, sm2/Cargo.toml
- Factor out `distid` module ([#865])
[#865]: https://github.com/RustCrypto/elliptic-curves/pull/865
=> sm2 v0.13.2

bp256/src/arithmetic/field.rs
```sage
sage: p = 0xa9fb57dba1eea9bc3e660a909d838d726e3bf623d52620282013481d1f6e5377
sage: s = len(p_minus_1_bin) - len(p_minus_1_bin.rstrip('0')) # count trailing zeros in binary sage: t = (p - 1) >> s
11
'1010100111111011010101111101101110100001111011101010100110111100001111100110011000001010100100001001110110000011100011010111001001101110001110111111011000100011110101010010011000100000001010000010000000010011010010000001110100011111011011100101001101110110'
sage: s
1
sage: hex(t) …
```
=> bp256: define `PrimeField` constants for `FieldElement`

bp256/src/arithmetic/scalar.rs
```sage
sage: p = 0xa9fb57dba1eea9bc3e660a909d838d718c397aa3b561a6f7901e0e82974856a7
3
'1010100111111011010101111101101110100001111011101010100110111100001111100110011000001010100100001001110110000011100011010111000110001100001110010111101010100011101101010110000110100110111101111001000000011110000011101000001010010111010010000101011010100110'
sage: s
1
sage: hex(t) …
```
=> bp256: define `PrimeField` constants for `Scalar`

bp256/src/arithmetic/field.rs, bp384/src/arithmetic/field.rs
```sage
sage: p = 0x8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b412b1da197fb71123acd3a729901d1a71874700133107ec53
3
'10001100101110010001111010000010101000110011100001101101001010000000111101011101011011110111111001010000111001100100000111011111000101010010111101110001000010011110110101010100010101101011010000010010101100011101101000011001011111111011011100010001001000111010110011010011 …
```
=> bp384: define `PrimeField` constants for `FieldElement`

bp384/src/arithmetic/scalar.rs
```sage
sage: p = 0x8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b31f166e6cac0425a7cf3ab6af6b7fc3103b883202e9046565
2
'10001100101110010001111010000010101000110011100001101101001010000000111101011101011011110111111001010000111001100100000111011111000101010010111101110001000010011110110101010100010101101011001100011111000101100110111001101100101011000000010000100101101001111100111100111010 …
```
=> bp384: define `PrimeField` constants for `Scalar`

bp256/src/arithmetic/scalar.rs, bp256/src/lib.rs, bp256/src/r1.rs, bp256/src/r1/arithmetic.rs, bp256/src/t1.rs, bp256/src/t1/arithmetic.rs
Impls have been added for both `Brainpool256r1` and `Brainpool256t1`, which use different curve equation coefficients and generators, but share the base and scalar field implementations.
=> bp256: `CurveArithmetic` + `PrimeCurveParams`

bp384/src/arithmetic/scalar.rs, bp384/src/lib.rs, bp384/src/r1.rs, bp384/src/r1/arithmetic.rs, bp384/src/t1.rs, bp384/src/t1/arithmetic.rs
Impls have been added for both `Brainpool384r1` and `Brainpool384t1`, which use different curve equation coefficients and generators, but share the base and scalar field implementations.
=> bp384: `CurveArithmetic` + `PrimeCurveParams`

.github/workflows/bp256.yml, .github/workflows/bp384.yml, README.md, bp256/Cargo.toml, bp256/src/lib.rs, bp256/src/r1.rs, bp256/src/t1.rs, bp384/Cargo.toml, bp384/src/lib.rs, bp384/src/r1.rs, bp384/src/t1.rs
This reverts commit 7e35ecb9f9db8d2e1704ba19a246071f4235a37f.
ECDH is failing. Not ready for this yet.
=> Revert "bp256/bp384: `arithmetic` feature (#878)"

primeorder/src/affine.rs
If you already have the uncompressed point, it's faster to just check the x and y against the curve's equation than solving the equation and calculating the modular square root of y².
In my very rough benchmarks, doing 200k ECDH operations with the same P224 uncompressed key, the time went from ~76s to ~38s, a 2x speedup!
=> primeorder: improve initialization from uncompressed point

Cargo.lock, primeorder/CHANGELOG.md, primeorder/Cargo.toml
- Improve decoding performance for uncompressed SEC1 points ([#891])
[#891]: https://github.com/RustCrypto/elliptic-curves/pull/891
=> primeorder v0.13.2

Cargo.lock, bign256/CHANGELOG.md, bign256/Cargo.toml
Initial release (other versions skipped to synchronize with `elliptic-curve`/`ff`/`group`)
=> bign256 v0.13.0

Cargo.lock, k256/Cargo.toml, k256/src/ecdsa.rs
Uses `ecdsa::hazmat::sign_prehashed` which provides a generic implementation of ECDSA signing, which was introduced in https://github.com/RustCrypto/signatures/pull/731 and released in `ecdsa` v0.16.8.
The code is largely identical to what was previously used, that code having originally been copied from `p256` and updated iteratively to match the generic implementation in the `ecdsa` crate as it evolved.
The only reason why we can't use the default implementation of `SignPrimitive::try_sign_prehashed` is to handle low-S normalization, which is unique to the secp256k1 ecosystem but nearly ubiquitous and very much expected of ECDSA/secp256k1 implementations.
In the next release this can hopefully be upstreamed to the `ecdsa` crate as well, which would eliminate the need for the …
=> k256: use generic signing implementation from `ecdsa`

k256/src/ecdsa.rs
=> k256: reject signatures which aren't low-S normalized

k256/src/schnorr/verifying.rs
=> k256: check for R being the identity point on Schnorr verification

k256/src/arithmetic/scalar/wide32.rs, k256/src/arithmetic/scalar/wide64.rs
- use `overflowing_add()` instead of the explicit `ct_less()`. Seems to compile to the same assembly code. 
- use checked addition (the default for arithmetic operations) instead of an explicit `debug_assert()`
I am 99% sure that `overflowing_add()` will compile to the same (or safer) assembly... On the weird architectures where there's no `adc` or an equivalent (are there any even?), `<` may very easily not be constant-time too.
=> k256: simplify internal helper functions in the scalar arithmetic

k256/README.md
Renames and updates the "Security Notes" section to include some basic information about the audit.
I will file RustSec advisories for these and update again with links to security advisories for them.
=> k256: link to NCC audit in README.md

k256/src/ecdh.rs
Copy/paste where NIST P-256 wasn't changed to secp256k1
=> k256: fix comment

k256/src/arithmetic/field.rs, k256/src/arithmetic/field/field_10x26.rs, k256/src/arithmetic/field/field_5x52.rs, k256/src/arithmetic/field/field_impl.rs, p256/src/arithmetic/field.rs, primeorder/src/affine.rs, primeorder/src/projective.rs
This seems to help situations where the Rust compiler otherwise will not completely inline conditional_select, causing algoritms which depend on this to become significantly slower than they would otherwise.
See #940 for discussion.
=> Add inline annotations on conditional_select in p256, k256, and primeorder

p521/src/arithmetic/field.rs, p521/src/arithmetic/util.rs
Introduces a function to converts the `U576` into a little endian byte array in constant time and uses it for `from_uint_unchecked`.
Tests:
- Verified that math on generator such as doubling the point etc returns the expected outputs.
=> p521: Use unsaturated limbs

p521/src/arithmetic/field.rs, p521/src/arithmetic/util.rs
See also: #947
Also relevant (sage calculations):
- PR for base field constants: #758
- PR for scalar field constants: #760
=> p521: impl `FieldElement::{sqrt, invert}` and add basic field tests

p521/src/arithmetic/field.rs
- sqn: Has an extra copy
- sqrt: Can have simplified math
@tarcieri
=> p521: Improve field arithmetic

Cargo.lock, p521/Cargo.toml, p521/src/arithmetic/field.rs
When using p521, the limbs can be populated differently which when deriving [`Debug`] shows up as different values for equal FieldElements, this can lead to confusion.
See:
- https://github.com/RustCrypto/elliptic-curves/pull/946#issuecomment-1789749836, equal field elements were considered as unequal.
- https://github.com/RustCrypto/elliptic-curves/pull/946#discussion_r1380388316, assert_eq! wasn't meaningful.
=> p521: Improve `Debug` for unsaturated math

p521/Cargo.toml, p521/tests/projective.rs, primeorder/src/dev.rs, primeorder/src/lib.rs
The tests added in #950 weren't actually running due to feature gating (the feature is named `wip-arithmetic-do-not-use`, but the conditional gating was using `arithmetic` instead).
It turns out a small modification to `primeorder` was needed, since the `impl_projective_arithmetic_tests` macro was relying on `Into` conversions from core arrays to `GenericArray` which top out at 64-element arrays, and `p521`'s field elements are 66-bytes.
With the modification in place, the tests pass!
=> p521: fix projective arithmetic tests

Cargo.lock, p521/Cargo.toml, primeorder/CHANGELOG.md, primeorder/Cargo.toml
- Inline annotations on `conditional_select` ([#942])
- Support field elements larger than 64-bytes in `impl_projective_arithmetic_tests!` ([#951])
[#942]: https://github.com/RustCrypto/elliptic-curves/pull/942
[#951]: https://github.com/RustCrypto/elliptic-curves/pull/951
=> primeorder v0.13.3

p521/Cargo.toml, p521/src/lib.rs, p521/tests/projective.rs
Now that #946, #950, and #951 have landed it seems prudent to add a real `arithmetic` feature.
This adds a feature similar to the other crates in this repo which exposes the following types which provide a curve arithmetic implementation:
- `AffinePoint`
- `ProjectivePoint`
- `Scalar`
The `wip-arithmetic-do-not-use` feature is now removed as well. While technically SemVer breaking, it wasn't supposed to be used in the first place!
Closes #947
=> p521: `arithmetic` feature

k256/src/arithmetic.rs, k256/src/arithmetic/mul.rs, k256/src/lib.rs
=> k256: rename `lincomb_generic` to `lincomb` and expose it.

Cargo.lock, p521/CHANGELOG.md, p521/Cargo.toml, p521/src/arithmetic/field.rs
- Bernstein-Yang scalar inversions ([#786])
- VOPRF support ([#924])
- `arithmetic` feature ([#953])
- `ecdh` feature ([#954])
- `ecdsa` feature ([#956])
[#786]: https://github.com/RustCrypto/elliptic-curves/pull/786
[#924]: https://github.com/RustCrypto/elliptic-curves/pull/924
[#953]: https://github.com/RustCrypto/elliptic-curves/pull/953
[#954]: https://github.com/RustCrypto/elliptic-curves/pull/954
[#956]: https://github.com/RustCrypto/elliptic-curves/pull/956
=> p521 v0.13.1

p521/src/lib.rs, p521/tests/projective.rs
The relevant types from the `arithmetic` module are available via re-exports, so direct access to the module is unnecessary. It was accidentally exposed in the v0.13.1 release (#958).
Exposing the module directly is inconsistent with p192/p224/p256/p384, so this removes it. This is technically a breaking change, but it was added in v0.13.1 which was released a few minutes ago, and will be yanked after this is released.
=> p521: remove `pub` from `arithmetic` module

Cargo.lock, p521/CHANGELOG.md, p521/Cargo.toml, p521/README.md, primeorder/README.md
- `serde` feature ([#962])
- Remove `pub` from `arithmetic` module ([#961])
[#961]: https://github.com/RustCrypto/elliptic-curves/pull/961
[#962]: https://github.com/RustCrypto/elliptic-curves/pull/962
=> p521 v0.13.2

p521/src/arithmetic/field.rs, p521/src/arithmetic/util.rs
Some `debug_assert!`s were getting triggered on inputs that need to be handled without panicking.
Fixes #965
cc @MasterAwesome
=> p521: fix panics when decoding `FieldElement`s

Cargo.lock, clippy.toml, p256/src/arithmetic/hash2curve.rs, p384/src/arithmetic/hash2curve.rs, p521/Cargo.toml, p521/src/arithmetic.rs, p521/src/arithmetic/field.rs, p521/src/arithmetic/hash2curve.rs
This implements the hash-to-curve proposal for P521.
I went ahead and updated the OPRF test vectors as well.
Additionally I added a test that makes sure that the constants we calculated by hand are correct and simplified them, which is now possible because of all the added const methods.
See #503 and #600 for previous implementations.
=> p521: implement hash2curve

Cargo.lock, p521/CHANGELOG.md, p521/Cargo.toml
- Implement hash2curve ([#964])
- Panics when decoding `FieldElement`s ([#967])
[#964]: https://github.com/RustCrypto/elliptic-curves/pull/964
[#967]: https://github.com/RustCrypto/elliptic-curves/pull/967
=> p521 v0.13.3

p521/src/arithmetic/field.rs, p521/src/arithmetic/util.rs
Moves `u576_to_le_bytes` from the `util` module to inside of `from_uint_unchecked`.
The old function in the `util` module was not general-purpose, but really specialized to the case of decoding P-521 base field elements in the unsaturated format used by fiat-crypto's Solinas prime backend.
Additionally `FieldElement::from_uint_unchecked` is the only caller, and it really is an implementation detail of that function.
=> p521: merge `u576_to_le_bytes` into `FieldBytes::from_uint_unchecked`

p521/src/arithmetic/field.rs
It has extra unnecessary zeros to allow decoding as a U576 which are undesirable in a string representation.
=> p521: get rid of private `MODULUS_HEX` constant

Cargo.lock, Cargo.toml, k256/src/arithmetic/mul.rs, k256/src/arithmetic/projective.rs, k256/src/lib.rs, primeorder/src/projective.rs
Adds a generic implementation of `batch_normalize` which abstracts over backing storages.
This is just implemented in `k256` for now, but could potentially be further abstracted and extracted into `elliptic-curve`.
=> k256+primeorder: add `batch_normalize_generic`

k256/src/arithmetic/projective.rs, primeorder/src/projective.rs
Uses the generic function to impl `group::Curve::batch_normalize`
=> k256+primeorder: use `batch_normalize_generic` for trait impl

k256/src/arithmetic/projective.rs, primeorder/src/projective.rs
Uses constant-time selectors rather than branching
=> k256+primeorder: make `batch_normalize_generic` constant time

p521/src/arithmetic/field.rs, p521/src/arithmetic/field/loose.rs
The `FieldElement` type is available via the `FieldElement` associated type of the `primeorder::PrimeCurveArithmetic` trait, principally because it's the only way to make the generic implementation of curve arithmetic formulas work, however certain power users working on things like point encodings can also make use of it.
This type also has a set of `*_loose` operations which return an unreduced `LooseFieldElement`, however these were previously marked `allow(dead_code)`.
This commit makes those methods pub and marks `LooseFieldElement` as `pub` as well. It can't be directly named or imported, but perhaps someone can actually make use of the `*_loose` operations in 3rd party crates, since `p521` itself is not using them.
=> p521: make `LooseFieldElement` pub

Cargo.lock, Cargo.toml, k256/Cargo.toml, primeorder/Cargo.toml
This notably contains the `BatchInvert`, `BatchNormalize`, and `LinearCombinationExt` traits, which we previously got by sourcing the crate from the upstream git repo.
=> Bump `elliptic-curve` to v0.13.7

Cargo.lock, k256/CHANGELOG.md, k256/Cargo.toml
- `#[inline]` annotations on `conditional_select` ([#942])
- `BatchInvert` and `BatchNormalize` impls ([#971])
- Optimized implementation of `LinearCombinationExt` trait ([#974])
- Use generic signing implementation from `ecdsa` crate ([#911])
- Simplify internal helper functions in the scalar arithmetic ([#917])
- Bump `elliptic-curve` to v0.13.7 ([#979])
- Reject signatures which aren't low-`S` normalized ([#914])
- Check for `R` being the identity point on Schnorr verification ([#916])
[#911]: https://github.com/RustCrypto/elliptic-curves/pull/911
[#914]: https://github.com/RustCrypto/elliptic-curves/pull/914
[#916]: https://github.com/RustCrypto/elliptic-curves/pull/916
[#917]: https://github.com/RustCrypto/elliptic-curves/pull/917
[#942]: …
=> k256 v0.13.2

Cargo.lock, primeorder/CHANGELOG.md, primeorder/Cargo.toml
- `BatchInvert` and `BatchNormalize` impls ([#971])
- Bump `elliptic-curve` to v0.13.7 ([#979])
[#971]: https://github.com/RustCrypto/elliptic-curves/pull/971
[#979]: https://github.com/RustCrypto/elliptic-curves/pull/979
=> primeorder v0.13.4

.github/workflows/primeorder.yml, primeorder/Cargo.toml, primeorder/src/lib.rs, primeorder/src/projective.rs
There was previously code gated under `cfg(feature = "alloc")` but no `alloc` feature had actually been delcared.
This adds one and fixes some issues with the gated code.
=> primeorder: add `alloc` feature

Cargo.lock, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/CHANGELOG.md, primeorder/Cargo.toml
- `alloc` feature ([#982])
[#982]: https://github.com/RustCrypto/elliptic-curves/pull/982
=> primeorder v0.13.5

primeorder/CHANGELOG.md, primeorder/src/lib.rs, primeorder/src/projective.rs
...as an associated type of `PrimeCurveParams`. This was an accidental breaking change which broke the build for released crates:
https://github.com/RustCrypto/elliptic-curves/issues/984
=> primeorder: remove `Invert` bounds on `FieldElement`

Cargo.lock, primeorder/CHANGELOG.md, primeorder/Cargo.toml
-  `Invert` bounds on `FieldElement` ([#985])
[#985]: https://github.com/RustCrypto/elliptic-curves/pull/985
=> primeorder v0.13.6

sm2/Cargo.toml, sm2/src/dsa/signing.rs
Previously only RFC6979 deterministic signing was supported.
This commit adds trait impls for `RandomizedSigner` and `RandomizedPrehashSigner`. They still use RFC6979, but supplement the deterministic pseudorandomness with additional entropy supplied via a provided `CryptoRngCore`.
=> sm2: impl `Randomized*Signer` for `dsa::SigningKey`

p256/tests/pkcs8.rs
output without this patch:
```
$ cargo test --no-default-features --features pkcs8
Compiling p256 v0.13.2 (/home/capitol/project/elliptic-curves/p256)
error[E0433]: failed to resolve: could not find `PublicKey` in `p256`
--> p256/tests/pkcs8.rs:37:28
|
37 |     let public_key = p256::PublicKey::from_public_key_der(&PKCS8_PUBLIC_KEY_DER[..]).unwrap();
|                            ^^^^^^^^^ could not find `PublicKey` in `p256`
|
help: consider importing one of these items
|
5  + use elliptic_curve::PublicKey;
|
5  + use elliptic_curve::dev::PublicKey;
|
help: if you import `PublicKey`, refer to it directly
|
37 -     let public_key = p256::PublicKey::from_public_key_der(&PKCS8_PUBLIC_KEY_DER[..]).unwrap();
37 +     let public_key = …
```
=> fix test compilation errors if only the feature pkcs8 is enabled

k256/benches/ecdsa.rs, k256/benches/field.rs, k256/benches/scalar.rs, k256/src/arithmetic/affine.rs, k256/src/arithmetic/field.rs, k256/src/arithmetic/field/field_5x52.rs, k256/src/arithmetic/scalar.rs
If I add more `inline`s, the performance in most current benchmarks improves on my machine (AMD EPYC 7302). Benchmarks were run as `RUSTFLAGS='-C target-cpu=native' cargo bench --features expose-field`.
```
Running benches/ecdsa.rs
ecdsa/try_sign_prehashed
time:   [48.866 µs 48.901 µs 48.944 µs]
change: [-10.073% -8.5345% -6.8744%] (p = 0.00 < 0.05)
ecdsa/verify_prehashed  
time:   [103.95 µs 104.43 µs 105.00 µs]
change: [-12.366% -11.807% -11.312%] (p = 0.00 < 0.05)
Running benches/field.rs
field element operations/normalize_weak
time:   [3.1100 ns 3.1228 ns 3.1391 ns]
change: [-44.824% -44.193% -43.486%] (p = 0.00 < 0.05)
field element operations/normalize
time:   [10.600 ns 10.665 ns 10.757 ns]
change: [-25.955% -25.278% -24.669%] (p = 0.00 < 0.05)
field element operations/mul
time: …
```
=> add more inlines for better efficiency

primeorder/src/lib.rs, primeorder/src/projective.rs
This reverts commit 33af0a62bb83ed28dfca1266840b779a4136e4d1.
We can now make breaking changes again
=> Revert "primeorder: remove `Invert` bounds on `FieldElement` (#985)"

.github/workflows/primefield.yml, Cargo.lock, Cargo.toml, primefield/CHANGELOG.md, primefield/Cargo.toml, primefield/LICENSE-APACHE, primefield/LICENSE-MIT, primefield/README.md, primefield/src/lib.rs
Right now the `primeorder` crate, which contains elliptic curve addition formulas, is also curiously overloaded with some macros for generating field implementations, even though those have nothing in particular to do with the curve formulas.
This is largely because `primeorder` was an existing dependency of the other crates, so it was a convenient place to put it.
This begins the process of extracting it out into a separate crate. It should also make it easier to perform the `fiat-crypto` upgrade, since we can put the new implementation in `primefield` and leave the existing one in `primeorder` until all crates have been migrated.
=> primefield: crate boilerplate

Cargo.lock, Cargo.toml, p521/src/arithmetic/field.rs
Uses the newly added `const fn`-friendly version of `Uint::to_le_bytes`
=> p521: simplify `FieldElement::from_uint_unchecked`

Cargo.lock, Cargo.toml, k256/src/ecdsa.rs
It's now infallible and always returns a normalized signature regardless of if the original one was normalized or not:
https://github.com/RustCrypto/signatures/pull/780
=> k256: update `Signature::normalize_s` usages

Cargo.lock, p521/src/ecdsa.rs
Now that RustCrypto/signatures#773 and RustCrypto/signatures#774 have landed it should be possible to use the upstream RFC6979 implementation from the `ecdsa` crate in conjunction with `p521`, which uses a Digest with a 64-byte output, but uses 66-byte field elements.
This required some upstream changes to the `rfc6979` crate but is now working: https://github.com/RustCrypto/signatures/pull/781
=> p521: switch to upstream RFC6979-based ECDSA

Cargo.lock, Cargo.toml, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml, sm2/Cargo.toml
Also bumps `ecdsa` to v0.17.0-pre.3
=> Bump `elliptic-curve` to v0.14.0-pre.3

Cargo.lock, Cargo.toml, bp256/src/r1/ecdsa.rs, bp256/src/t1/ecdsa.rs, bp384/src/r1/ecdsa.rs, bp384/src/t1/ecdsa.rs, k256/src/ecdsa.rs, p192/src/ecdsa.rs, p224/src/ecdsa.rs, p256/src/ecdsa.rs, p384/src/ecdsa.rs, p521/src/ecdsa.rs
This is a marker trait added in RustCrypto/signatures#787 which marks an elliptic curve as being intended for use with ECDSA.
It's the intended successor of the `SignPrimitive` and `VerifyPrimitive` traits, carrying with it the one bit of information needed to eliminate the need for custom impls: a flag for low-S normalization.
`bp256`, `bp384`, `k256`, `p192`, `p224`, `p256`, `p384`, and `p521` have all received trait impls.
Of those, only `k256` has the `NORMALIZE_S` flag set to `true`.
=> Add `EcdsaCurve` trait impls

Cargo.lock, k256/benches/ecdsa.rs, k256/src/ecdsa.rs, p192/src/ecdsa.rs, p224/src/ecdsa.rs, p256/src/ecdsa.rs, p384/src/ecdsa.rs, p521/src/ecdsa.rs
These were removed upstream in RustCrypto/signatures#793.
The ECDSA implementation is fully generic now. These traits were originally for per-curve implementations, but those are no-longer needed.
The upstream implementation now has native support for low-S normalization by way of `EcdsaCurve::NORMALIZE_S`.
=> ecdsa: remove `SignPrimitive`/`VerifyPrimitive` traits

Cargo.lock, Cargo.toml, bign256/Cargo.toml, bign256/src/dsa/verifying.rs, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, k256/benches/scalar.rs, k256/src/arithmetic/mul.rs, k256/src/schnorr/verifying.rs, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml, primeorder/src/projective.rs, sm2/Cargo.toml, sm2/src/dsa/verifying.rs
Also bumps `ecdsa` to v0.17.0-pre.5
This includes upgrades to the new `LinearCombination` trait
=> Bump `elliptic-curve` to v0.14.0-pre.5

k256/src/arithmetic/projective.rs, primeorder/src/projective.rs
This PR fixes a bug in batch normalization, where non-normalized identity points would be misidentified, and therefore batch normalization would panic in `unwrap`ing a `None` batch inversion result.
See thread in https://github.com/RustCrypto/elliptic-curves/issues/943#issuecomment-1925992540.
@tarcieri
=> Batch Normalization `normalizes_to_zero()` bug fix

k256/src/schnorr.rs, k256/src/schnorr/signing.rs, k256/src/schnorr/verifying.rs
This was an extension to BIP340 that was introduced in 2022. The official [BIP340 test vectors](https://github.com/bitcoin/bips/blob/master/bip-0340/test-vectors.csv) do contain data for this case (tests 15-18) which are included here.
Fixes #1040
=> Add support for BIP340 signtures where the messages are not exactly 32 bytes

k256/src/arithmetic/field.rs, k256/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p521/src/arithmetic/field.rs, p521/src/arithmetic/scalar.rs, primefield/src/lib.rs, primeorder/src/field.rs
These started surfacing in recent rustc versions
=> Fix unused qualifications warnings

k256/src/schnorr.rs
If you pass a byte slice shorter than 32 bytes to Schnorr's Signature::try_from, it panics.
There is a unit test as first commit to test behaviour before and after the fix.
An easy fix would have been to check in `try_from` if the slice was shorted than `Self::BYTES / 2` but this patch makes it more similar to `bign256` and `sm2`.
=> Prevent panic when creating a Schnorr from slice

bign256/Cargo.toml, bign256/src/arithmetic/scalar.rs, bign256/src/lib.rs, bign256/tests/projective.rs, p521/src/arithmetic/scalar.rs, sm2/Cargo.toml, sm2/src/lib.rs
Some crates were defining features but not using them:
- bign256: `bits`, `serde`, `test-vectors`
- p521: `bits`
- sm2: `bits`
In fixing this, I also uncovered that bign256's test vectors are failing.
=> Fix missing features found by Rust 1.80

Cargo.lock, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml, sm2/Cargo.toml
Cuts prereleases of the following crates:
- `p256` v0.14.0-pre.1
- `p384` v0.14.0-pre.1
- `p521` v0.14.0-pre.1
- `primeorder` v0.14.0-pre.1
=> Cut pre.1 prereleases

Cargo.lock, Cargo.toml, bign256/Cargo.toml, bign256/src/secret_key.rs, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml, sm2/Cargo.toml
This bumps `elliptic-curve` dependency to `0.14.0-rc.0` which pulls `pkcs8` `0.11.0-rc.1`.
See https://github.com/RustCrypto/formats/pull/1483
=> fix pkcs8 api break

k256/README.md
Was getting a 404 with the old link to the NCC Audit for `k256`.
Discovered the new link and updated the README for you.
Also created an Internet Archive Snapshot: https://web.archive.org/web/20240920222655/https://www.nccgroup.com/us/research-blog/public-report-entropyrust-cryptography-review/
=> Update k256 NCC audit link in docs

.github/workflows/security-audit.yml
Also busts the cache as an attempt to fix compile errors
=> CI: use `rustsec/audit-check@v2`

p384/Cargo.toml
This default feature is inconsistent with all of the other curve implementations in this repo, which don't enable the `ecdh` feature by default.
We could go either way, enabling it in all the other curves, or just disabling it here. This PR opts to do the latter, as it's simpler.
Closes #1047
=> p384: remove default `ecdh` feature

primeorder/src/projective.rs
This probably won't affect actual curves much, but it is useful for test curves which have a small order, but the representation size still has to be large. See also https://github.com/RustCrypto/formats/pull/1649
=> primeorder: use `PrimeField::NUM_BITS` to bound the scalar size during point-scalar multiplication

k256/src/arithmetic/scalar.rs
We can make this work by reversing the caller relationship with `Field::try_from_rng` and having `generate_vartime` call that
=> k256: use `TryCryptoRng` for `generate_vartime`

Cargo.lock, Cargo.toml, bign256/src/ecdsa/signing.rs, k256/benches/scalar.rs, k256/src/arithmetic/mul.rs, k256/src/arithmetic/projective.rs, primeorder/src/projective.rs, sm2/src/dsa/signing.rs, sm2/src/pke/encrypting.rs
This is stacked on #1131
This depends on: 
- https://github.com/RustCrypto/traits/pull/1822
- https://github.com/RustCrypto/signatures/pull/940
=> Remove `MulByGenerator`

sm2/src/pke/decrypting.rs, sm2/src/pke/encrypting.rs
Running cargo clippy reports the following error.
```shell
warning: manually reimplementing `div_ceil`
--> sm2/src/pke/decrypting.rs:163:18
|
163 |     let c1_len = (q.bits() + 7) / 8 * 2 + 1;
|                  ^^^^^^^^^^^^^^^^^^ help: consider using `.div_ceil()`: `q.bits().div_ceil(8)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_div_ceil
= note: `#[warn(clippy::manual_div_ceil)]` on by default
warning: manually reimplementing `div_ceil`
--> sm2/src/pke/encrypting.rs:155:26
|
155 |     const N_BYTES: u32 = (Sm2::ORDER.bits() + 7) / 8;
|                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `.div_ceil()`: `Sm2::ORDER.bits().div_ceil(8)`
|
= help: for further information visit …
```
=> chore: fix cargo clippy warning

p256/src/arithmetic/field.rs, p256/src/arithmetic/field/field32.rs, p256/src/arithmetic/field/field64.rs, p256/src/arithmetic/hash2curve.rs
Previously `FieldElement` was used, however `MODULUS` itself is not a valid field element.
Originally suggested here: https://reports.zksecurity.xyz/reports/near-p256/#finding-mix-type
=> p256: use `U256` for `MODULUS` of `FieldElement`

p256/src/arithmetic/field.rs
The internal representation of `FieldElement` is Montgomery form, so it doesn't make sense for canonicalization to return a `FieldElement`, but rather an integer, i.e. `U256`.
Originally suggested in: https://reports.zksecurity.xyz/reports/near-p256/#finding-mix-type
=> p256: have `FieldElement::to_canonical` return `U256`

p256/src/arithmetic/scalar/scalar32.rs, p256/src/arithmetic/scalar/scalar64.rs
Based on the following Barrett reduction bound analysis:
https://reports.zksecurity.xyz/reports/near-p256/#analysis-of-the-bound-of-barrett-reduction
...the duplicate subtractions are unnecessary, and it was recommended to remove them:
https://reports.zksecurity.xyz/reports/near-p256/#finding-barrett-second-sub
This results in the following performance improvements:
scalar operations/mul   time:   [38.900 ns 38.957 ns 39.026 ns]
change: [-14.379% -14.052% -13.734%] (p = 0.00 < 0.05)
Performance has improved.
scalar operations/invert
time:   [20.716 µs 20.758 µs 20.823 µs]
change: [-14.817% -14.331% -13.969%] (p = 0.00 < 0.05)
Performance has improved.
=> p256: remove unnecessary sub in scalar Barrett reduction

bign256/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs, primefield/src/lib.rs
Updates `primefield::field_element_type` to add `shr` methods and trait impls, replacing the copy/pasted definition to one provided by the macro
=> primefield: add `shr` methods/trait impls to macro

Cargo.lock, bign256/src/arithmetic/field.rs, bign256/src/arithmetic/scalar.rs, bign256/src/ecdsa/signing.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs, primefield/Cargo.toml, primefield/src/fiat.rs, primefield/src/lib.rs
This commit removes the last pieces coupling `primefield` and `elliptic-curve`.
Since an elliptic curve is over a finite field, it doesn't make sense for the dependency to go the other way.
=> primefield: decouple from `elliptic-curve`

Cargo.lock, Cargo.toml, bign256/Cargo.toml, primefield/Cargo.toml, sm2/Cargo.toml
This pulls in a new release of `crypto-bigint` as well as bumping `signature` to v3 prereleases
=> Bump `elliptic-curve` crate dependency

.github/workflows/bp256.yml, .github/workflows/bp384.yml, README.md, bp256/Cargo.toml, bp256/src/lib.rs, bp256/src/r1.rs, bp256/src/t1.rs, bp384/Cargo.toml, bp384/src/lib.rs, bp384/src/r1.rs, bp384/src/t1.rs
Promotes the previous `wip-arithmetic-do-not-use` feature to a proper `arithmetic` feature.
The previous bugs were in the field implementation. The `bp*` crates now use the `primefield` crate to write their field implementations with macros as opposed to the previous copy/pasted code.
=> bp256+bp384: `arithmetic` feature

bign256/src/arithmetic/field.rs, bign256/src/arithmetic/scalar.rs, bp256/src/arithmetic/field.rs, bp256/src/arithmetic/scalar.rs, bp384/src/arithmetic/field.rs, bp384/src/arithmetic/scalar.rs, p192/src/arithmetic/field.rs, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/field.rs, p224/src/arithmetic/scalar.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/field.rs, p521/src/arithmetic/scalar.rs, primefield/src/lib.rs, sm2/src/arithmetic/field.rs, sm2/src/arithmetic/scalar.rs
Adds a macro which writes all of the currently provided macro-based tests for types which impl `PrimeField`.
=> primefield: add `test_primefield!` macro

bign256/src/arithmetic/scalar.rs, bp256/src/arithmetic/scalar.rs, bp384/src/arithmetic/scalar.rs, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs, primefield/src/lib.rs, sm2/src/arithmetic/scalar.rs
More boilerplate in the macro is less copy/paste
=> primefield: move more `From` impls into `field_element_type!`

primeorder/src/projective.rs
warning: `#[must_use]` has no effect when applied to a provided trait
method
--> primeorder/src/projective.rs:294:5
|
294 |     #[must_use]
|     ^^^^^^^^^^^
=> primeorder: remove unnecessary `must_use`

p256/Cargo.toml, p256/benches/field.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/field/field32.rs, p256/src/arithmetic/field/field64.rs, primefield/src/lib.rs
This represents an initial attempt to convert some of the functionality of `FieldElement` to using macros from the `primefield` crate.
Changes have been made carefully and minimally along with benchmarking to ensure this does not impact performance (unlike the last attempt to do this, see #885)
Trying to use the full `field_element_type!` did appear to result in a benchmark regression, so this instead extracts a
`field_element_type_core!` macro (again) and begins to use it in `p256`, ensuring that there are no benchmark regressions.
=> p256: begin using `primefield`

p256/src/arithmetic/scalar/scalar32.rs, p256/src/arithmetic/scalar/scalar64.rs
This results in a 15%-20% speedup:
scalar operations/invert
time:   [16.393 µs 16.500 µs 16.600 µs]
change: [-15.781% -15.313% -14.861%] (p = 0.00 < 0.05)
Performance has improved.
=> p256: inline inner functions of Barrett reduction

bign256/src/arithmetic/scalar.rs, bp256/src/r1/arithmetic.rs, bp256/src/t1/arithmetic.rs, bp384/src/r1/arithmetic.rs, bp384/src/t1/arithmetic.rs, k256/src/arithmetic/scalar.rs, p192/src/arithmetic/scalar.rs, p192/src/lib.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/scalar.rs, sm2/src/arithmetic/scalar.rs
This implements `From<NonZeroScalar>` for `Scalar`. Unfortunately this can't be implemented on `NonZeroScalar` directly because `elliptic_curve::Scalar` is just a type alias.
Companion PR: https://github.com/RustCrypto/traits/pull/1847.
=> Implement `From<NonZeroScalar>` for `Scalar`

k256/src/arithmetic/field.rs, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs, p521/src/arithmetic/field.rs, p521/src/arithmetic/scalar.rs
There were several new warnings of this nature:
```console
warning: `#[must_use]` has no effect when applied to a provided trait method
--> k256/src/arithmetic/scalar.rs:239:5
|
239 |     #[must_use]
|     ^^^^^^^^^^^
```
=> Fix warnings on Rust 1.87

k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, primeorder/src/affine.rs, primeorder/src/projective.rs
This is the equivalent of #1188 for `ProjectivePoint` and `AffinePoint`.
=> Implement `From<NonIdentity>` for `Projective/AffinePoint`

bign256/src/arithmetic/scalar.rs, bp256/src/arithmetic/scalar.rs, bp384/src/arithmetic/scalar.rs, k256/src/arithmetic/scalar.rs, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/scalar.rs, primefield/src/lib.rs, primeorder/src/affine.rs, primeorder/src/lib.rs, primeorder/src/macros.rs, primeorder/src/projective.rs, sm2/src/arithmetic/scalar.rs
Adds a macro which writes a series of `Mul` impls for `Scalar` types for both `AffinePoint` and `ProjectivePoint` as operands (and various combinations of references thereof).
See also: RustCrypto/traits#1854
=> primeorder: add `scalar_mul_impls!` macro

bign256/src/arithmetic/scalar.rs, bp256/src/r1/arithmetic.rs, bp256/src/t1/arithmetic.rs, bp384/src/r1/arithmetic.rs, bp384/src/t1/arithmetic.rs, k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, k256/src/arithmetic/scalar.rs, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/scalar.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/scalar.rs, primeorder/src/affine.rs, primeorder/src/projective.rs, sm2/src/arithmetic/scalar.rs
This implement `TryFrom<Scalar> for NonZeroScalar`, `TryFrom<ProjectivePoint> for NonIdentity<ProjectivePoint>` and `TryFrom<AffinePoint> for NonIdentity<AffinePoint>` in the same spirit as #1188 and #1190.
=> Implement `TryFrom<Scalar/Projective/AffinePoint>` for `NonIdentity/ZeroScalar`

bign256/tests/projective.rs, p192/tests/projective.rs, p224/tests/projective.rs, p256/tests/projective.rs, p384/tests/projective.rs, p521/tests/projective.rs, primeorder/src/dev.rs
It was previously the more verbose `impl_projective_arithmetic_tests!`.
This follows the convention in the `primefield` crate.
=> primeorder: rename `test_projective_arithmetic!` macro

Cargo.lock, k256/src/arithmetic/hash2curve.rs, p256/src/arithmetic/hash2curve.rs, p384/src/arithmetic/hash2curve.rs, p521/src/arithmetic/hash2curve.rs, primeorder/src/projective.rs
Updates to the changes introduced in https://github.com/RustCrypto/traits/pull/1866.
Requires https://github.com/RustCrypto/traits/pull/1866.
This removes the unnecessary implementations of `CofactorGroup`.
=> Update for MapToCurve changes

Cargo.lock, Cargo.toml, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml, sm2/Cargo.toml
Also bumps:
- `ecdsa` v0.17.0-rc.0
- `elliptic-curve` v0.14.0-rc.2
- `signature` v3.0.0-rc.0
=> Bump `digest` dependency to v0.11.0-rc.0

Cargo.lock, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primefield/Cargo.toml, primeorder/Cargo.toml, sm2/Cargo.toml
Also cuts releases of: `k256`, `p256`, `p384`, `p521`
=> primefield v0.14.0-pre.2

Cargo.toml, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, sm2/Cargo.toml
When pulling dependencies using a `patch.crates-io` to a git dependency (for unreleased crates or ...):
```
[dependencies]
p224 = "0.14.0-pre"
p256 = "0.14.0-pre.4"
[patch.crates-io]
p224 = { git = "https://github.com/RustCrypto/elliptic-curves.git" }
```
Cargo will duplicate the `primefield` and `primeorder` dependencies:
```
[[package]]
name = "p224"
version = "0.14.0-pre"
source = "git+https://github.com/RustCrypto/elliptic-curves.git#d0d84f5bcc0ed933d472548e3085f17fdea57f17"
dependencies = [
"ecdsa",
"elliptic-curve",
"primefield 0.14.0-pre.2 (git+https://github.com/RustCrypto/elliptic-curves.git)",
"primeorder 0.14.0-pre.3 (git+https://github.com/RustCrypto/elliptic-curves.git)",
"sha2",
]
[[package]]
name = "p256"
version = "0.14.0-pre.4"
source = …
```
=> workspace: avoid duplicates when pulling dependency from git

Cargo.lock, Cargo.toml, ed448-goldilocks/src/curve/edwards/affine.rs, ed448-goldilocks/src/decaf/affine.rs, ed448-goldilocks/src/field/scalar.rs, ed448-goldilocks/src/lib.rs, k256/src/arithmetic/affine.rs, primeorder/src/affine.rs
Companion PR to RustCrypto/traits#1891 which adds access to affine y-coordinates.
Notably we've just added an Edwards curve with `ed448-goldilocks`, and these curves use compressed Edwards y-coordinates, so y-coordinate access is needed to even implement point compression generically for these curves.
Note that due to RustCrypto/elliptic-curves#1229 it's currently not possible to impl the extened `AffineCoordinates API for the Decaf implementation in the `ed448-goldilocks` crate. This PR comments out the relevant code for now with a TODO to fix it.
=> Expose `AffineCoordinates::y`

ed448-goldilocks/Cargo.toml
The `jwk` and `sec1` features are unused
=> ed448-goldilocks: remove unused `elliptic-curve` features

ed448-goldilocks/Cargo.toml, ed448-goldilocks/src/field/scalar.rs, ed448-goldilocks/src/lib.rs
Makes `bits` an optional feature, since it pulls in `bitvec` as a dependency
=> ed448-goldilocks: `bits` feature

Cargo.lock, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, ed448-goldilocks/Cargo.toml, k256/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml, sm2/Cargo.toml
Also cuts prereleases of `k256`, `p256`, `p384`, and `p521`.
Closes #1238
=> primeorder v0.14.0-pre.4

ed448-goldilocks/README.md, ed448-goldilocks/src/lib.rs
- Moves all toplevel attributes to the top of file
- Includes README.md in the rustdoc
- Moves code example to README.md
- Switch all `deny` lints to `warn` since we deny warnings in CI
- Add `forbid(unsafe)` and remove unnecessary `unsafe impl`s (the traits are auto anyway)
=> ed448-goldilocks: cleanup toplevel attributes

Cargo.lock, ed448-goldilocks/Cargo.toml, ed448-goldilocks/src/curve/edwards/extended.rs, ed448-goldilocks/src/sign/signature.rs, ed448-goldilocks/src/sign/verifying_key.rs
Depends:
- https://github.com/RustCrypto/elliptic-curves/pull/1219
- https://github.com/RustCrypto/signatures/pull/983
This is a followup to #1219
=> ed448-goldilocks: reuse types from `ed448`

Cargo.lock, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, k256/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primeorder/Cargo.toml, sm2/Cargo.toml
Also cuts prereleases of `k256`, `p256`, `p384`, and `p521`
=> primeorder v0.14.0-pre.5

ed448-goldilocks/src/curve/edwards/extended.rs, ed448-goldilocks/src/decaf/ops.rs, ed448-goldilocks/src/decaf/points.rs, k256/src/arithmetic/projective.rs, primeorder/src/projective.rs
Follow-up to https://github.com/RustCrypto/traits/pull/1902.
Let me know if i went too broad with this.
=> Use `elliptic_curve::CurveGroup`

primefield/src/fiat.rs
The `d` value used to calculate the iteration count is meant to be the max of the bit size of the modulus and the number being inverted, which would just be the size of the modulus in this case. For a modulus of 254 bits in a 256-bit representation this was setting `d` to 256, which produced the wrong result.
=> primeorder: fix Bernstein-Yang inversion iteration count

primefield/src/lib.rs
This macro was a workaround for when it wasn't possible to use the `field_element_type!` macro for all fields we implement in this repo.
However, all crates now use `field_element_type!`, so we can (re)combine the two macros again.
=> primefield: remove `field_element_type_core!` macro

Cargo.lock, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml
Cuts prereleases of `k256`, `p256`, `p384`, and `p521`
=> Cut pre.8 prereleases

ed448-goldilocks/README.md, ed448-goldilocks/src/constants.rs, ed448-goldilocks/src/curve.rs, ed448-goldilocks/src/curve/edwards/affine.rs, ed448-goldilocks/src/curve/edwards/extended.rs, ed448-goldilocks/src/curve/montgomery.rs, ed448-goldilocks/src/curve/scalar.rs, ed448-goldilocks/src/curve/scalar_mul/double_and_add.rs, ed448-goldilocks/src/curve/scalar_mul/variable_base.rs, ed448-goldilocks/src/decaf.rs, ed448-goldilocks/src/decaf/affine.rs, ed448-goldilocks/src/decaf/ops.rs, ed448-goldilocks/src/decaf/points.rs, ed448-goldilocks/src/decaf/scalar.rs, ed448-goldilocks/src/field.rs, ed448-goldilocks/src/field/scalar.rs, ed448-goldilocks/src/lib.rs, ed448-goldilocks/src/macros.rs, ed448-goldilocks/src/sign.rs, ed448-goldilocks/src/sign/expanded.rs, ed448-goldilocks/src/sign/signing_key.rs, ed448-goldilocks/src/sign/verifying_key.rs
Because Ed448 and Decaf448 have different scalar representations, we need two separate types.
This PR achieves this by making `Scalar` generic and adding two new types:
- `type EdwardsScalar = Scalar<Ed448>`
- `type DecafScalar = Scalar<Decaf448>`
`Scalar` itself must still be publicly visible to allow its methods and implementations to show up in the documentation. A new private trait `CurveWithScalar` is introduced to let implementations differentiate between both curves. Because `Scalar<C: CurveWithScalar>` relies on this private trait `Scalar` can't be used by users with other curves.
Alternatively we could also achieve the same result with a huge macro instead of a shared generic `Scalar` type. Let me know if you prefer that instead.
Resolves #1229.
=> ed448-goldilocks: split `Scalar` into `EdwardsScalar`/`DecafScalar`

ed448-goldilocks/src/decaf.rs, ed448-goldilocks/src/field/element.rs
This PR adds the official hash2curve test vectors for Decaf448: https://www.rfc-editor.org/rfc/rfc9496#name-group-elements-from-uniform-.
~~As pointed out in #1282, this currently fails. I have confirmed that the same test vectors work with other libraries, e.g. [OPRF PoC](https://github.com/cfrg/draft-irtf-cfrg-voprf), [crrl](https://github.com/pornin/crrl) and [noble-curves](https://github.com/paulmillr/noble-curves).~~
I eventually figured out the correct implementation and fixed it.
Fixes #1282.
=> ed448-goldilocks: fix Decaf448 map2curve and add test vectors

ed448-goldilocks/README.md, ed448-goldilocks/src/curve/edwards/extended.rs, ed448-goldilocks/src/curve/scalar.rs, ed448-goldilocks/src/decaf/points.rs, ed448-goldilocks/src/decaf/scalar.rs, ed448-goldilocks/src/field/element.rs, ed448-goldilocks/src/field/scalar.rs, ed448-goldilocks/src/lib.rs
This implements `GroupDigest` for `Ed448` and `Decaf448` and removes the already existing standalone functions. Test vectors from the hash2curve specification were already in place.
I also added test vectors for `hash_to_scalar` from OPRF, like we already have in place for P-256, P-384 and P-521.
=> ed448-goldilocks: impl `GroupDigest` for `Ed448` and `Decaf448`

Cargo.lock, bign256/Cargo.toml, bp256/Cargo.toml, bp384/Cargo.toml, p192/Cargo.toml, p224/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml, primefield/Cargo.toml, primeorder/Cargo.toml, sm2/Cargo.toml
Releases the following:
- `primefield` v0.14.0-pre.4
- `primeorder` v0.14.0-pre.7
=> Cut `primefield` and `primeorder` rcs

Cargo.lock, k256/Cargo.toml, p256/Cargo.toml, p384/Cargo.toml, p521/Cargo.toml
Cuts prereleases of `k256`, `p256`, `p384`, and `p521`
=> Cut pre.9 prereleases

hash2curve/src/group_digest.rs, hash2curve/src/hash2field.rs, k256/src/arithmetic/hash2curve.rs, p256/src/arithmetic/hash2curve.rs, p384/src/arithmetic/hash2curve.rs, p521/src/arithmetic/hash2curve.rs
=> `hash2curve`: make `hash_to_field` output an array instead of taking an out parameter.

.github/workflows/workspace.yml, bign256/src/ecdsa.rs, ed448-goldilocks/src/edwards/extended.rs, ed448-goldilocks/src/field/scalar.rs, sm2/src/dsa.rs, sm2/tests/dsa_extended.rs, sm2/tests/pkcs8.rs
This is just to limit noise for the folks running a local rust version higher than the minimum 1.85 of the crate.
=> chore: fixup clippy 1.88 warnings

Cargo.lock, p521/src/arithmetic/scalar.rs, primefield/src/lib.rs
It was noted as buggy in #1319 because `shr` was being computed on values within the Montgomery domain directly. They either need to be converted to canonical form first, or a Montgomery multiplication needs to be used in place of a bit shift.
Turns out it was completely unused, aside from fulfilling a bound in the `elliptic-curve` crate, which has since been removed.
This removes `shr` support from all curves whose `Scalar` uses an internal Montgomery representation. It has been retained on `k256` and `p256` which use canonical form `Scalar` types.
Closes #1319
=> primefield: remove `shr` support

p256/src/arithmetic/field.rs
The macro tests the `PrimeField` constants, `invert`, `sqrt`, and other tests which were previously handwritten
=> p256: use `primefield::test_primefield` to test `FieldElement`

primefield/src/dev.rs, primefield/src/lib.rs
Moves all of the `test_*!` macros to the `dev` module
=> primefield: extract `dev` module

Cargo.lock, primefield/src/monty.rs
Uses the new safegcd impl, which has a better strategy for computing the upper bounds on the number of divstep operations.
It also has improved "bounds" in other ways, namely it's impl'd for all sizes and no longer needs to rely on the `PrecomputedInverter` trait or `SafeGcdInverter` type, even in `const fn` contexts.
=> primefield: update to safegcd-bounds

ed448-goldilocks/src/decaf/points.rs, ed448-goldilocks/src/edwards/extended.rs, k256/src/arithmetic/affine.rs, k256/src/arithmetic/projective.rs, primeorder/src/affine.rs, primeorder/src/projective.rs
This PR changes random point generation to use rejection sampling by de-serialization instead of deriving a point from a random scalar.
Fixes #1140.
=> Use rejection sampling for random point generation

ed448-goldilocks/src/decaf/points.rs, ed448-goldilocks/src/edwards/extended.rs
In #1333 I will remove this specific check from `AffinePoint::try_from_rng()`, which doesn't have the limitations of `Group::try_from_rng()`.
Fixes #1346.
=> `ed448-goldilocks`: reject identity points in `Group::try_from_rng()`

ed448-goldilocks/src/curve/twedwards.rs, ed448-goldilocks/src/curve/twedwards/extended.rs, ed448-goldilocks/src/edwards/extended.rs
=> `ed448-goldilocks`: optimize Edwards isogeny map further

Cargo.lock, primefield/src/monty.rs
Now that the bounds on inversion have been removed, we no longer need to use this directly
=> primefield: remove `ConstMontyFormInverter`

p256/tests/projective.rs, primeorder/src/projective.rs
This reverts commit 4d49ce68efbad966e9c042c8d4bab0a1ca398725.
Getting some very strange build failures, e.g.:
https://github.com/RustCrypto/elliptic-curves/actions/runs/16733154177/job/47365846705
It seems to be failing on 32-bit targets for any Rust version older than 1.88, seemingly with a nonsense type mismatch.
I was able to reproduce it locally with:
cargo build --target i686-unknown-linux-gnu
Very strange, almost seems like a compiler bug, especially since it seems magically fixed in Rust 1.88.
Also very confused why CI passed to begin with.
cc @daxpedda
=> Revert #1343: "`primeorder`: add optimized implementation for `LinearCombination`"

hash2curve/src/group_digest.rs, hash2curve/src/hash2field.rs, hash2curve/src/hash2field/expand_msg.rs, hash2curve/src/hash2field/expand_msg/xmd.rs, hash2curve/src/hash2field/expand_msg/xof.rs
Discussed in https://github.com/RustCrypto/elliptic-curves/issues/1295. This was planned as a follow up to https://github.com/RustCrypto/elliptic-curves/pull/1317, but I decided to make it as its own PR because #1317 is not unanimous.
Replaces `elliptic_curve::{Error, Result}` with an associated type on `ExpandMsg`.
=> `hash2curve`: Error rework

x448/src/lib.rs
=> x448: api fixups

ed448-goldilocks/README.md, ed448-goldilocks/src/edwards.rs, ed448-goldilocks/src/edwards/affine.rs, ed448-goldilocks/src/edwards/extended.rs, ed448-goldilocks/src/field/element.rs, ed448-goldilocks/src/sign.rs, ed448-goldilocks/src/sign/expanded.rs, ed448-goldilocks/src/sign/signing_key.rs, ed448-goldilocks/src/sign/verifying_key.rs
A bunch of functionality implemented on `EdwardsPoint` internally just converts to `AffinePoint`. This functionality should rather live in `AffinePoint`.
This PR also implement `BatchNormalize` for `EdwardsPoint`, which wouldn't have much of a point without these changes to begin with.
=> Move function requiring `AffinePoint` from `EdwardsPoint` to `AffinePoint`

ed448-goldilocks/src/field/element.rs
I didn't add this in #1302 because the performance was much worse. Now with the latest changes in crypto-bigint this isn't the case anymore. Instead the new `ConstMontyForm::invert()` improves the performance by 85% (on my PC).
=> Use `ConstMontyForm::invert()` in place of `pow()`

ed448-goldilocks/benches/bench.rs
Follow-up to https://github.com/RustCrypto/elliptic-curves/pull/1334.
=> Fix `ed448-goldilocks` Benchmark Suite

ed448-goldilocks/benches/bench.rs
After some real-world usage, I've noticed that we can cut down on some unnecessary benchmarks. 
Among a couple of other nits, the main thing here is that I removed `hash_to_curve()`, because `encode_to_curve()` + point addition already covers that.
Follow-up to #1334.
=> `ed448-goldilocks`: clean up benchmarks

ed448-goldilocks/src/curve/scalar_mul/window/wnaf.rs, ed448-goldilocks/src/curve/twedwards/projective.rs
This PR makes `ProjectiveNielsPoint::identity()` and associated constant `IDENTITY`.
This actually had quite the effect on Edwards scalar multiplication, it called the twisted-curve to Niel's form conversion 113 times during the operation which isn't being optimized away in release mode (with fat LTO, `codegen-units = 1` and such). So during each iteration this added 3 multiplications to the already 20 present, a flat 15% increase. Which approximately matches the benchmarks I've run.
Also affects Decaf scalar multiplication with #1303.
=> Make `ProjectiveNielsPoint::identity()` an associated constant

ed448-goldilocks/src/decaf/scalar.rs, ed448-goldilocks/src/edwards/extended.rs, ed448-goldilocks/src/edwards/scalar.rs, ed448-goldilocks/src/field/scalar.rs
Taking what I learned from https://github.com/dalek-cryptography/curve25519-dalek/pull/805 I applied this to `ed448-goldilocks` as well.
This is based on #1335 because the current check for torsion-freeness multiplies by the order, which breaks most proper assumptions made here.
=> `ed448-goldilocks`: account for oddness in Scalar divisions

ed448-goldilocks/src/decaf/scalar.rs, ed448-goldilocks/src/edwards/scalar.rs, ed448-goldilocks/src/field/element.rs, hash2curve/src/group_digest.rs, hash2curve/src/hash2field.rs, hash2curve/src/map2curve.rs, k256/src/arithmetic/hash2curve.rs, p256/src/arithmetic/hash2curve.rs, p256/tests/projective.rs, p384/src/arithmetic/hash2curve.rs, p521/src/arithmetic/hash2curve.rs
This PR removes `hash2curve::FromOkm` in favor of `Reduce`.
This was previously discussed in #1295.
=> `hash2curve`: replace `FromOkm` with `Reduce`

ed448-goldilocks/src/field/element.rs, hash2curve/src/map2curve.rs, k256/src/arithmetic/hash2curve.rs, p256/src/arithmetic/hash2curve.rs, p384/src/arithmetic/hash2curve.rs, p521/src/arithmetic/hash2curve.rs
This isn't needed anymore. We can now also have a correctly optimized default implementation for `MapToCurve::add_and_map_to_subgroup()`.
=> `hash2curve`: remove `MapToCurve::CurvePoint`

ed448-goldilocks/src/decaf/points.rs, ed448-goldilocks/src/field/element.rs, hash2curve/src/group_digest.rs, hash2curve/src/map2curve.rs, k256/src/arithmetic/hash2curve.rs, k256/src/arithmetic/projective.rs, p256/src/arithmetic/hash2curve.rs, p384/src/arithmetic/hash2curve.rs, p521/src/arithmetic/hash2curve.rs, primeorder/src/projective.rs
This PR implements `CofactorGroup` for `ed448-goldilocks` curves, `k256` and `primeorder` curves. Apart from `EdwardsPoint` they are all no-op.
Additionally, `MapToCurve` now can rely on `CofactorGroup` to facilitate `hash_from_bytes()` and `encode_from_bytes()`.
=> Implement `CofactorGroup` for all relevant curves

ed448-goldilocks/src/constants.rs, ed448-goldilocks/src/decaf/points.rs, ed448-goldilocks/src/lib.rs
=> `ed448-goldilocks`: remove unnecessary `constants` module

bign256/src/arithmetic/field.rs, bign256/src/arithmetic/scalar.rs, bp256/src/arithmetic/field.rs, bp256/src/arithmetic/scalar.rs, bp384/src/arithmetic/field.rs, bp384/src/arithmetic/scalar.rs, p192/src/arithmetic/field.rs, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/field.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs, p521/src/arithmetic/scalar.rs, sm2/src/arithmetic/field.rs, sm2/src/arithmetic/scalar.rs
This defines the Montgomery field parameters `FieldParams` and `ScalarParams` for all curves which use Montgomery field representations, except for `k256` which doesn't use `primefield` (yet).
These aren't actually used yet, but getting them defined is the first step towards migrating to `MontyField` as the internal field element representation.
=> Use `primefield::monty_field_params!` where applicable

x448/src/lib.rs
This rewrites `Secret` to an opaque object to make sure they are not reused.
=> x448: make `Secret` an `EphemeralSecret`

p256/src/arithmetic/field.rs, p384/src/arithmetic/field.rs, p384/src/arithmetic/scalar.rs, primefield/src/monty.rs
Uses a common upstream implementation rather than a copy-pasted one
=> p256+p384: use `MontyFieldElement::sqn_vartime`

k256/src/schnorr.rs, k256/src/schnorr/signing.rs, k256/src/schnorr/verifying.rs
This changes `k256::schnorr::{SigningKey, VerifyingKey}` to have separate `from_bytes` and `from_slice` methods where the `from_bytes` method takes `&FieldBytes` as an argument (i.e. `from_bytes` has effectively been renamed to `from_slice`).
Additionally this adds a `TryFrom<AffinePoint>` impl to `VerifyingKey` which auto-inverts the point if the y-coordinate is odd, which should resolve #1070.
=> k256: split Schnorr `from_bytes`/`from_slice`; fix #1070

.github/workflows/bignp256.yml, .github/workflows/bp256.yml, .github/workflows/bp384.yml, .github/workflows/p192.yml, .github/workflows/p224.yml, .github/workflows/p384.yml, .github/workflows/p521.yml, .github/workflows/sm2.yml
Run tests on downstream curve crates when `primefield` and/or `primeorder` are changed
=> CI: trigger builds on `primefield`/`primeorder` changes

bignp256/src/arithmetic/field.rs, bignp256/src/arithmetic/scalar.rs, bp256/src/arithmetic/field.rs, bp256/src/arithmetic/scalar.rs, bp384/src/arithmetic/field.rs, bp384/src/arithmetic/scalar.rs, p192/src/arithmetic/field.rs, p192/src/arithmetic/scalar.rs, p224/src/arithmetic/scalar.rs, p256/src/arithmetic/field.rs, p256/src/arithmetic/scalar.rs, p521/src/arithmetic/field.rs, p521/src/arithmetic/scalar.rs, primefield/src/dev.rs, primefield/src/macros.rs, primefield/src/monty.rs, sm2/src/arithmetic/field.rs, sm2/src/arithmetic/scalar.rs
Previously it was `&[u64]`, which dates back to the original code which was adapted from `ff_derive`.
This changes the argument to be a `Uint` (which can be a different number of limbs from `Self`), and also changes `MontyFieldParams::T` to be a `Uint` as well (where `T` can be used to compute many other constants, often by raising them to the power of `T`).
This simplifies dealing with 32-bit vs 64-bit platforms, and also should make it easier to provide a generic implementation of `sqrt` where we may want to calculate constants based on `T`.
=> primefield: make exponent of `pow_vartime` a `Uint`

primefield/src/monty.rs, primefield/src/monty/sqrt.rs
- Extracts `sqrt` implementations into their own module
- Ensures all constants are computed using `const`
- Extracts algorithms into their own function; test individually
- Adds internal `mod_residue` for algorithm selection
=> primefield: sqrt improvements

Cargo.lock, sm2/src/pke.rs
Notably this needed some `OctetStringRef`-related changes to `sm2`
=> Bump `der` to v0.8.0-rc.9

primefield/Cargo.toml
Our 1.85 MSRV amply supports it, and it's useful for downstream crates e.g. #1467
=> subtle: enable `const-generics` feature

primefield/src/macros.rs, primefield/src/monty.rs
Being able to compute `ROOT_OF_UNITY` at compile time is super cool! The only problem is we're running `modpow` at compile time, and miri is slow. For large fields, it may be impractically slow.
This makes it possible to define field parameters that include a precomputed `ROOT_OF_UNITY` constant.
=> primefield: support precomputed `ROOT_OF_UNITY` constant

Cargo.lock, x448/Cargo.toml, x448/src/lib.rs
Some implementations (like rpgp) will serialize a secret and can use static secret similar to what we can find in x25519.
This is a fixup on https://github.com/RustCrypto/elliptic-curves/pull/1378 which removed that support
=> x448: Add `StaticSecret` in a feature-flag

bignp256/src/lib.rs, bp256/src/lib.rs, bp384/src/lib.rs, ed448-goldilocks/src/lib.rs, hash2curve/src/lib.rs, k256/src/lib.rs, p192/src/lib.rs, p224/src/lib.rs, p256/src/lib.rs, p384/src/lib.rs, p521/src/lib.rs, primefield/src/lib.rs, primeorder/src/lib.rs, sm2/src/lib.rs
The former was removed from nightly. See RustCrypto/traits#2028
=> Switch from `doc_auto_cfg` to `doc_cfg`
